const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const root=path.resolve(__dirname,'..')
const read=p=>fs.readFileSync(path.join(root,p),'utf8')

const room=read('components/world/weave-system-room.tsx')
assert.ok(room.includes('data-weave-room={roomKey}'),'Reusable WEAVE room exposes room identity')
assert.ok(room.includes('usePresenceCamera'),'Reusable WEAVE room stays attached to Presence Camera')
assert.ok(room.includes('System pulse'),'Reusable WEAVE room exposes live system pulse')

const converted=[
 ['app/client/loops/page.tsx','client-loop-field'],
 ['app/(app)/admin/loop-workshop/page.tsx','administration-loop-workshop'],
 ['app/(app)/bridger/subscription/page.tsx','bridger-continuance'],
 ['app/(app)/bridger/numbers/page.tsx','bridger-number-bay'],
 ['app/(app)/admin/bridger-numbers/page.tsx','administration-number-engine'],
]
for(const [file,key] of converted){
 const source=read(file)
 assert.ok(source.includes('WeaveSystemRoom'),file+' uses the shared environment room')
 assert.ok(source.includes('roomKey="'+key+'"'),file+' preserves its spatial room identity')
 assert.ok(!source.includes('min-h-screen bg-slate-950'),file+' does not recreate an opaque standalone page')
}

const bridgerNumbers=read('app/(app)/bridger/numbers/page.tsx')
const bridgerNumbersApi=read('app/api/bridger/numbers/route.ts')
const adminNumbers=read('app/(app)/admin/bridger-numbers/page.tsx')
assert.ok(!bridgerNumbers.includes('n.acquisition_cost'),'Bridger Number Bay never renders provider acquisition cost')
assert.ok(!bridgerNumbersApi.includes('acquisition_cost'),'Bridger Number API never returns provider acquisition cost')
assert.ok(adminNumbers.includes('n.acquisition_cost'),'Administration retains internal acquisition cost')
assert.ok(adminNumbers.includes('price_flame_coin'),'Administration retains Bridger Flame Coin price')

const continuance=read('app/(app)/bridger/subscription/page.tsx')
assert.ok(!continuance.includes('bg-white shadow-sm'),'Bridger Continuance no longer uses generic white web cards')
assert.ok(!continuance.includes('text-gray-'),'Bridger Continuance uses WEAVE environment language')

const camera=read('lib/presence-camera.ts')
for(const key of ['client-loop-field','number-bay','bridger-continuance','loop-workshop','number-control','infrastructure','visual-systems','environment-organizer','dj-workshop','client-deposit-control','enterprise-dream-authority']){
 assert.ok(camera.includes("key:'"+key+"'"),key+' has a distinct Presence Camera scene')
}

const css=read('app/globals.css')
assert.ok(css.includes('Environment-first enforcement.'),'Authenticated legacy roots are absorbed into the persistent world')

const rootLayout=read('app/layout.tsx')
assert.equal((rootLayout.match(/<PresenceCameraProvider>/g)||[]).length,1,'Exactly one Presence Camera provider owns the application')
assert.equal((rootLayout.match(/<WeaveWorldEnvironment\s*\/>/g)||[]).length,1,'Exactly one persistent WEAVE world owns the application')
assert.ok(rootLayout.includes('<WeaveEnvironmentTransit>'),'Global environment transit remains active')
assert.ok(rootLayout.includes('<InteractionMotionLayer />'),'Interaction output remains globally visible')
assert.ok(rootLayout.includes('<WeavePresenceAmbience />'),'Persistent WEAVE world mounts one adaptive presence ambience engine')

const normalBackdrop=read('components/world/weave-normal-world-backdrop.tsx')
const bridgePlazaPage=read('app/(app)/weave/page.tsx')
assert.ok(normalBackdrop.includes('data-weave-world-material="stone-bronze-fire-water"'),'Persistent WEAVE world declares realistic stone, bronze, fire and water materials')
assert.ok(normalBackdrop.includes('FlameBrazier'),'Persistent normal world uses architectural flame features instead of abstract star fields')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-theme="continuous-moving-system"'),'Bridge Plaza page is one continuous moving system rather than a card layout')
assert.ok(!bridgePlazaPage.includes('grid gap-3 sm:grid-cols-2 xl:grid-cols-4'),'Bridge Plaza removes the four architecture-card row')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-station="client-support"'),'Client support is an entered Plaza station instead of a permanent side card')
assert.ok(bridgePlazaPage.includes('File Folders are shown as a live ledger, not a stack of cards.'),'Support station explicitly preserves ledger movement instead of card rendering')

const artifact=read('components/events/flame-event-artifact.tsx')
const bridgePlaza=read('components/world/bridge-plaza-map.tsx')
const weaveHero=read('components/weave-hero-3d.tsx')
const bridgeRadiance=read('components/bridge/bridge-radiance-world.tsx')
const eventDecor=read('components/events/flame-event-world-decorations.tsx')
const clientEvent=read('components/events/client-flame-event-dashboard.tsx')
assert.ok(artifact.includes('FlameEventArtifact3D'),'Canonical Flame Event 4D artifact exists')
assert.ok(artifact.includes('FlameEventArtifactMark'),'Canonical Flame Event interface mark exists')
assert.ok(!bridgePlaza.includes('FlameEventArtifact3D'),'Bridge Plaza no longer uses the abstract Flame Event artifact as its physical world')
assert.ok(bridgePlaza.includes('FlameFountain'),'Bridge Plaza has a central living flame fountain')
assert.ok(bridgePlaza.includes('TerraceWing')&&bridgePlaza.includes('DistrictEntrance'),'Bridge Plaza uses architectural terraces and real district entrances')
assert.ok(bridgePlaza.includes('StoneFloor')&&bridgePlaza.includes('FlameFountain'),'Bridge Plaza uses grounded physical architecture around the central movement point')
assert.ok(!bridgePlaza.includes('HumanFigure'),'Bridge Plaza removes literal human proxy figures')
assert.ok(bridgePlaza.includes('GrandHall')&&bridgePlaza.includes('Arcade'),'Bridge Plaza replaces figures with monumental hall architecture and deep arcades')
assert.ok(bridgePlaza.includes('SystemRoute'),'Bridge Plaza movement is carried by live routes between the central WEAVE point and districts')
assert.ok(bridgePlaza.includes('WorldCamera')&&bridgePlaza.includes('onArrival'),'Entering a district physically moves the camera before navigation')
assert.ok(bridgePlaza.includes('WorldInscriptions'),'School, Board, Subject and Topics exist as spatial world information rather than rendered cards')
assert.ok(bridgePlaza.includes('data-bridge-plaza-system="continuous-moving-world"'),'Bridge Plaza declares one continuous world runtime')
assert.ok(bridgePlaza.includes('WEAVE HALL')&&bridgePlaza.includes('ORDER · CONTINUITY · MOVEMENT'),'Bridge Plaza has a central order/continuity hall identity')
assert.ok(bridgePlaza.includes('const bell=useRef'),'Bridge Plaza hall visibly contains a bell structure')
assert.ok(!bridgePlaza.includes('torusKnotGeometry'),'Bridge Plaza no longer uses the old gold/green woven ring object')
assert.ok(!bridgePlaza.includes("color='#e8b93f'") && !bridgePlaza.includes('color="#e8b93f"'),'Bridge Plaza no longer hard-codes the old gold ring identity')
assert.ok(!bridgePlaza.includes("color='#14b8a6'") && !bridgePlaza.includes('color="#14b8a6"'),'Bridge Plaza no longer hard-codes the old teal ring identity')
assert.ok(weaveHero.includes('FlameEventArtifact3D'),'Homepage 3D hero uses the same canonical artifact')
assert.ok(!weaveHero.includes('torusKnotGeometry'),'Homepage no longer revives the old woven ring motif')
assert.ok(bridgeRadiance.includes('FlameEventArtifact3D'),'Bridge Radiance portals use the same artifact language')
assert.ok(!bridgeRadiance.includes('torusGeometry'),'Bridge Radiance no longer uses generic torus portals')
assert.ok(eventDecor.includes('FlameEventArtifactMark'),'Global Flame Event atmosphere uses the canonical artifact')
assert.ok(clientEvent.includes('FlameEventArtifactMark'),'Client Flame Event center uses the canonical artifact')

const presenceAmbience=read('components/world/weave-presence-ambience.tsx')
const djBroadcastPlayer=read('components/dj-broadcast-player.tsx')
assert.ok(presenceAmbience.includes('makeHallImpulse'),'Presence ambience builds hall reverb procedurally')
assert.ok(presenceAmbience.includes('playFootstep'),'Presence ambience carries distant stone footsteps')
assert.ok(presenceAmbience.includes('playBell'),'Presence ambience carries occasional hall bell resonance')
assert.ok(presenceAmbience.includes('playDistantMovement'),'Presence ambience carries subtle unseen movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:dj-audio-state'"),'Presence ambience listens to the live WEAVE DJ mix')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:personal-dj'"),'Presence ambience also ducks beneath personal File Folder DJ playback')
assert.ok(presenceAmbience.includes('ambience.musicGain')&&presenceAmbience.includes('ambience.voiceGain'),'Presence ambience reads live Administration-controlled music and voice ducking')
assert.ok(djBroadcastPlayer.includes("new CustomEvent('weave:dj-audio-state'"),'Global DJ publishes playback state for environmental mixing')
assert.ok(djBroadcastPlayer.includes('data-weave-dj-broadcast="true"'),'Global DJ audio element is explicitly identified as the WEAVE broadcast source')

const visualProfile=read('lib/weave-visual-profile.ts')
const visualRuntime=read('lib/weave-visual-runtime.ts')
const visualAdminApi=read('app/api/admin/visual-systems/route.ts')
const visualPublicApi=read('app/api/visual-runtime/route.ts')
const visualWorkshop=read('app/(app)/admin/visual-systems/page.tsx')
const visualRuntimeHook=read('components/world/use-visual-runtime.ts')
const interactionMotionField=read('components/world/interaction-motion-field.tsx')
const interactionMotionLayer=read('components/world/interaction-motion-layer.tsx')
const interactionMotionBus=read('lib/weave-interaction-motion.ts')
const fileFolderWorldApi=read('app/api/client/file-folder-world/route.ts')
const growthWorldApi=read('app/api/client/growth-world/route.ts')
const dailyProspectClaimUi=read('components/bridger/daily-prospect-claim.tsx')
const flameEventWorld=read('components/events/flame-event-world-decorations.tsx')
const adminWorkshop=read('app/(app)/admin/workshop/page.tsx')
const appSidebar=read('components/app-sidebar.tsx')
const operatingRoom=read('components/world/role-operating-room.tsx')
const dashboardWorld=read('components/world/weave-dashboard-world.tsx')
assert.ok(visualProfile.includes('FLAME_ARTIFACT_SURFACES'),'Visual runtime has an explicit surface registry')
assert.ok(visualProfile.includes("red:'#fb7185'") && visualProfile.includes("sky:'#7dd3fc'"),'Published visual profile preserves Flame Event red/sky signature')
assert.ok(visualProfile.includes("'bridge-plaza-core'")&&visualProfile.includes("'client-event'"),'Visual runtime covers Bridge Plaza through Client Flame Event')
assert.ok(visualRuntime.includes('weave_visual_profiles')&&visualRuntime.includes('weave_visual_profile_history'),'Visual runtime persists draft, published state and history')
assert.ok(visualRuntime.includes('rollbackVisualProfile'),'Visual runtime supports published rollback')
assert.ok(visualAdminApi.includes("user.role!=='admin'"),'Only Administration can publish visual runtime changes')
assert.ok(visualAdminApi.includes("action==='publish'")&&visualAdminApi.includes("action==='rollback'"),'Administration API exposes publish and rollback actions')
assert.ok(visualPublicApi.includes('getPublishedVisualProfile'),'Public runtime exposes published visual state only')
assert.ok(visualPublicApi.includes('DEFAULT_FLAME_ARTIFACT_CONFIG'),'Public runtime has a compiled safe fallback')
assert.ok(visualRuntimeHook.includes("createRuntimeResource('/api/visual-runtime'"),'Shared Visual Runtime reads the published runtime profile')
assert.ok(read('lib/runtime-resource.ts').includes('15000'),'Mounted visual systems refresh published runtime state without deployment')
assert.ok(artifact.includes('useVisualRuntime'),'Canonical Flame artifact consumes the shared live Visual Runtime')
assert.ok(artifact.includes('surface?:FlameArtifactSurface'),'Artifact applies per-surface runtime placement controls')
assert.ok(visualWorkshop.includes('Visual Systems Workshop')&&visualWorkshop.includes('Publish Live'),'Administration has a live Visual Systems Workshop')
assert.ok(visualWorkshop.includes("run('rollback'"),'Visual Systems Workshop can roll back a published revision')
assert.ok(visualWorkshop.includes('configOverride={draft}'),'Visual Systems Workshop previews draft state before publishing')
assert.ok(visualProfile.includes("type VisualWorldMode='normal'|'flame-event'|'quiet-river'|'ceremony'|'night-operations'"),'Visual Runtime defines explicit world-motion operating modes')
assert.ok(visualProfile.includes('flameIntensity')&&visualProfile.includes('riverIntensity')&&visualProfile.includes('routeCurrent')&&visualProfile.includes('emergence'),'Visual Runtime persists Flame, River, route-current and system-emergence controls')
assert.ok(interactionMotionField.includes('drawFlames')&&interactionMotionField.includes('drawRiver')&&interactionMotionField.includes('drawEmbers'),'Interaction Motion Field procedurally renders flame, river and ember motion')
assert.ok(interactionMotionField.includes('requestAnimationFrame'),'Interaction Motion Field is a live animation runtime rather than a static background')
assert.ok(interactionMotionField.includes('budget.reducedMotion'),'Interaction Motion Field respects reduced-motion accessibility')
assert.ok(flameEventWorld.includes('<InteractionMotionField forceEvent'),'Flame Event uses the live Flame + Burning River field as its atmosphere')
assert.ok(normalBackdrop.includes('<InteractionMotionField'),'Normal WEAVE world carries a lower-intensity Interaction Motion field')
assert.ok(bridgePlaza.includes('useVisualRuntime')&&bridgePlaza.includes('routeCurrent'),'Bridge Plaza movement current is driven by the published Visual Runtime')
assert.ok(visualWorkshop.includes('World motion authority'),'Administration Visual Systems Workshop exposes world-motion authority')
assert.ok(visualWorkshop.includes('Flame Field')&&visualWorkshop.includes('Burning River')&&visualWorkshop.includes('Live system emergence'),'Administration can tune Flame, River and live-system emergence without source edits')
assert.ok(visualWorkshop.includes("new Event('weave:visual-runtime-published')"),'Publishing or rollback refreshes mounted Visual Runtime consumers immediately')
assert.ok(interactionMotionBus.includes("type WeaveMotionKind=")&&interactionMotionBus.includes("'emergence'")&&interactionMotionBus.includes("'value'")&&interactionMotionBus.includes("'interruption'"),'WEAVE has one semantic motion vocabulary for real interaction')
assert.ok(interactionMotionLayer.includes("window.addEventListener('weave:presence-output'")&&interactionMotionLayer.includes("window.addEventListener('weave:system-motion'"),'Global motion layer joins human intent with confirmed system movement')
assert.ok(interactionMotionLayer.includes("pulse.kind==='ignition'")&&interactionMotionLayer.includes("pulse.kind==='river'")&&interactionMotionLayer.includes("pulse.kind==='route'")&&interactionMotionLayer.includes("pulse.kind==='emergence'")&&interactionMotionLayer.includes("pulse.kind==='value'"),'Global motion layer renders distinct physical responses instead of one generic ripple')
assert.ok(interactionMotionField.includes("window.addEventListener('weave:system-motion'"),'Underlying Flame/River field surges from confirmed system movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:system-motion'"),'Procedural ambience responds to confirmed system movement through the DJ-aware mixer')
assert.ok(fileFolderWorldApi.includes('motion:fileFolderMotion(action)'),'File Folder API returns motion meaning with confirmed world state')
assert.ok(growthWorldApi.includes('motion:growthMotion(action)'),'Growth World API returns motion meaning with confirmed growth state')
assert.ok(dailyProspectClaimUi.includes("kind:'route'")&&dailyProspectClaimUi.includes('Daily Prospect entered Bridger outreach'),'Daily Prospect claim moves visibly into Bridger outreach')
assert.ok(bridgerNumbers.includes("kind:'value'")&&bridgerNumbers.includes("kind:'confirmation'"),'Number Bay purchase, order, delivery and verification have confirmed motion responses')
assert.ok(bridgePlaza.includes("kind:'route'")&&bridgePlaza.includes("kind:'arrival'"),'Bridge Plaza physical travel emits route and arrival movement')
assert.ok(visualWorkshop.includes('data-admin-motion-tests="true"')&&visualWorkshop.includes('Admin motion test'),'Administration can test motion responses without creating business records')
for(const source of [adminWorkshop,appSidebar,operatingRoom,dashboardWorld]){
 assert.ok(source.includes('/admin/visual-systems'),'Administration navigation exposes Visual Systems Workshop')
}
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_visual_systems_workshop.sql')),'Visual Systems Workshop migration exists')

const environmentRegistry=read('lib/weave-environment-registry.ts')
const environmentRuntime=read('lib/weave-environment-organizer.ts')
const environmentAdminApi=read('app/api/admin/environment-organizer/route.ts')
const environmentPublicApi=read('app/api/environment-organizer/route.ts')
const environmentProvider=read('components/world/environment-organizer-provider.tsx')
const environmentWorkshop=read('app/(app)/admin/environment-organizer/page.tsx')
const environmentRuntimeProfile=read('lib/weave-environment-runtime-profile.ts')
const environmentRuntimeControls=read('components/admin/environment-runtime-controls.tsx')
const environmentRuntimeHook=read('components/world/use-environment-runtime-config.ts')
const environmentTransit=read('components/world/weave-environment-transit.tsx')
const bridgerOperatingRoom=read('components/bridger/bridger-operating-environment.tsx')
const clientFileFolder=read('components/system-switch/client-file-folder-operating-environment.tsx')
const clientFileFolder3d=read('components/system-switch/client-file-folder-3d.tsx')
assert.ok(clientFileFolder3d.includes('visualRuntime.world.emergence')&&clientFileFolder3d.includes('visualRuntime.world.routeCurrent'),'Client File Folder construction and route movement consume live emergence/current controls')
const fileFolderOpenWorld=read('components/system-switch/file-folder-open-world.tsx')
assert.ok(fileFolderOpenWorld.includes('body.motion||fileFolderMotion'),'Client File Folder consumes server-confirmed motion meaning')
assert.ok(fileFolderOpenWorld.includes("status==='complete'")&&fileFolderOpenWorld.includes('commissioned and live'),'Automatic build completion produces emergence without requiring a click')
const clientNavigation=read('components/client-navigation.tsx')
const clientLayout=read('app/client/layout.tsx')
const supportFileFolderPage=read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')

assert.ok(!operatingRoom.toLowerCase().includes('position map'),'Agent/Admin Operating Room removes Position Map card')
assert.ok(!bridgerOperatingRoom.toLowerCase().includes('position map'),'Bridger Operating Room removes Position Map card')
assert.ok(environmentRegistry.includes('WEAVE_ENVIRONMENT_REGISTRY'),'Environment Organizer has an explicit page/card registry')
assert.ok(environmentRegistry.includes("kind:'card'")&&environmentRegistry.includes("kind:'page'"),'Environment Organizer registers both cards and pages')
assert.ok(environmentRegistry.includes("protected:true"),'Environment Organizer protects critical control surfaces')
assert.ok(environmentRegistry.includes("key:'admin-integrity-engine'")&&environmentRegistry.includes("route:'/admin/dev-workshop'"),'Integrity Engine is a protected Administration environment surface')
assert.ok(environmentRuntime.includes('weave_environment_surfaces'),'Environment organization persists in the database')
assert.ok(environmentRuntime.includes('weave_environment_runtime_profiles'),'Environment loading and ambience profile persists in the database')
assert.ok(environmentRuntime.includes('setEnvironmentRuntimeConfig')&&environmentRuntime.includes('restoreEnvironmentRuntimeDefaults'),'Administration can publish or restore environment runtime settings')
assert.ok(environmentRuntimeProfile.includes('bootMinMs:3600')&&environmentRuntimeProfile.includes('transitMinMs:900'),'Environment defaults deliberately allow more formation time')
assert.ok(environmentRuntimeProfile.includes('waitForFonts:true')&&environmentRuntimeProfile.includes('waitForImages:true'),'Environment defaults wait for typography and media')
assert.ok(environmentAdminApi.includes("action==='set_runtime'")&&environmentAdminApi.includes("action==='restore_runtime_defaults'"),'Environment Organizer API exposes live runtime publication')
assert.ok(environmentPublicApi.includes('DEFAULT_ENVIRONMENT_RUNTIME_CONFIG'),'Public environment runtime has a safe compiled fallback')
assert.ok(environmentRuntimeHook.includes("'weave-environment-refresh'")&&read('lib/runtime-resource.ts').includes('window.addEventListener(event,published)'),'Published runtime settings can refresh mounted environments immediately')
assert.ok(environmentTransit.includes('MutationObserver')&&environmentTransit.includes('document.fonts.ready')&&environmentTransit.includes('document.images'),'Environment cover waits for component, font and media readiness')
assert.ok(environmentRuntimeControls.includes('Loading + Presence Workshop'),'Administration Environment Organizer exposes loading and presence controls')
assert.ok(environmentRuntimeControls.includes("publish('set_runtime')"),'Administration can publish environment runtime changes live')
assert.ok(environmentRuntimeControls.includes("weave:ambience-preview"),'Administration can preview presence sounds before publishing')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:ambience-preview'"),'Presence engine receives Administration sound previews')
assert.ok(environmentRuntime.includes('setEnvironmentSurfaceVisibility')&&environmentRuntime.includes('setEnvironmentSurfaceOrder'),'Environment runtime supports withdrawal/restoration and ordering')
assert.ok(environmentAdminApi.includes("user.role!=='admin'"),'Only Administration can mutate environment organization')
assert.ok(environmentAdminApi.includes("action==='set_visibility'")&&environmentAdminApi.includes("action==='set_order'"),'Environment Organizer API exposes visibility and ordering actions')
assert.ok(environmentPublicApi.includes('getEnvironmentOrganizerState'),'Running clients can read the active environment organization')
assert.ok(environmentProvider.includes('EnvironmentPageGuard'),'Withdrawn registered pages are guarded at runtime')
assert.ok(environmentProvider.includes('useEnvironmentRuntimeConfig')&&environmentRuntimeHook.includes('weave-environment-refresh'),'Organizer changes can refresh mounted navigation without deployment')
assert.ok(environmentWorkshop.includes('Environment Organizer')&&environmentWorkshop.includes('Remove'),'Administration has the page/card organizer workshop')
assert.ok(appSidebar.includes('/admin/environment-organizer'),'Administration sidebar exposes Environment Organizer')
assert.ok(adminWorkshop.includes('/admin/environment-organizer'),'Admin Workshop exposes Environment Organizer')
assert.ok(adminWorkshop.includes('WEAVE Integrity Engine')&&adminWorkshop.includes('/admin/dev-workshop?tab=terminal'),'Admin Workshop exposes the live Integrity Engine repair surface')
assert.ok(operatingRoom.includes('/admin/environment-organizer'),'Administration Operating Room exposes Environment Organizer')
assert.ok(dashboardWorld.includes('/admin/environment-organizer'),'Administration World exposes Environment Organizer')
assert.ok(clientNavigation.includes('useEnvironmentOrganizer'),'Client navigation honors the organizer registry')
assert.ok(clientLayout.includes('EnvironmentOrganizerProvider'),'Client world mounts the organizer runtime')
assert.ok(supportFileFolderPage.includes('Support · Read only'),'Support File Folder preserves role awareness in a compact context strip')
assert.ok(supportFileFolderPage.includes('md:static'),'Support context is sticky only where mobile needs it')
assert.ok(!supportFileFolderPage.includes("['Recognize'"),'Support File Folder removes the duplicated five-stage card strip')
assert.ok(clientFileFolder.includes('Command Citadel'),'Main File Folder has one strategic command center')
assert.ok(clientFileFolder.includes('BUILD_LADDER'),'Main File Folder exposes an ordered construction lifecycle')
assert.ok(clientFileFolder.includes('Blueprint')&&clientFileFolder.includes('Foundation')&&clientFileFolder.includes('Commissioning')&&clientFileFolder.includes('Live operation'),'File Folder construction communicates real build stages')
assert.ok(clientFileFolder.includes('visibleSurfaceKeys'),'File Folder 3D receives runtime-organized districts')
assert.ok(clientFileFolder3d.includes('ConstructionSite')&&clientFileFolder3d.includes('ScaffoldEnvelope')&&clientFileFolder3d.includes('Crane'),'File Folder world renders real progressive construction sites with scaffolding and cranes')
assert.ok(clientFileFolder3d.includes('PavedRoad')&&clientFileFolder3d.includes('WaterChannel'),'File Folder territory physically connects districts with roads and water infrastructure')
assert.ok(clientFileFolder3d.includes('Persistent construction territory'),'File Folder is framed as a progressive construction territory rather than a floating dashboard')
assert.ok(!clientFileFolder3d.includes('<Stars'),'File Folder removes the old star-field treatment')
assert.ok(!clientFileFolder3d.includes('<gridHelper'),'File Folder removes the old sci-fi grid floor')
assert.ok(clientFileFolder3d.includes('CommandHall')&&clientFileFolder3d.includes('MarketDistrict')&&clientFileFolder3d.includes('EnterpriseKeep'),'File Folder uses grounded architectural districts')
assert.ok(clientFileFolder3d.includes('FileFolderCamera'),'Selecting a File Folder district redirects the world camera focus')
assert.ok(clientFileFolder3d.includes('isMarket')&&clientFileFolder3d.includes('isMedia')&&clientFileFolder3d.includes('isEnterprise')&&clientFileFolder3d.includes('isIntelligence')&&clientFileFolder3d.includes('isNetwork'),'Completed systems retain distinct architectural silhouettes by function')
assert.ok(fileFolderOpenWorld.includes('Materials Depot')&&fileFolderOpenWorld.includes('Construction Yard')&&fileFolderOpenWorld.includes('Build Intelligence'),'Build support surfaces are ordered by construction purpose')
assert.ok(fileFolderOpenWorld.includes('data-construction-workspace="progressive-site"'),'File Folder construction tools are contained inside one progressive site')
assert.ok(fileFolderOpenWorld.includes('Walk the build site'),'Construction support navigation behaves as site travel rather than a sidebar page menu')
assert.ok(fileFolderOpenWorld.includes('data-build-site-awareness="compact-sticky-rail"'),'Build-site awareness stays in one compact sticky rail on mobile')
assert.ok(fileFolderOpenWorld.includes("readOnly?'top-11 md:top-0':'top-0'"),'Support build-site awareness sits below the support context strip without overlap')
assert.ok(clientFileFolder.includes('data-file-folder-awareness="compact-build-sequence"'),'Client File Folder keeps construction sequence awareness compact instead of duplicating a tall navigation block')
assert.ok(!clientFileFolder.includes('studioDistricts.map((item,index)=><button'),'Client wrapper no longer duplicates the detailed construction-site navigation')
assert.ok(clientFileFolder3d.includes('h-[390px] sm:h-[500px] lg:h-[590px]'),'File Folder 3D uses a shorter mobile viewport while preserving larger-screen depth')
assert.ok(clientFileFolder.includes('data-file-folder-world="progressive-construction-territory"'),'Client File Folder declares the progressive world runtime')
assert.ok(clientFileFolder.includes('one continuous site'),'Construction opens directly into one continuous site rather than an intermediary catalog dashboard')
assert.ok(fileFolderOpenWorld.includes('materialPurpose'),'Materials explain which blueprints/functions they enable')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_environment_organizer.sql')),'Environment Organizer migration exists')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260927_environment_runtime_controls.sql')),'Environment runtime-control migration exists')

console.log('environment-grade regression checks passed')
