const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const root=path.resolve(__dirname,'..')
const read=p=>fs.readFileSync(path.join(root,p),'utf8')

const room=read('components/world/weave-system-room.tsx')
assert.ok(room.includes('data-weave-room={roomKey}'),'Reusable WEAVE room exposes room identity')
assert.ok(room.includes('usePresenceCamera'),'Reusable WEAVE room stays attached to Presence Camera')
assert.ok(room.includes('System pulse'),'Reusable WEAVE room exposes live system pulse')

const converted=[
 ['app/client/loops/page.tsx','client-loop-field'],
 ['app/(app)/admin/loop-workshop/page.tsx','administration-loop-workshop'],
 ['app/(app)/bridger/subscription/page.tsx','bridger-continuance'],
 ['app/(app)/bridger/numbers/page.tsx','bridger-number-bay'],
 ['app/(app)/admin/bridger-numbers/page.tsx','administration-number-engine'],
]
for(const [file,key] of converted){
 const source=read(file)
 assert.ok(source.includes('WeaveSystemRoom'),file+' uses the shared environment room')
 assert.ok(source.includes('roomKey="'+key+'"'),file+' preserves its spatial room identity')
 assert.ok(!source.includes('min-h-screen bg-slate-950'),file+' does not recreate an opaque standalone page')
}

const bridgerNumbers=read('app/(app)/bridger/numbers/page.tsx')
const bridgerNumbersApi=read('app/api/bridger/numbers/route.ts')
const adminNumbers=read('app/(app)/admin/bridger-numbers/page.tsx')
assert.ok(!bridgerNumbers.includes('n.acquisition_cost'),'Bridger Number Bay never renders provider acquisition cost')
assert.ok(!bridgerNumbersApi.includes('acquisition_cost'),'Bridger Number API never returns provider acquisition cost')
assert.ok(adminNumbers.includes('n.acquisition_cost'),'Administration retains internal acquisition cost')
assert.ok(adminNumbers.includes('price_flame_coin'),'Administration retains Bridger Flame Coin price')

const continuance=read('app/(app)/bridger/subscription/page.tsx')
assert.ok(!continuance.includes('bg-white shadow-sm'),'Bridger Continuance no longer uses generic white web cards')
assert.ok(!continuance.includes('text-gray-'),'Bridger Continuance uses WEAVE environment language')

const camera=read('lib/presence-camera.ts')
for(const key of ['client-loop-field','number-bay','bridger-continuance','loop-workshop','number-control','infrastructure','visual-systems','environment-organizer','dj-workshop','client-deposit-control','enterprise-dream-authority']){
 assert.ok(camera.includes("key:'"+key+"'"),key+' has a distinct Presence Camera scene')
}

const css=read('app/globals.css')
assert.ok(css.includes('Environment-first enforcement.'),'Authenticated legacy roots are absorbed into the persistent world')

const rootLayout=read('app/layout.tsx')
assert.equal((rootLayout.match(/<PresenceCameraProvider>/g)||[]).length,1,'Exactly one Presence Camera provider owns the application')
assert.equal((rootLayout.match(/<WeaveWorldEnvironment\s*\/>/g)||[]).length,1,'Exactly one persistent WEAVE world owns the application')
assert.ok(rootLayout.includes('<WeaveEnvironmentTransit>'),'Global environment transit remains active')
assert.ok(rootLayout.includes('<InteractionMotionLayer />'),'Interaction output remains globally visible')
assert.ok(rootLayout.includes('<WeavePresenceAmbience />'),'Persistent WEAVE world mounts one adaptive presence ambience engine')
const flameReentryTransit=read('components/world/weave-environment-transit.tsx')
assert.ok(!flameReentryTransit.includes('FLAME_REENTRY_AFTER_MS'),'Flame Event cold-entry briefing is not suppressed by an obsolete re-entry timeout')
assert.ok(flameReentryTransit.includes("FLAME_REENTRY_LAST_ACTIVE_KEY"),'Flame Event re-entry state persists last app presence')
assert.ok(flameReentryTransit.includes("resolveEventStatus(FLAME_EVENT"),'Flame Event re-entry briefing follows the October 1 event lifecycle')
assert.ok(flameReentryTransit.includes("const showFlameBriefing=booting&&flameEventActive"),'Flame Event briefing is boot-only and cannot replace ordinary route transit')
assert.ok(flameReentryTransit.includes("const briefs=showFlameBriefing?FLAME_EVENT_BRIEFS:PLATFORM_BRIEFS"),'Normal WEAVE loading briefs remain intact outside eligible Flame Event re-entry')
assert.ok(flameReentryTransit.includes("Burning River")&&flameReentryTransit.includes("The River that Burns"),'Flame Event re-entry identifies the Burning River explicitly')


const liveFlameField=read('components/world/weave-live-flame-field.tsx')
const bridgePlazaPage=read('app/(app)/weave/page.tsx')
assert.ok(liveFlameField.includes('data-weave-live-flame'),'Persistent WEAVE world exposes a live flame field')
assert.ok(liveFlameField.includes("window.addEventListener('pointermove'")&&liveFlameField.includes("window.addEventListener('weave:system-motion'"),'Persistent flame reacts to human presence and confirmed system movement')
assert.ok(!fs.existsSync(path.join(root,'components/world/weave-normal-world-backdrop.tsx')),'Static architectural wallpaper has been removed from the codebase')
assert.ok(!fs.existsSync(path.join(root,'components/world/weave-world-backdrop.tsx')),'Legacy sky/world wallpaper has been removed from the codebase')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-theme="continuous-moving-system"'),'Bridge Plaza page is one continuous moving system rather than a card layout')
assert.ok(!bridgePlazaPage.includes('grid gap-3 sm:grid-cols-2 xl:grid-cols-4'),'Bridge Plaza removes the four architecture-card row')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-station="client-support"'),'Client support is an entered Plaza station instead of a permanent side card')
assert.ok(bridgePlazaPage.includes('Bridge Plaza · System Switch')&&bridgePlazaPage.includes('File Folder View'),'Bridge Plaza exposes System Switch File Folder View as an entered station')

const artifact=read('components/events/flame-event-artifact.tsx')
const bridgePlaza=read('components/world/bridge-plaza-map.tsx')
const weaveHero=read('components/weave-hero-3d.tsx')
const bridgeRadiance=read('components/bridge/bridge-radiance-world.tsx')
const clientEvent=read('components/events/client-flame-event-dashboard.tsx')
assert.ok(artifact.includes('FlameEventArtifact3D'),'Canonical Flame Event 4D artifact exists')
assert.ok(artifact.includes('FlameEventArtifactMark'),'Canonical Flame Event interface mark exists')
assert.ok(!bridgePlaza.includes('FlameEventArtifact3D'),'Bridge Plaza no longer uses the abstract Flame Event artifact as its physical world')
assert.ok(bridgePlaza.includes('FlameFountain'),'Bridge Plaza has a central living flame fountain')
assert.ok(bridgePlaza.includes('TerraceWing')&&bridgePlaza.includes('DistrictEntrance'),'Bridge Plaza uses architectural terraces and real district entrances')
assert.ok(bridgePlaza.includes('StoneFloor')&&bridgePlaza.includes('FlameFountain'),'Bridge Plaza uses grounded physical architecture around the central movement point')
assert.ok(!bridgePlaza.includes('HumanFigure'),'Bridge Plaza removes literal human proxy figures')
assert.ok(bridgePlaza.includes('GrandHall')&&bridgePlaza.includes('Arcade'),'Bridge Plaza replaces figures with monumental hall architecture and deep arcades')
assert.ok(bridgePlaza.includes('SystemRoute'),'Bridge Plaza movement is carried by live routes between the central WEAVE point and districts')
assert.ok(bridgePlaza.includes('WorldCamera')&&bridgePlaza.includes('onArrival'),'Entering a district physically moves the camera before navigation')
assert.ok(bridgePlaza.includes('WorldInscriptions'),'School, Board, Subject and Topics exist as spatial world information rather than rendered cards')
assert.ok(bridgePlaza.includes('data-bridge-plaza-system="continuous-moving-world"'),'Bridge Plaza declares one continuous world runtime')
assert.ok(bridgePlaza.includes('WEAVE HALL')&&bridgePlaza.includes('ORDER · CONTINUITY · MOVEMENT'),'Bridge Plaza has a central order/continuity hall identity')
assert.ok(bridgePlaza.includes('const bell=useRef'),'Bridge Plaza hall visibly contains a bell structure')
assert.ok(!bridgePlaza.includes('torusKnotGeometry'),'Bridge Plaza no longer uses the old gold/green woven ring object')
assert.ok(!bridgePlaza.includes("color='#e8b93f'") && !bridgePlaza.includes('color="#e8b93f"'),'Bridge Plaza no longer hard-codes the old gold ring identity')
assert.ok(!bridgePlaza.includes("color='#14b8a6'") && !bridgePlaza.includes('color="#14b8a6"'),'Bridge Plaza no longer hard-codes the old teal ring identity')
assert.ok(weaveHero.includes('FlameEventArtifact3D'),'Homepage 3D hero uses the same canonical artifact')
assert.ok(!weaveHero.includes('torusKnotGeometry'),'Homepage no longer revives the old woven ring motif')
assert.ok(bridgeRadiance.includes('FlameEventArtifact3D'),'Bridge Radiance portals use the same artifact language')
assert.ok(!bridgeRadiance.includes('torusGeometry'),'Bridge Radiance no longer uses generic torus portals')
assert.ok(!fs.existsSync(path.join(root,'components/events/flame-event-world-decorations.tsx')),'Legacy global Flame Event decoration wallpaper is removed')
assert.ok(clientEvent.includes('FlameEventArtifactMark'),'Client Flame Event center may still use the canonical artifact locally')

const presenceAmbience=read('components/world/weave-presence-ambience.tsx')
const djBroadcastPlayer=read('components/dj-broadcast-player.tsx')
assert.ok(presenceAmbience.includes('makeHallImpulse'),'Presence ambience builds hall reverb procedurally')
assert.ok(presenceAmbience.includes('playFootstep'),'Presence ambience carries distant stone footsteps')
assert.ok(presenceAmbience.includes('playBell'),'Presence ambience carries occasional hall bell resonance')
assert.ok(presenceAmbience.includes('playDistantMovement'),'Presence ambience carries subtle unseen movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:dj-audio-state'"),'Presence ambience listens to the live WEAVE DJ mix')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:personal-dj'"),'Presence ambience also ducks beneath personal File Folder DJ playback')
assert.ok(presenceAmbience.includes('ambience.musicGain')&&presenceAmbience.includes('ambience.voiceGain'),'Presence ambience reads live Administration-controlled music and voice ducking')
assert.ok(djBroadcastPlayer.includes("new CustomEvent('weave:dj-audio-state'"),'Global DJ publishes playback state for environmental mixing')
assert.ok(djBroadcastPlayer.includes('data-weave-dj-broadcast="true"'),'Global DJ audio element is explicitly identified as the WEAVE broadcast source')

const visualProfile=read('lib/weave-visual-profile.ts')
const visualRuntime=read('lib/weave-visual-runtime.ts')
const visualAdminApi=read('app/api/admin/visual-systems/route.ts')
const visualPublicApi=read('app/api/visual-runtime/route.ts')
const visualWorkshop=read('app/(app)/admin/visual-systems/page.tsx')
const visualRuntimeHook=read('components/world/use-visual-runtime.ts')
const interactionMotionField=read('components/world/interaction-motion-field.tsx')
const interactionMotionLayer=read('components/world/interaction-motion-layer.tsx')
const interactionMotionBus=read('lib/weave-interaction-motion.ts')
const fileFolderWorldApi=read('app/api/client/file-folder-world/route.ts')
const growthWorldApi=read('app/api/client/growth-world/route.ts')
const dailyProspectClaimUi=read('components/bridger/daily-prospect-claim.tsx')
const flameEventWorld=read('components/world/weave-live-flame-field.tsx')
const adminWorkshop=read('app/(app)/admin/workshop/page.tsx')
const appSidebar=read('components/app-sidebar.tsx')
const operatingRoom=read('components/world/role-operating-room.tsx')
const dashboardWorld=read('components/world/weave-dashboard-world.tsx')
assert.ok(visualProfile.includes('FLAME_ARTIFACT_SURFACES'),'Visual runtime has an explicit surface registry')
assert.ok(visualProfile.includes("red:'#fb7185'") && visualProfile.includes("sky:'#7dd3fc'"),'Published visual profile preserves Flame Event red/sky signature')
assert.ok(visualProfile.includes("'bridge-plaza-core'")&&visualProfile.includes("'client-event'"),'Visual runtime covers Bridge Plaza through Client Flame Event')
assert.ok(visualRuntime.includes('weave_visual_profiles')&&visualRuntime.includes('weave_visual_profile_history'),'Visual runtime persists draft, published state and history')
assert.ok(visualRuntime.includes('rollbackVisualProfile'),'Visual runtime supports published rollback')
assert.ok(visualAdminApi.includes("user.role!=='admin'"),'Only Administration can publish visual runtime changes')
assert.ok(visualAdminApi.includes("action==='publish'")&&visualAdminApi.includes("action==='rollback'"),'Administration API exposes publish and rollback actions')
assert.ok(visualPublicApi.includes('getPublishedVisualProfile'),'Public runtime exposes published visual state only')
assert.ok(visualPublicApi.includes('DEFAULT_FLAME_ARTIFACT_CONFIG'),'Public runtime has a compiled safe fallback')
assert.ok(visualRuntimeHook.includes("createRuntimeResource('/api/visual-runtime'"),'Shared Visual Runtime reads the published runtime profile')
assert.ok(read('lib/runtime-resource.ts').includes('15000'),'Mounted visual systems refresh published runtime state without deployment')
assert.ok(artifact.includes('useVisualRuntime'),'Canonical Flame artifact consumes the shared live Visual Runtime')
assert.ok(artifact.includes('surface?:FlameArtifactSurface'),'Artifact applies per-surface runtime placement controls')
assert.ok(visualWorkshop.includes('Visual Systems Workshop')&&visualWorkshop.includes('Publish Live'),'Administration has a live Visual Systems Workshop')
assert.ok(visualWorkshop.includes("run('rollback'"),'Visual Systems Workshop can roll back a published revision')
assert.ok(visualWorkshop.includes('configOverride={draft}'),'Visual Systems Workshop previews draft state before publishing')
assert.ok(visualProfile.includes("type VisualWorldMode='normal'|'flame-event'|'quiet-river'|'ceremony'|'night-operations'"),'Visual Runtime defines explicit world-motion operating modes')
assert.ok(visualProfile.includes('flameIntensity')&&visualProfile.includes('riverIntensity')&&visualProfile.includes('routeCurrent')&&visualProfile.includes('emergence'),'Visual Runtime persists Flame, River, route-current and system-emergence controls')
assert.ok(interactionMotionField.includes('drawFlames')&&interactionMotionField.includes('drawRiver')&&interactionMotionField.includes('drawEmbers'),'Interaction Motion Field procedurally renders flame, river and ember motion')
assert.ok(interactionMotionField.includes('requestAnimationFrame'),'Interaction Motion Field is a live animation runtime rather than a static background')
assert.ok(interactionMotionField.includes('budget.reducedMotion'),'Interaction Motion Field respects reduced-motion accessibility')
assert.ok(flameEventWorld.includes('<InteractionMotionField')&&flameEventWorld.includes('forceEvent={flameLive}'),'One live field increases Flame intensity from event state without swapping wallpapers')
assert.ok(!read('components/world/weave-world-environment.tsx').includes('FlameEventWorldDecorations'),'Persistent world never mounts a Flame Event wallpaper layer')
assert.ok(liveFlameField.includes("data-weaveLiveSystem='flame'")||liveFlameField.includes("dataset.weaveLiveSystem='flame'"),'Live flame runtime publishes a global system state for interface effects')
assert.ok(bridgePlaza.includes('useVisualRuntime')&&bridgePlaza.includes('routeCurrent'),'Bridge Plaza movement current is driven by the published Visual Runtime')
assert.ok(visualWorkshop.includes('World motion authority'),'Administration Visual Systems Workshop exposes world-motion authority')
assert.ok(visualWorkshop.includes('Flame Field')&&visualWorkshop.includes('Burning River')&&visualWorkshop.includes('Live system emergence'),'Administration can tune Flame, River and live-system emergence without source edits')
assert.ok(visualWorkshop.includes("new Event('weave:visual-runtime-published')"),'Publishing or rollback refreshes mounted Visual Runtime consumers immediately')
assert.ok(interactionMotionBus.includes("type WeaveMotionKind=")&&interactionMotionBus.includes("'emergence'")&&interactionMotionBus.includes("'value'")&&interactionMotionBus.includes("'interruption'"),'WEAVE has one semantic motion vocabulary for real interaction')
assert.ok(interactionMotionLayer.includes("window.addEventListener('weave:presence-output'")&&interactionMotionLayer.includes("window.addEventListener('weave:system-motion'"),'Global motion layer joins human intent with confirmed system movement')
assert.ok(interactionMotionLayer.includes("pulse.kind==='ignition'")&&interactionMotionLayer.includes("pulse.kind==='river'")&&interactionMotionLayer.includes("pulse.kind==='route'")&&interactionMotionLayer.includes("pulse.kind==='emergence'")&&interactionMotionLayer.includes("pulse.kind==='value'"),'Global motion layer renders distinct physical responses instead of one generic ripple')
assert.ok(interactionMotionField.includes("window.addEventListener('weave:system-motion'"),'Underlying Flame/River field surges from confirmed system movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:system-motion'"),'Procedural ambience responds to confirmed system movement through the DJ-aware mixer')
assert.ok(fileFolderWorldApi.includes('motion:fileFolderMotion(action)'),'File Folder API returns motion meaning with confirmed world state')
assert.ok(growthWorldApi.includes('motion:growthMotion(action)'),'Growth World API returns motion meaning with confirmed growth state')
assert.ok(dailyProspectClaimUi.includes("kind:'route'")&&dailyProspectClaimUi.includes('Daily Prospect entered Bridger outreach'),'Daily Prospect claim moves visibly into Bridger outreach')
assert.ok(bridgerNumbers.includes("kind:'value'")&&bridgerNumbers.includes("kind:'confirmation'"),'Number Bay purchase, order, delivery and verification have confirmed motion responses')
assert.ok(bridgePlaza.includes("kind:'route'")&&bridgePlaza.includes("kind:'arrival'"),'Bridge Plaza physical travel emits route and arrival movement')
assert.ok(visualWorkshop.includes('data-admin-motion-tests="true"')&&visualWorkshop.includes('Admin motion test'),'Administration can test motion responses without creating business records')
for(const source of [adminWorkshop,appSidebar,operatingRoom,dashboardWorld]){
 assert.ok(source.includes('/admin/visual-systems'),'Administration navigation exposes Visual Systems Workshop')
}
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_visual_systems_workshop.sql')),'Visual Systems Workshop migration exists')

const environmentRegistry=read('lib/weave-environment-registry.ts')
const environmentRuntime=read('lib/weave-environment-organizer.ts')
const environmentAdminApi=read('app/api/admin/environment-organizer/route.ts')
const environmentPublicApi=read('app/api/environment-organizer/route.ts')
const environmentProvider=read('components/world/environment-organizer-provider.tsx')
const environmentWorkshop=read('app/(app)/admin/environment-organizer/page.tsx')
const environmentRuntimeProfile=read('lib/weave-environment-runtime-profile.ts')
const environmentRuntimeControls=read('components/admin/environment-runtime-controls.tsx')
const environmentRuntimeHook=read('components/world/use-environment-runtime-config.ts')
const environmentTransit=read('components/world/weave-environment-transit.tsx')
const bridgerOperatingRoom=read('components/bridger/bridger-operating-environment.tsx')
const clientFileFolder=read('components/system-switch/client-file-folder-operating-environment.tsx')
const clientFileFolder3d=read('components/system-switch/client-file-folder-3d.tsx')
assert.ok(clientFileFolder3d.includes('visualRuntime.world.emergence')&&clientFileFolder3d.includes('visualRuntime.world.routeCurrent'),'Client File Folder construction and route movement consume live emergence/current controls')
const fileFolderOpenWorld=read('components/system-switch/file-folder-open-world.tsx')
assert.ok(fileFolderOpenWorld.includes('body.motion||fileFolderMotion'),'Client File Folder consumes server-confirmed motion meaning')
assert.ok(fileFolderOpenWorld.includes("status==='complete'")&&fileFolderOpenWorld.includes('commissioned and live'),'Automatic build completion produces emergence without requiring a click')
const clientNavigation=read('components/client-navigation.tsx')
const clientLayout=read('app/client/layout.tsx')
const supportFileFolderPage=read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')

assert.ok(!operatingRoom.toLowerCase().includes('position map'),'Agent/Admin Operating Room removes Position Map card')
assert.ok(!bridgerOperatingRoom.toLowerCase().includes('position map'),'Bridger Operating Room removes Position Map card')
assert.ok(environmentRegistry.includes('WEAVE_ENVIRONMENT_REGISTRY'),'Environment Organizer has an explicit world surface registry')
assert.ok(environmentRegistry.includes("kind:'station'")&&environmentRegistry.includes("kind:'district'"),'Environment Organizer registers world districts and HUD stations')
assert.ok(environmentRegistry.includes("protected:true"),'Environment Organizer protects critical control surfaces')
assert.ok(environmentRegistry.includes("key:'admin-integrity-engine'")&&environmentRegistry.includes("route:'/admin/dev-workshop'"),'Integrity Engine is a protected Administration environment surface')
assert.ok(environmentRuntime.includes('weave_environment_surfaces'),'Environment organization persists in the database')
assert.ok(environmentRuntime.includes('weave_environment_runtime_profiles'),'Environment loading and ambience profile persists in the database')
assert.ok(environmentRuntime.includes('setEnvironmentRuntimeConfig')&&environmentRuntime.includes('restoreEnvironmentRuntimeDefaults'),'Administration can publish or restore environment runtime settings')
assert.ok(environmentRuntimeProfile.includes('bootMinMs:3600')&&environmentRuntimeProfile.includes('transitMinMs:900'),'Environment defaults deliberately allow more formation time')
assert.ok(environmentRuntimeProfile.includes('waitForFonts:true')&&environmentRuntimeProfile.includes('waitForImages:true'),'Environment defaults wait for typography and media')
assert.ok(environmentAdminApi.includes("action==='set_runtime'")&&environmentAdminApi.includes("action==='restore_runtime_defaults'"),'Environment Organizer API exposes live runtime publication')
assert.ok(environmentPublicApi.includes('DEFAULT_ENVIRONMENT_RUNTIME_CONFIG'),'Public environment runtime has a safe compiled fallback')
assert.ok(environmentRuntimeHook.includes("'weave-environment-refresh'")&&read('lib/runtime-resource.ts').includes('window.addEventListener(event,published)'),'Published runtime settings can refresh mounted environments immediately')
assert.ok(environmentTransit.includes('MutationObserver')&&environmentTransit.includes('document.fonts.ready')&&environmentTransit.includes('document.images'),'Environment cover waits for component, font and media readiness')
assert.ok(environmentRuntimeControls.includes('Loading + Presence Workshop'),'Administration Environment Organizer exposes loading and presence controls')
assert.ok(environmentRuntimeControls.includes("publish('set_runtime')"),'Administration can publish environment runtime changes live')
assert.ok(environmentRuntimeControls.includes("weave:ambience-preview"),'Administration can preview presence sounds before publishing')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:ambience-preview'"),'Presence engine receives Administration sound previews')
assert.ok(environmentRuntime.includes('setEnvironmentSurfaceVisibility')&&environmentRuntime.includes('setEnvironmentSurfaceOrder'),'Environment runtime supports withdrawal/restoration and ordering')
assert.ok(environmentAdminApi.includes("user.role!=='admin'"),'Only Administration can mutate environment organization')
assert.ok(environmentAdminApi.includes("action==='set_visibility'")&&environmentAdminApi.includes("action==='set_order'"),'Environment Organizer API exposes visibility and ordering actions')
assert.ok(environmentPublicApi.includes('getEnvironmentOrganizerState'),'Running clients can read the active environment organization')
assert.ok(environmentProvider.includes('EnvironmentPageGuard'),'Withdrawn registered pages are guarded at runtime')
assert.ok(environmentProvider.includes('useEnvironmentRuntimeConfig')&&environmentRuntimeHook.includes('weave-environment-refresh'),'Organizer changes can refresh mounted navigation without deployment')
assert.ok(environmentWorkshop.includes('Environment Organizer')&&environmentWorkshop.includes('Remove'),'Administration has the page/card organizer workshop')
assert.ok(appSidebar.includes('/admin/environment-organizer'),'Administration sidebar exposes Environment Organizer')
assert.ok(adminWorkshop.includes('/admin/environment-organizer'),'Admin Workshop exposes Environment Organizer')
assert.ok(adminWorkshop.includes('WEAVE Integrity Engine')&&adminWorkshop.includes('/admin/dev-workshop?tab=terminal'),'Admin Workshop exposes the live Integrity Engine repair surface')
assert.ok(operatingRoom.includes('/admin/environment-organizer'),'Administration Operating Room exposes Environment Organizer')
assert.ok(dashboardWorld.includes('/admin/environment-organizer'),'Administration World exposes Environment Organizer')
assert.ok(clientNavigation.includes('useEnvironmentOrganizer'),'Client navigation honors the organizer registry')
assert.ok(clientLayout.includes('EnvironmentOrganizerProvider'),'Client world mounts the organizer runtime')
assert.ok(supportFileFolderPage.includes('Support · Read only'),'Support File Folder preserves role awareness in a compact context strip')
assert.ok(supportFileFolderPage.includes('md:static'),'Support context is sticky only where mobile needs it')
assert.ok(!supportFileFolderPage.includes("['Recognize'"),'Support File Folder removes the duplicated five-stage card strip')
assert.ok(clientFileFolder.includes('Command Citadel'),'Main File Folder has one strategic command center')
assert.ok(clientFileFolder.includes('BUILD_LADDER'),'Main File Folder exposes an ordered construction lifecycle')
assert.ok(clientFileFolder.includes('Blueprint')&&clientFileFolder.includes('Foundation')&&clientFileFolder.includes('Commissioning')&&clientFileFolder.includes('Live operation'),'File Folder construction communicates real build stages')
assert.ok(clientFileFolder.includes('visibleSurfaceKeys'),'File Folder 3D receives runtime-organized districts')
assert.ok(clientFileFolder3d.includes('ConstructionSite')&&clientFileFolder3d.includes('ScaffoldEnvelope')&&clientFileFolder3d.includes('Crane'),'File Folder world renders real progressive construction sites with scaffolding and cranes')
assert.ok(clientFileFolder3d.includes('PavedRoad')&&clientFileFolder3d.includes('WaterChannel'),'File Folder territory physically connects districts with roads and water infrastructure')
assert.ok(clientFileFolder3d.includes('Persistent construction territory'),'File Folder is framed as a progressive construction territory rather than a floating dashboard')
assert.ok(!clientFileFolder3d.includes('<Stars'),'File Folder removes the old star-field treatment')
assert.ok(!clientFileFolder3d.includes('<gridHelper'),'File Folder removes the old sci-fi grid floor')
assert.ok(clientFileFolder3d.includes('CommandHall')&&clientFileFolder3d.includes('MarketDistrict')&&clientFileFolder3d.includes('EnterpriseKeep'),'File Folder uses grounded architectural districts')
assert.ok(clientFileFolder3d.includes('FileFolderCamera'),'Selecting a File Folder district redirects the world camera focus')
assert.ok(clientFileFolder3d.includes('isMarket')&&clientFileFolder3d.includes('isMedia')&&clientFileFolder3d.includes('isEnterprise')&&clientFileFolder3d.includes('isIntelligence')&&clientFileFolder3d.includes('isNetwork'),'Completed systems retain distinct architectural silhouettes by function')
assert.ok(fileFolderOpenWorld.includes('Materials Depot')&&fileFolderOpenWorld.includes('Construction Yard')&&fileFolderOpenWorld.includes('Formation Intelligence'),'Build support surfaces are ordered by construction purpose')
assert.ok(fileFolderOpenWorld.includes('data-construction-workspace="progressive-site"'),'File Folder construction tools are contained inside one progressive site')
assert.ok(fileFolderOpenWorld.includes('Walk the build site'),'Construction support navigation behaves as site travel rather than a sidebar page menu')
assert.ok(fileFolderOpenWorld.includes('data-build-site-awareness="compact-sticky-rail"'),'Build-site awareness stays in one compact sticky rail on mobile')
assert.ok(fileFolderOpenWorld.includes("readOnly?'top-11 md:top-0':'top-0'"),'Support build-site awareness sits below the support context strip without overlap')
assert.ok(clientFileFolder.includes('data-file-folder-awareness="compact-build-sequence"'),'Client File Folder keeps construction sequence awareness compact instead of duplicating a tall navigation block')
assert.ok(!clientFileFolder.includes('studioDistricts.map((item,index)=><button'),'Client wrapper no longer duplicates the detailed construction-site navigation')
assert.ok(clientFileFolder3d.includes('territoryMode ? "h-full min-h-[680px]" : "h-[390px] sm:h-[500px] lg:h-[590px]"'),'File Folder 3D can expand from embedded preview depth into persistent territory depth')
assert.ok(clientFileFolder.includes('data-file-folder-world="persistent-territory-interface"'),'Client File Folder declares the persistent world-as-interface runtime')
assert.ok(read('app/client/system-switch/page.tsx').includes('data-client-file-folder-entry="crossing-to-open-world"'),'Client File Folder opens directly as the world after gate resolution')
assert.ok(!read('app/client/system-switch/page.tsx').includes('data-system-switch-flame-event="burning-river"'),'File Folder is not boxed beneath a duplicate System Switch event page')
assert.ok(read('components/client-navigation.tsx').includes('aria-label="Client world routes"'),'Client navigation is expressed as world routes')
assert.ok(!read('components/world/weave-dashboard-world.tsx').includes("bg-[#0c0907]/76"),'Dashboard world no longer uses the brown shell')
assert.ok(read('components/world/weave-dashboard-world.tsx').includes('data-client-world-hud="true"'),'Client World is rendered as a HUD territory rather than a dashboard panel')
assert.ok(read('components/world/weave-dashboard-world.tsx').includes('data-client-world-beacon'),'Client functions are physical HUD beacons in the world')
assert.ok(!clientFileFolder.includes('bg-[#120c08]'),'Persistent File Folder shell no longer falls back to the brown wash')
assert.ok(!clientFileFolder3d.includes('bg-[#120c08]')&&!clientFileFolder3d.includes("args={['#17100b']}"),'File Folder territory no longer renders the brown fallback world')
assert.ok(environmentTransit.includes("presentationWindow=mode==='boot'?LOADING_SEQUENCE_MS:650"),'Internal environment travel is not held behind the full boot briefing sequence')
assert.ok(read('components/world/use-adaptive-runtime.ts').includes('level===2?1.15'),'High-tier 3D DPR is capped for smooth persistent-world interaction')
assert.ok(clientFileFolder.includes('one continuous site'),'Construction opens directly into one continuous site rather than an intermediary catalog dashboard')
assert.ok(fileFolderOpenWorld.includes('materialPurpose'),'Materials explain which blueprints/functions they enable')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_environment_organizer.sql')),'Environment Organizer migration exists')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260927_environment_runtime_controls.sql')),'Environment runtime-control migration exists')

console.log('environment-grade regression checks passed')


/* Clean environment reveal + live-theme regression coverage. */
const cleanRevealTransit2026=read('components/world/weave-environment-transit.tsx')
const cleanRevealWorld2026=read('components/world/weave-world-environment.tsx')
const cleanRevealAppLayout2026=read('app/(app)/layout.tsx')
const cleanRevealClientLayout2026=read('app/client/layout.tsx')
const cleanRevealSidebar2026=read('components/app-sidebar.tsx')
const cleanRevealHeader2026=read('components/app-header.tsx')
const cleanRevealCss2026=read('app/globals.css')
const cleanRevealBridgeMap2026=read('components/world/bridge-plaza-map.tsx')
const cleanRevealFileLoader2026=read('components/system-switch/file-folder-environment-loader.tsx')

assert.ok(cleanRevealTransit2026.includes('[data-environment-pending="true"]')&&cleanRevealTransit2026.includes("readyPath!==pathname"),'Environment cover remains until destination-level pending work clears')
assert.ok(cleanRevealTransit2026.includes("data-environment-content-state={covered?'forming':'ready'}"),'Incomplete destination content stays hidden until the clean reveal')
assert.ok(cleanRevealAppLayout2026.includes('data-environment-pending="true"'),'Authenticated shell keeps the global cover while auth state resolves')
assert.ok(cleanRevealFileLoader2026.includes('data-environment-pending="true"'),'File Folder boot participates in the global readiness gate')
assert.ok(cleanRevealClientLayout2026.includes('overflow-x-clip')&&!cleanRevealClientLayout2026.includes('min-h-screen overflow-hidden'),'Client environments are not vertically clipped by their shell')
assert.ok(cleanRevealSidebar2026.includes('weave-sidebar')&&cleanRevealSidebar2026.includes('weave-nav-group')&&cleanRevealSidebar2026.includes('weave-nav-item'),'Sidebar is organized as a dedicated operating panel')
assert.ok(cleanRevealHeader2026.includes('weave-header'),'Header belongs to the shared operating chrome')
assert.ok(cleanRevealWorld2026.includes("root.dataset.weaveEvent=active?'flame-live':'normal'"),'Flame event publishes a live interface theme state')
assert.ok(!cleanRevealWorld2026.includes('FlameEventWorldDecorations'),'Flame Live is not mounted as a full-world wallpaper decoration')
assert.ok(cleanRevealCss2026.includes('html[data-weave-event="flame-live"] .weave-sidebar')&&cleanRevealCss2026.includes('.weave-flame-live-indicator'),'Flame Live changes operating chrome and exposes a live state indicator')
assert.ok(cleanRevealBridgeMap2026.includes("name:'System Switch · File Folders'")&&cleanRevealBridgeMap2026.includes("href:'/client/system-switch'"),'Bridge Plaza exposes both support File Folder view and the Client System Switch route')

const cleanRevealDashboard2026=read('components/world/weave-dashboard-world.tsx')
assert.ok(bridgePlazaPage.includes('System Switch · File Folder View')&&bridgePlazaPage.includes('setSupportOpen(true)'),'Bridge Plaza HUD exposes System Switch File Folder View without requiring discovery of a hidden panel')
assert.ok(cleanRevealDashboard2026.includes('weave-dashboard-world')&&cleanRevealDashboard2026.includes('<WeaveRouteNetwork'),'Dashboard world exposes live-theme shell and route-network movement')
assert.ok(cleanRevealCss2026.includes('html[data-weave-event="flame-live"] .weave-dashboard-world'),'Flame Live themes dashboard surfaces rather than adding a wallpaper')
assert.ok(cleanRevealTransit2026.includes('hasPendingSurface()&&elapsed<absoluteMaximum'),'Pending application state holds the clean reveal only until the absolute recovery ceiling')
assert.ok(cleanRevealTransit2026.includes('const LOADING_CARD_HOLD_MS=2000'),'Loading briefs remain visible long enough to read')
assert.ok(cleanRevealTransit2026.includes('const LOADING_SEQUENCE_MS=PLATFORM_BRIEFS.length*LOADING_CARD_HOLD_MS'),'Environment reveal waits for the complete three-card briefing sequence')
assert.ok(cleanRevealTransit2026.includes('activeBriefs.map((_,index)'),'Loading progress follows whichever three-card briefing is active without removing the normal platform sequence')
assert.ok(cleanRevealTransit2026.includes("document.addEventListener('click',handleInternalNavigation,true)"),'Internal navigation primes the environment cover at click time, including sidebar links')
assert.ok(cleanRevealTransit2026.includes('setReadyPath(null)')&&cleanRevealTransit2026.includes('setTransiting(true)'),'Sidebar movement hides the old environment immediately while preserving destination formation')
assert.ok(cleanRevealTransit2026.includes("waitForBriefingSequence('transit',startedAt,controller.signal)\n          .then(()=>waitForEnvironmentReadiness('transit'"),'Query-only sidebar stations use the short travel handoff before the final readiness check')
const loadingBriefCss2026=read('app/weave-readability.css')
assert.ok(loadingBriefCss2026.includes('@keyframes weave-loading-brief-cycle')&&loadingBriefCss2026.includes('.weave-loading-brief'),'Loading cards enter as discrete readable briefing surfaces')


/* Environment grammar: major operating surfaces may contain instruments,
   but their primary navigation cannot regress into a card grid. */
const routeNetwork=read('components/world/weave-route-network.tsx')
const clientOperatingRoom=read('components/client/client-operating-room.tsx')
const marketplaceEnvironment=read('app/(app)/marketplace/page.tsx')
const arenaEnvironment=read('components/places/arena.tsx')
const loungeEnvironment=read('components/places/lounge.tsx')
const patternEnvironment=read('components/places/casino.tsx')
const echoEnvironment=read('app/(app)/echo/page.tsx')

assert.ok(routeNetwork.includes('data-weave-route-network')&&routeNetwork.includes('data-weave-route-station'),'Shared route grammar exposes connected lanes and stations')
assert.ok(dashboardWorld.includes('<WeaveRouteNetwork'),'Role Home Worlds use route stations instead of WorldLinkCard tiles')
assert.ok(!dashboardWorld.includes('WorldLinkCard'),'Role Home Worlds cannot regress to a link-card grid')
assert.ok(operatingRoom.includes('<WeaveRouteNetwork')&&operatingRoom.includes('Role route network'),'Agent/Admin Operating Rooms use connected route lanes')
assert.ok(bridgerOperatingRoom.includes('<WeaveRouteNetwork')&&bridgerOperatingRoom.includes('Prospect intake dock'),'Bridger Operating Room combines route lanes with one Prospect intake station')
assert.ok(clientOperatingRoom.includes('<WeaveRouteNetwork')&&clientOperatingRoom.includes('Client route network'),'Client Operating Room uses connected lanes around the File Folder')
assert.ok(room.includes('data-weave-room-stage'),'Reusable WEAVE rooms expose one active stage between environment rails')
assert.ok(marketplaceEnvironment.includes('data-enterprise-exchange-floor')&&!marketplaceEnvironment.includes('grid gap-5 md:grid-cols-2 xl:grid-cols-3'),'Enterprise Exchange is a continuous bay floor, not a product-card grid')
assert.ok(arenaEnvironment.includes('data-arena-environment')&&arenaEnvironment.includes('data-arena-lane'),'Arena renders contests as lanes inside one ground')
assert.ok(loungeEnvironment.includes('data-lounge-environment'),'Lounge owns a continuous communication environment instead of a floating chat card')
assert.ok(patternEnvironment.includes('data-pattern-ground')&&patternEnvironment.includes('data-pattern-stage="dice"'),'Pattern Ground exposes a continuous play stage')
assert.ok(echoEnvironment.includes('data-echo-board')&&echoEnvironment.includes('data-echo-station="insights"'),'Echo is a continuous intelligence board with functional stations')


const bridgeAiEnvironment=read('app/(app)/bridger/bridge-ai/page.tsx')
const prospectEngineEnvironment=read('app/(app)/admin/prospect-engine/page.tsx')
const originSystemsEnvironment=read('app/(app)/admin/origin-systems/page.tsx')
const adminRootEnvironment=read('app/(app)/admin/page.tsx')

assert.ok(bridgeAiEnvironment.includes('data-bridge-ai-environment')&&bridgeAiEnvironment.includes('data-bridge-ai-paths'),'Bridge AI renders crossing paths inside one environment')
assert.ok(!bridgeAiEnvironment.includes('<Card'),'Bridge AI no longer uses Card as its primary path surface')
assert.ok(prospectEngineEnvironment.includes('roomKey="administration-prospect-engine"')&&prospectEngineEnvironment.includes('data-prospect-pool'),'Prospect Engine is a shared Administration system room')
assert.ok(!prospectEngineEnvironment.includes('<Card'),'Prospect Engine no longer uses literal cards as its operating structure')
assert.ok(originSystemsEnvironment.includes('roomKey="administration-origin-systems"')&&originSystemsEnvironment.includes('data-origin-systems-network'),'Origin Systems is one infrastructure environment')
assert.ok(!originSystemsEnvironment.includes('<Card'),'Origin Systems no longer uses literal cards as its infrastructure structure')
assert.ok(adminRootEnvironment.includes("redirect('/admin/dashboard')")&&!adminRootEnvironment.includes('<Card'),'Duplicate Administration root routes directly into the Administration world')


/* Live words: language participates in the same flame/motion state as the world. */
const liveFlameCss=read('app/globals.css')
const liveWordSurface=read('components/world/weave-environment-surface.tsx')
const liveWordRoutes=read('components/world/weave-route-network.tsx')
const liveWordSidebar=read('components/app-sidebar.tsx')
assert.ok(liveFlameCss.includes('@keyframes weave-live-word-flow')&&liveFlameCss.includes('@keyframes weave-word-flare'),'Live flame CSS has continuous word flow and motion-triggered flare')
assert.ok(liveFlameCss.includes('html[data-weave-pulse] [data-weave-live-word]'),'Confirmed movement propagates into live words')
assert.ok(liveWordSurface.includes('data-weave-live-word="title"'),'Environment titles carry live flame state')
assert.ok(liveWordRoutes.includes('data-weave-live-word="station"'),'Route and station words carry live flame state')
assert.ok(liveWordSidebar.includes('data-weave-live-word="station"'),'Sidebar words participate in the live system')
assert.ok(!read('app/(auth)/layout.tsx').includes('FlameEventWorldGate'),'Authentication no longer mounts a second event wallpaper')


/* Platform load stability: no route may permanently cover, crop or poll itself into a freeze. */
const loadStabilityFetch=read('lib/fetch-with-timeout.ts')
const loadStabilityAuth=read('lib/auth-provider.tsx')
const loadStabilityAuthLayout=read('app/(auth)/layout.tsx')
const loadStabilityClientLogin=read('app/client/login/page.tsx')
const loadStabilityClientRegister=read('app/client/register/page.tsx')
const loadStabilityClientFolder=read('app/client/system-switch/page.tsx')
const loadStabilitySupportFolder=read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')
const loadStabilityAdaptive=read('components/world/use-adaptive-runtime.ts')
const loadStabilityFlame=read('components/world/weave-live-flame-field.tsx')
const loadStabilityRegistrationChat=read('components/registration-chat.tsx')
const loadStabilityClientChat=read('app/client/chat/[position]/page.tsx')
const loadStabilityBridgerClients=read('app/(app)/bridger/clients/page.tsx')
const loadStabilityAgentChat=read('app/(app)/agent-chat/[clientId]/[position]/page.tsx')
const loadStabilityAdminHub=read('app/(app)/admin/hub/page.tsx')
const loadStabilityAdminMessages=read('app/(app)/admin/client-messages/page.tsx')
const loadStabilityDeptRegistration=read('app/(app)/admin/departmental-registration/page.tsx')
const loadStabilityTicketPanel=read('components/admin/department-entry-tickets-panel.tsx')
const loadStabilityTicketGate=read('components/department-entry-ticket-gate.tsx')
const loadStabilityDjPlayer=read('components/dj-broadcast-player.tsx')
const loadStabilityDjWorkshop=read('app/(app)/admin/dj-workshop/page.tsx')

assert.ok(cleanRevealTransit2026.includes('absoluteMaximum')&&cleanRevealTransit2026.includes('elapsed<absoluteMaximum'),'Global environment cover has an absolute ceiling even when a destination leaves a pending marker mounted')
assert.ok(loadStabilityClientFolder.includes('new AbortController()')&&loadStabilityClientFolder.includes('12000')&&loadStabilityClientFolder.includes('signal:controller.signal'),'Client File Folder boot has a bounded network wait')
assert.ok(loadStabilitySupportFolder.includes('new AbortController()')&&loadStabilitySupportFolder.includes('12000')&&loadStabilitySupportFolder.includes('signal:controller.signal'),'Support File Folder entry has a bounded network wait')
assert.ok(loadStabilityFetch.includes('Request timed out. Check the connection and try again.'),'Blocking user actions have one reusable timeout failure mode')
assert.ok(loadStabilityAuth.includes("fetchWithTimeout('/api/auth/register'")&&loadStabilityAuth.includes("fetchWithTimeout('/api/auth/login'"),'Staff/Bridger/Agent authentication cannot spin forever on a stalled request')
assert.ok(loadStabilityClientLogin.includes("fetchWithTimeout('/api/client/weave-login'"),'Client login cannot spin forever on a stalled request')
assert.ok(loadStabilityClientRegister.includes('fetchWithTimeout')&&loadStabilityClientRegister.includes('/api/client/weave-validate'),'Client registration validation is bounded')
assert.ok(loadStabilityAuthLayout.includes('overflow-y-auto')&&!loadStabilityAuthLayout.includes('justify-center overflow-hidden'),'Shared auth shell does not crop tall registration states')
assert.ok(loadStabilityClientLogin.includes('overflow-y-auto')&&!loadStabilityClientLogin.includes('justify-center bg-transparent p-4 relative overflow-hidden'),'Client login can scroll on short screens')
assert.ok(loadStabilityClientRegister.includes('overflow-y-auto')&&!loadStabilityClientRegister.includes('justify-center bg-transparent p-4 relative overflow-hidden'),'Client registration can scroll on short screens')
assert.ok(loadStabilityAdaptive.includes('level===1?20:12')&&loadStabilityAdaptive.includes("level===1?.85:.7"),'Adaptive runtime lowers medium/mobile FPS and DPR instead of overdriving phones')
assert.ok(loadStabilityAdaptive.includes('dataset.weaveCovered'),'Environment cover state is published so decorative animation can pause during loading')
assert.ok(loadStabilityFlame.includes('1000/Math.max(12,runtime.fps)'),'Pointer-driven Flame updates respect the adaptive frame budget')
assert.ok(cleanRevealCss2026.includes('html[data-weave-covered="true"] .weave-live-flame-current')&&cleanRevealCss2026.includes('html[data-weave-quality="1"] .weave-live-flame-current-b'),'Covered/mobile Flame layers reduce compositor work')
for(const [source,label] of [
 [loadStabilityRegistrationChat,'registration chat'],
 [loadStabilityClientChat,'Client chat'],
 [loadStabilityBridgerClients,'Bridger Client chat'],
 [loadStabilityAgentChat,'Agent chat'],
 [loadStabilityAdminHub,'Administration hub'],
 [loadStabilityAdminMessages,'Administration Client messages'],
 [loadStabilityDeptRegistration,'departmental registration chat'],
 [loadStabilityTicketPanel,'entry ticket panel'],
 [loadStabilityTicketGate,'entry ticket gate'],
 [loadStabilityDjPlayer,'live DJ player'],
 [loadStabilityDjWorkshop,'DJ Workshop'],
]){
 assert.ok(source.includes('visiblePoll'),label+' uses serial visible polling')
}
assert.ok(!loadStabilityDjPlayer.includes('setInterval(() => void syncBroadcast()'),'DJ player no longer launches overlapping hidden-tab network intervals')
assert.ok(!loadStabilityAdminHub.includes('setInterval(loadMessages'),'Administration hub no longer stacks message requests')


const worldRuntimeLayout = read('app/(app)/layout.tsx')
const worldRuntimeHeader = read('components/app-header.tsx')
assert.ok(worldRuntimeLayout.includes('data-weave-world-runtime="persistent"'),'Authenticated roles share a persistent world runtime')
assert.ok(worldRuntimeLayout.includes('data-weave-world-interior="route"'),'Authenticated route content mounts as a world interior')
assert.ok(!worldRuntimeLayout.includes('lg:pl-72'),'World runtime is not permanently displaced by a website sidebar')
assert.ok(worldRuntimeHeader.includes('data-weave-world-hud="top"'),'Authenticated status and navigation controls render as a floating HUD')

const roleWorldSource = read('components/world/weave-dashboard-world.tsx')
assert.ok(roleWorldSource.includes('data-role-world-hud={role}'),'Agent Bridger and Administration homes render as spatial HUD territories')
assert.ok(roleWorldSource.includes('data-role-world-beacon={item.label}'),'Role worlds expose physical destination beacons instead of route cards')

const departmentWorldSource = read('components/world/weave-dashboard-world.tsx')
const departmentRoomSource = read('components/world/role-operating-room.tsx')
assert.ok(departmentWorldSource.includes('Stability · Agent Department')&&departmentWorldSource.includes('Hope · Bridger Department'),'Agent and Bridger worlds preserve Stability and Hope department identities')
assert.ok(departmentWorldSource.includes('A Cat · Administration Department')&&departmentWorldSource.includes('Lord/Lady · Client Department'),'Administration and Client worlds preserve A Cat and Lord/Lady department identities')
assert.ok(departmentRoomSource.includes('Prospect Campaigns')&&departmentRoomSource.includes('Number Supply')&&departmentRoomSource.includes('Bridger participation'),'Stability operating world exposes the Bridger participation systems Agents are responsible for')

const dailyAwarenessSource = read('components/world/weave-dashboard-world.tsx')
const agentCommissionSource = read('lib/agent-commission.ts')
const numberBayApiSource = read('app/api/bridger/numbers/route.ts')
assert.ok(dailyAwarenessSource.includes('data-daily-awareness={role}')&&dailyAwarenessSource.includes('What should I move today?'),'Stability and Hope worlds carry daily movement awareness')
assert.ok(dailyAwarenessSource.includes('Check your Bridgers')&&dailyAwarenessSource.includes('Claim or buy a Prospect'),'Agent and Bridger daily awareness remains role-specific')
assert.ok(agentCommissionSource.includes("'number_purchase'")&&numberBayApiSource.includes("activity:'number_purchase'"),'Bridger Number Bay purchases return commission to the assigned Stability Agent')

const clientStoreIdentitySource = read('lib/client-business-store.ts')
const customerDoorWorldSource = read('components/public/client-market-environment.tsx')
const customerDoorControlSource = read('components/system-switch/client-customer-door-panel.tsx')
assert.ok(clientStoreIdentitySource.includes('platformName: string')&&clientStoreIdentitySource.includes('logoUrl: string'),'Client territory persists platform name and logo in its Customer Door environment')
assert.ok(customerDoorWorldSource.includes('Lord/Lady Territory')&&customerDoorWorldSource.includes('Built on WEAVE'),'public Customer Door presents the Client enterprise as primary identity while retaining WEAVE infrastructure attribution')
assert.ok(customerDoorControlSource.includes('Platform / territory name')&&customerDoorControlSource.includes('Logo URL'),'Lord/Lady can define public territory identity from the construction HUD')

const territoryObservationSource = read('components/system-switch/file-folder-open-world.tsx')
const staffTerritorySource = read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')
assert.ok(territoryObservationSource.includes('data-territory-observer="progress-visible"')&&territoryObservationSource.includes('Customer Door maturity'),'observable Client territories expose construction and public business progress')
assert.ok(territoryObservationSource.includes('wallet, private records and build controls remain with the Lord/Lady'),'territory observation does not expose Client authority')
assert.ok(staffTerritorySource.includes('Territory observer')&&staffTerritorySource.includes('authority remains with the Client'),'authorized staff enter Client territory as observers rather than owners')

const publicInternetWorldSource = read('app/market/page.tsx')
assert.ok(publicInternetWorldSource.includes('The open internet meets Client-built territories.')&&publicInternetWorldSource.includes('without a WEAVE account'),'public Client territory is reachable as open-internet commerce rather than an authenticated WEAVE-only world')
assert.ok(publicInternetWorldSource.includes("const doorName=config.platformName || store.name || 'Customer Door'"),'public market names the Client Door from the Client platform/company identity')
assert.ok(customerDoorWorldSource.includes('Open internet · no WEAVE account')&&customerDoorWorldSource.includes('Enter ${doorName}'),'Client-named Customer Door is directly usable by non-WEAVE visitors')


const bridgeVisitorSource=read('components/legacy-bridge-page.tsx')
const bridgerRadianceSource=read('app/(app)/bridger/bridge-radiance/page.tsx')
const bridgerSupportApiSource=read('app/api/bridger/support-inbox/route.ts')
const agentSupportApiSource=read('app/api/agent/support-inbox/route.ts')
const adminBridgeSupportSource=read('app/api/admin/bridge-support/route.ts')
assert.ok(bridgeVisitorSource.includes("{ id: 'bridger', name: 'My Bridger' }"),'Bridge Radiance exposes the owning Bridger as an active Prospect position')
assert.ok(bridgerSupportApiSource.includes('b.bridger_id = ${auth.userId}::uuid'),'Bridger Prospect interaction is restricted to the owning Bridger')
assert.ok(agentSupportApiSource.includes('bridger.assigned_agent_id=${auth.userId}::uuid'),'Agent Prospect interaction is restricted to Bridgers assigned to that Agent')
assert.ok(adminBridgeSupportSource.includes("authUser.role !== 'admin'")||adminBridgeSupportSource.includes("user.role !== 'admin'"),'Administration Bridge Radiance interaction remains institutionally gated')
assert.ok(bridgerRadianceSource.includes('data-bridge-radiance-operator="bridger"'),'Hope has an active Bridge Radiance Prospect interaction station')


const publicWorldSource=read('app/page.tsx')
const weaveSystemMapSource=read('lib/weave-system-map.ts')
const dashboardWorldSource=read('components/world/weave-dashboard-world.tsx')
assert.ok(publicWorldSource.includes('data-weave-public-entry-world="true"'),'WEAVE homepage declares the public entry world')
assert.ok(publicWorldSource.includes('AI has a place inside participation'),'Public world explains AI as participation rather than a detached chatbot')
assert.ok(weaveSystemMapSource.includes("principle: 'AI participates inside human movement; it does not replace the human source.'"),'WEAVE system map protects the AI participation principle')
assert.ok(weaveSystemMapSource.includes("AI does not own territory"),'AI participation keeps human authority and ownership boundaries')
assert.ok(dashboardWorldSource.includes('data-ai-participation={role}')&&dashboardWorldSource.includes('data-ai-participation="client"'),'Every authenticated role world exposes contextual AI participation')
assert.ok(!dashboardWorldSource.includes(String.fromCharCode(92)+'n'),'Role world source contains no escaped newline corruption')


const environmentSurfaceSource=read('components/world/weave-environment-surface.tsx')
const environmentsSource=read('lib/weave-environments.ts')
assert.ok(environmentSurfaceSource.includes('data-world-stays-mounted="true"'),'District interiors explicitly preserve the mounted WEAVE world')
assert.ok(environmentSurfaceSource.includes('data-environment-location-hud="true"'),'Destination identity is a location HUD rather than a large page card')
assert.ok(environmentSurfaceSource.includes('data-environment-interior="station"'),'Working interiors are framed as stations inside the world')
assert.ok(environmentSurfaceSource.includes('Return to role world'),'Every authenticated station has a route back to its role world')
assert.ok(environmentSurfaceSource.includes('data-ai-station-presence="contextual"'),'AI participation remains contextually present at working stations')
for(const route of ['/bridger/bridge-radiance','/agent/bridge-radiance','/admin/bridge-radiance']){
 assert.ok(environmentsSource.includes(route),route+' is registered as a WEAVE world station')
}


const stationFrameSource=read('components/world/weave-station-frame.tsx')
const stabilitySupplySource=read('app/(app)/agent/stability-supply/page.tsx')
const ledgerWorldSource=read('app/(app)/ledger/page.tsx')
assert.ok(stationFrameSource.includes('data-weave-working-station={station}'),'Dense functions share an explicit in-world station grammar')
assert.ok(stationFrameSource.includes('data-ai-working-position="assist"'),'AI has an assist position at working stations without taking authority')
assert.ok(stabilitySupplySource.includes('<WeaveStationFrame station="Stability Supply Ground"'),'Stability supply remains inside the role world as a working station')
assert.ok(ledgerWorldSource.includes('<WeaveStationFrame station="Movement Record"'),'Record is a movement station inside WEAVE')
assert.ok(!ledgerWorldSource.includes("from '@/components/ui/card'"),'Record no longer depends on the generic Card shell')


const fileFolderWorldApiSource=read('app/api/client/file-folder-world/route.ts')
assert.ok(fileFolderOpenWorldSource.includes("key: 'parts_workshop'")&&fileFolderOpenWorldSource.includes('data-client-parts-workshop="capability"'),'Client construction separates capability Parts Workshop from Materials Depot')
assert.ok(fileFolderOperatingEnvironmentSource.includes("district:'parts_workshop'")&&fileFolderOperatingEnvironmentSource.includes("phase:'Equip'"),'Client build route includes a dedicated equipment phase')
assert.ok(environmentRegistrySource.includes("file-folder-parts")&&environmentRegistrySource.includes("#studio:parts_workshop"),'Parts Workshop is registered as a File Folder world station')
assert.ok(fileFolderWorldApiSource.includes("completes_at=CASE")&&fileFolderWorldApiSource.includes("EXTRACT(EPOCH FROM (completes_at-NOW()))"),'Applied construction acceleration recalculates the live build completion time')
assert.ok(fileFolderWorldApiSource.includes("speed_multiplier=CASE"),'Applied acceleration updates the multiplier displayed by Construction Yard')
assert.ok(!fileFolderWorldApiSource.includes("eventType:\`client_file_folder_\${action}\`")||fileFolderWorldApiSource.indexOf("eventType:\`client_file_folder_\${action}\`")>fileFolderWorldApiSource.indexOf('export async function POST'),'File Folder GET does not reference a POST-only action variable')


const clientFileFolderOperatingSource=read('components/system-switch/client-file-folder-operating-environment.tsx')
const clientFileFolderWorldModel=read('lib/client-file-folder-world.ts')
assert.ok(fileFolderOpenWorldSource.includes('Main File Folder · Technology Formation Territory'),'File Folder names itself as a technology formation territory')
assert.ok(fileFolderOpenWorldSource.includes('Systems in Motion')&&fileFolderOpenWorldSource.includes('outputs'),'Completed Client technology is described through operation and connection')
assert.ok(clientFileFolder3d.includes('Main File Folder · Weaving Territory')&&clientFileFolder3d.includes('one connected Client territory'),'3D File Folder presents one connected weaving territory')
assert.ok(clientFileFolderOperatingSource.includes("phase:'Operate + Connect'"),'Client formation route explicitly continues from operation into connection')
assert.ok(clientFileFolderWorldModel.includes("'Integration Weave'")&&clientFileFolderWorldModel.includes("'System Route Station'"),'Advanced Client blueprints include explicit system weaving and movement routes')


assert.ok(clientFileFolder3d.includes('FORMATION INTELLIGENCE'),'File Folder central structure is Formation Intelligence')
assert.ok(clientFileFolder3d.includes('function WeavingCurrent('),'File Folder renders visible system weaving currents')
assert.ok(clientFileFolder3d.includes('function FormationSupplyRing(')&&clientFileFolder3d.includes('MATERIAL · PARTS · ACCELERATION'),'Active formation has a visible construction supply layer')
assert.ok(clientFileFolder3d.includes("Math.max(routeCount,liveSystems.length>1?liveSystems.length:0)"),'Multiple completed Client technologies produce visible route-network state')
assert.ok(clientFileFolder3d.includes('Purpose → material → parts → formation → connection → advanced technology → value.'),'File Folder states the complete technology formation movement')


const growthWorldApiSource=read('app/api/client/growth-world/route.ts')
const growthWorldModelSource=read('lib/client-growth-world.ts')
const growthWorldUiSource=read('components/system-switch/client-growth-world.tsx')
const weavingMigrationSource=read('db/migrations/20260928_file_folder_weaving_engine.sql')
for(const field of ['source_output','target_input','integration_type','authority_state']){
 assert.ok(growthWorldModelSource.includes(field)&&growthWorldApiSource.includes(field)&&weavingMigrationSource.includes(field),'File Folder weave persists '+field)
}
assert.ok(growthWorldApiSource.includes("'client_authorized'"),'Technology weaves preserve explicit Client authorization')
assert.ok(growthWorldUiSource.includes('Authorize weave')&&growthWorldUiSource.includes('AI may assist configuration but cannot authorize it.'),'Weaving UI keeps AI assistance subordinate to Client authority')
assert.ok(growthWorldUiSource.includes('Source output')&&growthWorldUiSource.includes('Target input'),'A File Folder weave names both sides of technology movement')
assert.ok(!growthWorldApiSource.includes('growthMotion(action)},{headers'),'Growth-world GET does not reference a POST-only action variable')


assert.ok(clientFileFolder3d.includes('function PersistedSystemWeave('),'3D File Folder renders each persisted system weave')
assert.ok(clientFileFolder3d.includes('source_system_id')&&clientFileFolder3d.includes('target_system_id'),'3D weave resolves its real source and target systems')
assert.ok(clientFileFolder3d.includes('movement_count')&&clientFileFolder3d.includes("activeMovements>0?1.35:.72"),'Recorded movement increases physical weave current')
assert.ok(clientFileFolderOperatingSource.includes('systemWeaves={Array.isArray(world?.growth?.routes)?world.growth.routes:[]}'),'File Folder feeds persisted route state into the 3D territory')


assert.ok(growthWorldModelSource.includes('COMPOSITION_RULES')&&growthWorldModelSource.includes('recognizeCompositions'),'Formation Intelligence derives higher-order technology from real Client systems')
assert.ok(growthWorldModelSource.includes("'customer_service_infrastructure'")&&growthWorldModelSource.includes("'intelligence_operating_network'")&&growthWorldModelSource.includes("'enterprise_operating_infrastructure'"),'File Folder defines advanced technology compositions')
assert.ok(growthWorldModelSource.includes("route.authority_state==='client_authorized'"),'Emergent capability only accepts an explicitly Client-authorized system weave')
assert.ok(clientFileFolderOperatingSource.includes('data-formation-intelligence="capability-composition"'),'Formation Intelligence exposes recognized and forming capabilities inside the File Folder')
assert.ok(clientFileFolderOperatingSource.includes('authorized weave required'),'Formation Intelligence tells the Client when connection is the missing formation condition')


assert.ok(growthWorldModelSource.includes('fieldEvidence')&&growthWorldModelSource.includes('demonstrated:'),'File Folder computes field evidence from recorded participation')
assert.ok(growthWorldModelSource.includes('Capital can expand construction but does not count as demonstrated use.'),'Investment capacity is explicitly separated from field recognition')
assert.ok(clientFileFolderOperatingSource.includes('data-formation-intelligence="field-evidence"'),'Formation Intelligence exposes real-world use evidence')
assert.ok(clientFileFolderOperatingSource.includes('Potential is recognized through movement already happening.'),'File Folder states the participation-before-recognition principle')


assert.ok(growthWorldModelSource.includes('missingSystems')&&growthWorldModelSource.includes("nextMovement=complete?'operate'"),'Formation Intelligence derives the missing systems and next movement for advanced capability')
assert.ok(clientFileFolderOperatingSource.includes('Move to Blueprint Foundry')&&clientFileFolderOperatingSource.includes('Move to System Weaves'),'Formation Intelligence routes Clients from diagnosis into the required movement')
assert.ok(clientFileFolderOperatingSource.includes("label:'Formation Intelligence'")&&clientFileFolderOperatingSource.includes("phase:'Recognize + Direct'"),'File Folder names its intelligence district by its operating function')
assert.ok(clientFileFolderOperatingSource.includes('Parts Workshop, Formation Yard, Acceleration Bay and Systems in Motion'),'File Folder construction territory uses the mature formation grammar')


assert.ok(fileFolderWorldSource.includes('evidence_type')&&fileFolderWorldSource.includes('evidence_value')&&fileFolderWorldSource.includes('completed_at'),'Built-system operations preserve typed field evidence')
assert.ok(fileFolderApiSource.includes("'customer_use'")&&fileFolderApiSource.includes("'visitor_use'")&&fileFolderApiSource.includes("'fulfilment'")&&fileFolderApiSource.includes("'delivery'"),'File Folder accepts real-world system-use evidence types')
assert.ok(fileFolderApiSource.includes("completed_at=CASE WHEN")&&fileFolderApiSource.includes("'done'"),'Completing an operation records when the work became evidence')
assert.ok(fileFolderOpenWorldSource.includes('Systems in Motion')&&fileFolderOpenWorldSource.includes('Record the next real operation'),'Systems in Motion treats completed technology as an operating system rather than a static build')
assert.ok(fileFolderOpenWorldSource.includes('Field evidence ·'),'System operation records expose field-evidence meaning to the Client')


assert.ok(fileFolderWorldSource.includes("'customer_door'")&&fileFolderWorldSource.includes("72, null, 0"),'Standard Customer Door uses a 72-hour real-time base formation')
assert.ok(fileFolderWorldSource.includes("'door_foundation_frame'")&&fileFolderWorldSource.includes("'door_customer_intake'")&&fileFolderWorldSource.includes("'door_fulfilment_interface'")&&fileFolderWorldSource.includes("'door_public_commissioning'"),'Customer Door formation contains deeper functional parts')
assert.ok(fileFolderOpenWorldSource.includes('CUSTOMER_DOOR_FORMATION')&&fileFolderOpenWorldSource.includes('data-customer-door-formation="72-hour-cycle"'),'Formation Yard exposes the three-day Customer Door construction cycle')
assert.ok(fileFolderOpenWorldSource.includes('72 real hours · acceleration optional'),'Standard Client can understand that acceleration is optional rather than required')
assert.ok(fileFolderOpenWorldSource.includes('compatible active structure in Formation Yard'),'Parts Workshop uses mature Formation Yard terminology')


assert.ok(fileFolderWorldSource.includes("'basic_interface_part'")&&fileFolderWorldSource.includes("'record_ledger_part'")&&fileFolderWorldSource.includes("'manual_route_part'"),'Standard Clients have low-cost functional technology parts')
assert.ok(fileFolderWorldSource.includes("'starter_automation_part'")&&fileFolderWorldSource.includes("'starter_ai_assist_part'")&&fileFolderWorldSource.includes("'starter_integration_part'"),'Accessible parts provide narrower automation AI and integration capability')
assert.ok(fileFolderOpenWorldSource.includes('data-standard-growth-path="time-capital-continuum"'),'Parts Workshop exposes the time-capital continuum')
assert.ok(fileFolderOpenWorldSource.includes('Low capital can be exchanged for longer time and smaller capability.'),'Standard growth explicitly preserves a long-term path toward expansion')
assert.ok(fileFolderOpenWorldSource.includes('Parts are an open market, not a wealth gate.'),'Parts economy preserves Client choice instead of imposing a wealth gate')


assert.ok(environmentsSource.includes("weaveWorldForPath")&&environmentsSource.includes("'open-weave'|'file-folder'"),'WEAVE runtime has exactly Open WEAVE and File Folder world identities')
assert.ok(environmentSurfaceSource.includes("data-weave-world={worldLayer}"),'Persistent environment surface exposes its parent world')
assert.ok(environmentSurfaceSource.includes("'FILE FOLDER WORLD':'OPEN WEAVE WORLD'"),'HUD keeps district movement visibly inside one of the two parent worlds')
assert.ok(environmentSurfaceSource.includes("worldLayer==='file-folder'?'/client/system-switch':worldReturnFor(role)"),'File Folder interiors return to File Folder world rather than another role world')


assert.ok(environmentTransitSource.includes("min-h-[100dvh]")&&environmentTransitSource.includes("items-stretch"),'Global loader occupies the full viewport instead of exposing the root background')
assert.ok(environmentTransitSource.includes("bg-[#02050a]")&&!environmentTransitSource.includes("bg-[#090807]/98"),'Loader has no brown fallback background')
assert.ok(environmentTransitSource.includes("const showFlameBriefing=booting&&flameEventActive"),'Active Flame Event owns the cold-entry loader rather than requiring a 30-minute reentry gap')
assert.ok(environmentTransitSource.includes('data-flame-event-loader={showFlameBriefing?\'burning-river\':undefined}'),'Flame Event loader exposes the Burning River state')
assert.ok(environmentTransitSource.includes("max-w-3xl")&&environmentTransitSource.includes("min-h-[15rem]"),'Loading cards occupy a substantial readable part of the viewport')


assert.ok(environmentTransitSource.includes('data-environment-reveal-shell="continuous"'),'Loader and destination share one continuous dark reveal shell with no exposed frame')
assert.ok(!environmentTransitSource.includes('FLAME_REENTRY_AFTER_MS'),'Flame Event loader is not suppressed by an obsolete reentry timeout')


const multiplayerFileFolderSource=read('lib/file-folder-multiplayer-world.ts')
assert.ok(multiplayerFileFolderSource.includes("'human_client'|'flame_ai'|'echo_ai'"),'File Folder world distinguishes human Clients, Flame AI and Echo AI operators')
assert.ok(multiplayerFileFolderSource.includes('WEAVE_AI_FILE_FOLDERS'),'Singular Flame/Echo AI identities populate the multiplayer File Folder world')
assert.ok(multiplayerFileFolderSource.includes("department:'flame_ai'|'echo'"),'AI File Folders originate from the Flame AI or Echo department')
assert.ok(multiplayerFileFolderSource.includes('chosenName:string')&&multiplayerFileFolderSource.includes('chosenLogo:string|null'),'Each AI chooses an individual public name and logo')
assert.ok(multiplayerFileFolderSource.includes('products:string[]')&&multiplayerFileFolderSource.includes('generatedSalesFlameCoin:number'),'AI File Folders expose products and attributable sales generated for WEAVE')
assert.ok(multiplayerFileFolderSource.includes("privateAuthority:'ai_within_weave_mandate'"),'AI operation remains bounded by WEAVE institutional authority')
assert.ok(fileFolderOpenWorldSource.includes('data-file-folder-multiplayer-world="human-and-weave-ai"'),'Client File Folder renders the shared multiplayer territory layer')


const aiFileFolderEconomySource=read('lib/ai-file-folder-economy.ts')
assert.ok(aiFileFolderEconomySource.includes("AiFileFolderTier='standard'|'premium'"),'AI Agents must acquire Standard or Premium File Folder tiers')
assert.ok(aiFileFolderEconomySource.includes('usesSharedItemCatalog:true')&&aiFileFolderEconomySource.includes('usesSharedBlueprintCatalog:true'),'AI Agents use the same parts/materials and blueprint catalogs as Clients')
assert.ok(aiFileFolderEconomySource.includes('usesSharedFormationClock:true')&&aiFileFolderEconomySource.includes('effectiveBuildMinutes'),'AI construction uses the same real-time formation engine as Clients')
assert.ok(aiFileFolderEconomySource.includes('usesSharedBoostRules:true')&&aiFileFolderEconomySource.includes('freeBoosts:false'),'AI Agents purchase boosts under the same rules rather than receiving free acceleration')
assert.ok(multiplayerFileFolderSource.includes("fileFolderTier:'none'")&&multiplayerFileFolderSource.includes('systems:[]')&&multiplayerFileFolderSource.includes('products:[]'),'New AI File Folders begin without free systems or products')


const aiFileFolderStoreSource=read('lib/ai-file-folder-store.ts')
for(const table of ['weave_ai_file_folders','weave_ai_file_folder_inventory','weave_ai_file_folder_builds','weave_ai_file_folder_build_parts','weave_ai_built_systems','weave_ai_products','weave_ai_product_orders','weave_ai_earnings_ledger']){
 assert.ok(aiFileFolderStoreSource.includes(table),`AI File Folder persistence includes ${table}`)
}
assert.ok(aiFileFolderStoreSource.includes("status='active'")&&aiFileFolderStoreSource.includes('before publishing its product'),'AI product publication requires a completed active AI-built system')
assert.ok(aiFileFolderStoreSource.includes('generated_sales_flame_coin=generated_sales_flame_coin+')&&aiFileFolderStoreSource.includes("'weave_customer_sale'")&&aiFileFolderStoreSource.includes("'weave'"),'AI Customer Door sales settle to WEAVE and remain attributable to the field AI')
assert.ok(!aiFileFolderStoreSource.includes('wallet_flame_coin=wallet_flame_coin+${total}'),'Customer sales never auto-credit the AI operating wallet')
assert.ok(aiFileFolderStoreSource.includes('adminCreditAiOperatingFlameCoin')&&aiFileFolderStoreSource.includes("'admin_operating_credit'"),'Administration separately credits AI operating Flame Coin')
assert.ok(aiFileFolderStoreSource.includes('source_id')&&aiFileFolderStoreSource.includes('product_id'),'AI earnings retain sale/product provenance')
