const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const root=path.resolve(__dirname,'..')
const read=p=>fs.readFileSync(path.join(root,p),'utf8')

const room=read('components/world/weave-system-room.tsx')
assert.ok(room.includes('data-weave-room={roomKey}'),'Reusable WEAVE room exposes room identity')
assert.ok(room.includes('usePresenceCamera'),'Reusable WEAVE room stays attached to Presence Camera')
assert.ok(room.includes('System pulse'),'Reusable WEAVE room exposes live system pulse')

const converted=[
 ['app/client/loops/page.tsx','client-loop-field'],
 ['app/(app)/admin/loop-workshop/page.tsx','administration-loop-workshop'],
 ['app/(app)/bridger/subscription/page.tsx','bridger-continuance'],
 ['app/(app)/bridger/numbers/page.tsx','bridger-number-bay'],
 ['app/(app)/admin/bridger-numbers/page.tsx','administration-number-engine'],
]
for(const [file,key] of converted){
 const source=read(file)
 assert.ok(source.includes('WeaveSystemRoom'),file+' uses the shared environment room')
 assert.ok(source.includes('roomKey="'+key+'"'),file+' preserves its spatial room identity')
 assert.ok(!source.includes('min-h-screen bg-slate-950'),file+' does not recreate an opaque standalone page')
}

const bridgerNumbers=read('app/(app)/bridger/numbers/page.tsx')
const bridgerNumbersApi=read('app/api/bridger/numbers/route.ts')
const adminNumbers=read('app/(app)/admin/bridger-numbers/page.tsx')
assert.ok(!bridgerNumbers.includes('n.acquisition_cost'),'Bridger Number Bay never renders provider acquisition cost')
assert.ok(!bridgerNumbersApi.includes('acquisition_cost'),'Bridger Number API never returns provider acquisition cost')
assert.ok(adminNumbers.includes('n.acquisition_cost'),'Administration retains internal acquisition cost')
assert.ok(adminNumbers.includes('price_flame_coin'),'Administration retains Bridger Flame Coin price')

const continuance=read('app/(app)/bridger/subscription/page.tsx')
assert.ok(!continuance.includes('bg-white shadow-sm'),'Bridger Continuance no longer uses generic white web cards')
assert.ok(!continuance.includes('text-gray-'),'Bridger Continuance uses WEAVE environment language')

const camera=read('lib/presence-camera.ts')
for(const key of ['client-loop-field','number-bay','bridger-continuance','loop-workshop','number-control','infrastructure','visual-systems','environment-organizer','dj-workshop','client-deposit-control','enterprise-dream-authority']){
 assert.ok(camera.includes("key:'"+key+"'"),key+' has a distinct Presence Camera scene')
}

const css=read('app/globals.css')
assert.ok(css.includes('Environment-first enforcement.'),'Authenticated legacy roots are absorbed into the persistent world')

const rootLayout=read('app/layout.tsx')
assert.equal((rootLayout.match(/<PresenceCameraProvider>/g)||[]).length,1,'Exactly one Presence Camera provider owns the application')
assert.equal((rootLayout.match(/<WeaveWorldEnvironment\s*\/>/g)||[]).length,1,'Exactly one persistent WEAVE world owns the application')
assert.ok(rootLayout.includes('<WeaveEnvironmentTransit>'),'Global environment transit remains active')
assert.ok(rootLayout.includes('<InteractionMotionLayer />'),'Interaction output remains globally visible')
assert.ok(rootLayout.includes('<WeavePresenceAmbience />'),'Persistent WEAVE world mounts one adaptive presence ambience engine')
const flameReentryTransit=read('components/world/weave-environment-transit.tsx')
assert.ok(flameReentryTransit.includes("FLAME_REENTRY_AFTER_MS=30*60*1000"),'Flame Event re-entry briefing waits for meaningful absence')
assert.ok(flameReentryTransit.includes("FLAME_REENTRY_LAST_ACTIVE_KEY"),'Flame Event re-entry state persists last app presence')
assert.ok(flameReentryTransit.includes("resolveEventStatus(FLAME_EVENT"),'Flame Event re-entry briefing follows the October 1 event lifecycle')
assert.ok(flameReentryTransit.includes("const showFlameBriefing=booting&&flameReentry"),'Flame Event briefing is boot-only and cannot replace ordinary route transit')
assert.ok(flameReentryTransit.includes("const briefs=showFlameBriefing?FLAME_EVENT_BRIEFS:PLATFORM_BRIEFS"),'Normal WEAVE loading briefs remain intact outside eligible Flame Event re-entry')
assert.ok(flameReentryTransit.includes("Burning River")&&flameReentryTransit.includes("The River that Burns"),'Flame Event re-entry identifies the Burning River explicitly')


const liveFlameField=read('components/world/weave-live-flame-field.tsx')
const bridgePlazaPage=read('app/(app)/weave/page.tsx')
assert.ok(liveFlameField.includes('data-weave-live-flame'),'Persistent WEAVE world exposes a live flame field')
assert.ok(liveFlameField.includes("window.addEventListener('pointermove'")&&liveFlameField.includes("window.addEventListener('weave:system-motion'"),'Persistent flame reacts to human presence and confirmed system movement')
assert.ok(!fs.existsSync(path.join(root,'components/world/weave-normal-world-backdrop.tsx')),'Static architectural wallpaper has been removed from the codebase')
assert.ok(!fs.existsSync(path.join(root,'components/world/weave-world-backdrop.tsx')),'Legacy sky/world wallpaper has been removed from the codebase')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-theme="continuous-moving-system"'),'Bridge Plaza page is one continuous moving system rather than a card layout')
assert.ok(!bridgePlazaPage.includes('grid gap-3 sm:grid-cols-2 xl:grid-cols-4'),'Bridge Plaza removes the four architecture-card row')
assert.ok(bridgePlazaPage.includes('data-bridge-plaza-station="client-support"'),'Client support is an entered Plaza station instead of a permanent side card')
assert.ok(bridgePlazaPage.includes('Bridge Plaza · System Switch')&&bridgePlazaPage.includes('File Folder View'),'Bridge Plaza exposes System Switch File Folder View as an entered station')

const artifact=read('components/events/flame-event-artifact.tsx')
const bridgePlaza=read('components/world/bridge-plaza-map.tsx')
const weaveHero=read('components/weave-hero-3d.tsx')
const bridgeRadiance=read('components/bridge/bridge-radiance-world.tsx')
const clientEvent=read('components/events/client-flame-event-dashboard.tsx')
assert.ok(artifact.includes('FlameEventArtifact3D'),'Canonical Flame Event 4D artifact exists')
assert.ok(artifact.includes('FlameEventArtifactMark'),'Canonical Flame Event interface mark exists')
assert.ok(!bridgePlaza.includes('FlameEventArtifact3D'),'Bridge Plaza no longer uses the abstract Flame Event artifact as its physical world')
assert.ok(bridgePlaza.includes('FlameFountain'),'Bridge Plaza has a central living flame fountain')
assert.ok(bridgePlaza.includes('TerraceWing')&&bridgePlaza.includes('DistrictEntrance'),'Bridge Plaza uses architectural terraces and real district entrances')
assert.ok(bridgePlaza.includes('StoneFloor')&&bridgePlaza.includes('FlameFountain'),'Bridge Plaza uses grounded physical architecture around the central movement point')
assert.ok(!bridgePlaza.includes('HumanFigure'),'Bridge Plaza removes literal human proxy figures')
assert.ok(bridgePlaza.includes('GrandHall')&&bridgePlaza.includes('Arcade'),'Bridge Plaza replaces figures with monumental hall architecture and deep arcades')
assert.ok(bridgePlaza.includes('SystemRoute'),'Bridge Plaza movement is carried by live routes between the central WEAVE point and districts')
assert.ok(bridgePlaza.includes('WorldCamera')&&bridgePlaza.includes('onArrival'),'Entering a district physically moves the camera before navigation')
assert.ok(bridgePlaza.includes('WorldInscriptions'),'School, Board, Subject and Topics exist as spatial world information rather than rendered cards')
assert.ok(bridgePlaza.includes('data-bridge-plaza-system="continuous-moving-world"'),'Bridge Plaza declares one continuous world runtime')
assert.ok(bridgePlaza.includes('WEAVE HALL')&&bridgePlaza.includes('ORDER · CONTINUITY · MOVEMENT'),'Bridge Plaza has a central order/continuity hall identity')
assert.ok(bridgePlaza.includes('const bell=useRef'),'Bridge Plaza hall visibly contains a bell structure')
assert.ok(!bridgePlaza.includes('torusKnotGeometry'),'Bridge Plaza no longer uses the old gold/green woven ring object')
assert.ok(!bridgePlaza.includes("color='#e8b93f'") && !bridgePlaza.includes('color="#e8b93f"'),'Bridge Plaza no longer hard-codes the old gold ring identity')
assert.ok(!bridgePlaza.includes("color='#14b8a6'") && !bridgePlaza.includes('color="#14b8a6"'),'Bridge Plaza no longer hard-codes the old teal ring identity')
assert.ok(weaveHero.includes('FlameEventArtifact3D'),'Homepage 3D hero uses the same canonical artifact')
assert.ok(!weaveHero.includes('torusKnotGeometry'),'Homepage no longer revives the old woven ring motif')
assert.ok(bridgeRadiance.includes('FlameEventArtifact3D'),'Bridge Radiance portals use the same artifact language')
assert.ok(!bridgeRadiance.includes('torusGeometry'),'Bridge Radiance no longer uses generic torus portals')
assert.ok(!fs.existsSync(path.join(root,'components/events/flame-event-world-decorations.tsx')),'Legacy global Flame Event decoration wallpaper is removed')
assert.ok(clientEvent.includes('FlameEventArtifactMark'),'Client Flame Event center may still use the canonical artifact locally')

const presenceAmbience=read('components/world/weave-presence-ambience.tsx')
const djBroadcastPlayer=read('components/dj-broadcast-player.tsx')
assert.ok(presenceAmbience.includes('makeHallImpulse'),'Presence ambience builds hall reverb procedurally')
assert.ok(presenceAmbience.includes('playFootstep'),'Presence ambience carries distant stone footsteps')
assert.ok(presenceAmbience.includes('playBell'),'Presence ambience carries occasional hall bell resonance')
assert.ok(presenceAmbience.includes('playDistantMovement'),'Presence ambience carries subtle unseen movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:dj-audio-state'"),'Presence ambience listens to the live WEAVE DJ mix')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:personal-dj'"),'Presence ambience also ducks beneath personal File Folder DJ playback')
assert.ok(presenceAmbience.includes('ambience.musicGain')&&presenceAmbience.includes('ambience.voiceGain'),'Presence ambience reads live Administration-controlled music and voice ducking')
assert.ok(djBroadcastPlayer.includes("new CustomEvent('weave:dj-audio-state'"),'Global DJ publishes playback state for environmental mixing')
assert.ok(djBroadcastPlayer.includes('data-weave-dj-broadcast="true"'),'Global DJ audio element is explicitly identified as the WEAVE broadcast source')

const visualProfile=read('lib/weave-visual-profile.ts')
const visualRuntime=read('lib/weave-visual-runtime.ts')
const visualAdminApi=read('app/api/admin/visual-systems/route.ts')
const visualPublicApi=read('app/api/visual-runtime/route.ts')
const visualWorkshop=read('app/(app)/admin/visual-systems/page.tsx')
const visualRuntimeHook=read('components/world/use-visual-runtime.ts')
const interactionMotionField=read('components/world/interaction-motion-field.tsx')
const interactionMotionLayer=read('components/world/interaction-motion-layer.tsx')
const interactionMotionBus=read('lib/weave-interaction-motion.ts')
const fileFolderWorldApi=read('app/api/client/file-folder-world/route.ts')
const growthWorldApi=read('app/api/client/growth-world/route.ts')
const dailyProspectClaimUi=read('components/bridger/daily-prospect-claim.tsx')
const flameEventWorld=read('components/world/weave-live-flame-field.tsx')
const adminWorkshop=read('app/(app)/admin/workshop/page.tsx')
const appSidebar=read('components/app-sidebar.tsx')
const operatingRoom=read('components/world/role-operating-room.tsx')
const dashboardWorld=read('components/world/weave-dashboard-world.tsx')
assert.ok(visualProfile.includes('FLAME_ARTIFACT_SURFACES'),'Visual runtime has an explicit surface registry')
assert.ok(visualProfile.includes("red:'#fb7185'") && visualProfile.includes("sky:'#7dd3fc'"),'Published visual profile preserves Flame Event red/sky signature')
assert.ok(visualProfile.includes("'bridge-plaza-core'")&&visualProfile.includes("'client-event'"),'Visual runtime covers Bridge Plaza through Client Flame Event')
assert.ok(visualRuntime.includes('weave_visual_profiles')&&visualRuntime.includes('weave_visual_profile_history'),'Visual runtime persists draft, published state and history')
assert.ok(visualRuntime.includes('rollbackVisualProfile'),'Visual runtime supports published rollback')
assert.ok(visualAdminApi.includes("user.role!=='admin'"),'Only Administration can publish visual runtime changes')
assert.ok(visualAdminApi.includes("action==='publish'")&&visualAdminApi.includes("action==='rollback'"),'Administration API exposes publish and rollback actions')
assert.ok(visualPublicApi.includes('getPublishedVisualProfile'),'Public runtime exposes published visual state only')
assert.ok(visualPublicApi.includes('DEFAULT_FLAME_ARTIFACT_CONFIG'),'Public runtime has a compiled safe fallback')
assert.ok(visualRuntimeHook.includes("createRuntimeResource('/api/visual-runtime'"),'Shared Visual Runtime reads the published runtime profile')
assert.ok(read('lib/runtime-resource.ts').includes('15000'),'Mounted visual systems refresh published runtime state without deployment')
assert.ok(artifact.includes('useVisualRuntime'),'Canonical Flame artifact consumes the shared live Visual Runtime')
assert.ok(artifact.includes('surface?:FlameArtifactSurface'),'Artifact applies per-surface runtime placement controls')
assert.ok(visualWorkshop.includes('Visual Systems Workshop')&&visualWorkshop.includes('Publish Live'),'Administration has a live Visual Systems Workshop')
assert.ok(visualWorkshop.includes("run('rollback'"),'Visual Systems Workshop can roll back a published revision')
assert.ok(visualWorkshop.includes('configOverride={draft}'),'Visual Systems Workshop previews draft state before publishing')
assert.ok(visualProfile.includes("type VisualWorldMode='normal'|'flame-event'|'quiet-river'|'ceremony'|'night-operations'"),'Visual Runtime defines explicit world-motion operating modes')
assert.ok(visualProfile.includes('flameIntensity')&&visualProfile.includes('riverIntensity')&&visualProfile.includes('routeCurrent')&&visualProfile.includes('emergence'),'Visual Runtime persists Flame, River, route-current and system-emergence controls')
assert.ok(interactionMotionField.includes('drawFlames')&&interactionMotionField.includes('drawRiver')&&interactionMotionField.includes('drawEmbers'),'Interaction Motion Field procedurally renders flame, river and ember motion')
assert.ok(interactionMotionField.includes('requestAnimationFrame'),'Interaction Motion Field is a live animation runtime rather than a static background')
assert.ok(interactionMotionField.includes('budget.reducedMotion'),'Interaction Motion Field respects reduced-motion accessibility')
assert.ok(flameEventWorld.includes('<InteractionMotionField')&&flameEventWorld.includes('forceEvent={flameLive}'),'One live field increases Flame intensity from event state without swapping wallpapers')
assert.ok(!read('components/world/weave-world-environment.tsx').includes('FlameEventWorldDecorations'),'Persistent world never mounts a Flame Event wallpaper layer')
assert.ok(liveFlameField.includes("data-weaveLiveSystem='flame'")||liveFlameField.includes("dataset.weaveLiveSystem='flame'"),'Live flame runtime publishes a global system state for interface effects')
assert.ok(bridgePlaza.includes('useVisualRuntime')&&bridgePlaza.includes('routeCurrent'),'Bridge Plaza movement current is driven by the published Visual Runtime')
assert.ok(visualWorkshop.includes('World motion authority'),'Administration Visual Systems Workshop exposes world-motion authority')
assert.ok(visualWorkshop.includes('Flame Field')&&visualWorkshop.includes('Burning River')&&visualWorkshop.includes('Live system emergence'),'Administration can tune Flame, River and live-system emergence without source edits')
assert.ok(visualWorkshop.includes("new Event('weave:visual-runtime-published')"),'Publishing or rollback refreshes mounted Visual Runtime consumers immediately')
assert.ok(interactionMotionBus.includes("type WeaveMotionKind=")&&interactionMotionBus.includes("'emergence'")&&interactionMotionBus.includes("'value'")&&interactionMotionBus.includes("'interruption'"),'WEAVE has one semantic motion vocabulary for real interaction')
assert.ok(interactionMotionLayer.includes("window.addEventListener('weave:presence-output'")&&interactionMotionLayer.includes("window.addEventListener('weave:system-motion'"),'Global motion layer joins human intent with confirmed system movement')
assert.ok(interactionMotionLayer.includes("pulse.kind==='ignition'")&&interactionMotionLayer.includes("pulse.kind==='river'")&&interactionMotionLayer.includes("pulse.kind==='route'")&&interactionMotionLayer.includes("pulse.kind==='emergence'")&&interactionMotionLayer.includes("pulse.kind==='value'"),'Global motion layer renders distinct physical responses instead of one generic ripple')
assert.ok(interactionMotionField.includes("window.addEventListener('weave:system-motion'"),'Underlying Flame/River field surges from confirmed system movement')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:system-motion'"),'Procedural ambience responds to confirmed system movement through the DJ-aware mixer')
assert.ok(fileFolderWorldApi.includes('motion:fileFolderMotion(action)'),'File Folder API returns motion meaning with confirmed world state')
assert.ok(growthWorldApi.includes('motion:growthMotion(action)'),'Growth World API returns motion meaning with confirmed growth state')
assert.ok(dailyProspectClaimUi.includes("kind:'route'")&&dailyProspectClaimUi.includes('Daily Prospect entered Bridger outreach'),'Daily Prospect claim moves visibly into Bridger outreach')
assert.ok(bridgerNumbers.includes("kind:'value'")&&bridgerNumbers.includes("kind:'confirmation'"),'Number Bay purchase, order, delivery and verification have confirmed motion responses')
assert.ok(bridgePlaza.includes("kind:'route'")&&bridgePlaza.includes("kind:'arrival'"),'Bridge Plaza physical travel emits route and arrival movement')
assert.ok(visualWorkshop.includes('data-admin-motion-tests="true"')&&visualWorkshop.includes('Admin motion test'),'Administration can test motion responses without creating business records')
for(const source of [adminWorkshop,appSidebar,operatingRoom,dashboardWorld]){
 assert.ok(source.includes('/admin/visual-systems'),'Administration navigation exposes Visual Systems Workshop')
}
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_visual_systems_workshop.sql')),'Visual Systems Workshop migration exists')

const environmentRegistry=read('lib/weave-environment-registry.ts')
const environmentRuntime=read('lib/weave-environment-organizer.ts')
const environmentAdminApi=read('app/api/admin/environment-organizer/route.ts')
const environmentPublicApi=read('app/api/environment-organizer/route.ts')
const environmentProvider=read('components/world/environment-organizer-provider.tsx')
const environmentWorkshop=read('app/(app)/admin/environment-organizer/page.tsx')
const environmentRuntimeProfile=read('lib/weave-environment-runtime-profile.ts')
const environmentRuntimeControls=read('components/admin/environment-runtime-controls.tsx')
const environmentRuntimeHook=read('components/world/use-environment-runtime-config.ts')
const environmentTransit=read('components/world/weave-environment-transit.tsx')
const bridgerOperatingRoom=read('components/bridger/bridger-operating-environment.tsx')
const clientFileFolder=read('components/system-switch/client-file-folder-operating-environment.tsx')
const clientFileFolder3d=read('components/system-switch/client-file-folder-3d.tsx')
assert.ok(clientFileFolder3d.includes('visualRuntime.world.emergence')&&clientFileFolder3d.includes('visualRuntime.world.routeCurrent'),'Client File Folder construction and route movement consume live emergence/current controls')
const fileFolderOpenWorld=read('components/system-switch/file-folder-open-world.tsx')
assert.ok(fileFolderOpenWorld.includes('body.motion||fileFolderMotion'),'Client File Folder consumes server-confirmed motion meaning')
assert.ok(fileFolderOpenWorld.includes("status==='complete'")&&fileFolderOpenWorld.includes('commissioned and live'),'Automatic build completion produces emergence without requiring a click')
const clientNavigation=read('components/client-navigation.tsx')
const clientLayout=read('app/client/layout.tsx')
const supportFileFolderPage=read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')

assert.ok(!operatingRoom.toLowerCase().includes('position map'),'Agent/Admin Operating Room removes Position Map card')
assert.ok(!bridgerOperatingRoom.toLowerCase().includes('position map'),'Bridger Operating Room removes Position Map card')
assert.ok(environmentRegistry.includes('WEAVE_ENVIRONMENT_REGISTRY'),'Environment Organizer has an explicit page/card registry')
assert.ok(environmentRegistry.includes("kind:'card'")&&environmentRegistry.includes("kind:'page'"),'Environment Organizer registers both cards and pages')
assert.ok(environmentRegistry.includes("protected:true"),'Environment Organizer protects critical control surfaces')
assert.ok(environmentRegistry.includes("key:'admin-integrity-engine'")&&environmentRegistry.includes("route:'/admin/dev-workshop'"),'Integrity Engine is a protected Administration environment surface')
assert.ok(environmentRuntime.includes('weave_environment_surfaces'),'Environment organization persists in the database')
assert.ok(environmentRuntime.includes('weave_environment_runtime_profiles'),'Environment loading and ambience profile persists in the database')
assert.ok(environmentRuntime.includes('setEnvironmentRuntimeConfig')&&environmentRuntime.includes('restoreEnvironmentRuntimeDefaults'),'Administration can publish or restore environment runtime settings')
assert.ok(environmentRuntimeProfile.includes('bootMinMs:3600')&&environmentRuntimeProfile.includes('transitMinMs:900'),'Environment defaults deliberately allow more formation time')
assert.ok(environmentRuntimeProfile.includes('waitForFonts:true')&&environmentRuntimeProfile.includes('waitForImages:true'),'Environment defaults wait for typography and media')
assert.ok(environmentAdminApi.includes("action==='set_runtime'")&&environmentAdminApi.includes("action==='restore_runtime_defaults'"),'Environment Organizer API exposes live runtime publication')
assert.ok(environmentPublicApi.includes('DEFAULT_ENVIRONMENT_RUNTIME_CONFIG'),'Public environment runtime has a safe compiled fallback')
assert.ok(environmentRuntimeHook.includes("'weave-environment-refresh'")&&read('lib/runtime-resource.ts').includes('window.addEventListener(event,published)'),'Published runtime settings can refresh mounted environments immediately')
assert.ok(environmentTransit.includes('MutationObserver')&&environmentTransit.includes('document.fonts.ready')&&environmentTransit.includes('document.images'),'Environment cover waits for component, font and media readiness')
assert.ok(environmentRuntimeControls.includes('Loading + Presence Workshop'),'Administration Environment Organizer exposes loading and presence controls')
assert.ok(environmentRuntimeControls.includes("publish('set_runtime')"),'Administration can publish environment runtime changes live')
assert.ok(environmentRuntimeControls.includes("weave:ambience-preview"),'Administration can preview presence sounds before publishing')
assert.ok(presenceAmbience.includes("window.addEventListener('weave:ambience-preview'"),'Presence engine receives Administration sound previews')
assert.ok(environmentRuntime.includes('setEnvironmentSurfaceVisibility')&&environmentRuntime.includes('setEnvironmentSurfaceOrder'),'Environment runtime supports withdrawal/restoration and ordering')
assert.ok(environmentAdminApi.includes("user.role!=='admin'"),'Only Administration can mutate environment organization')
assert.ok(environmentAdminApi.includes("action==='set_visibility'")&&environmentAdminApi.includes("action==='set_order'"),'Environment Organizer API exposes visibility and ordering actions')
assert.ok(environmentPublicApi.includes('getEnvironmentOrganizerState'),'Running clients can read the active environment organization')
assert.ok(environmentProvider.includes('EnvironmentPageGuard'),'Withdrawn registered pages are guarded at runtime')
assert.ok(environmentProvider.includes('useEnvironmentRuntimeConfig')&&environmentRuntimeHook.includes('weave-environment-refresh'),'Organizer changes can refresh mounted navigation without deployment')
assert.ok(environmentWorkshop.includes('Environment Organizer')&&environmentWorkshop.includes('Remove'),'Administration has the page/card organizer workshop')
assert.ok(appSidebar.includes('/admin/environment-organizer'),'Administration sidebar exposes Environment Organizer')
assert.ok(adminWorkshop.includes('/admin/environment-organizer'),'Admin Workshop exposes Environment Organizer')
assert.ok(adminWorkshop.includes('WEAVE Integrity Engine')&&adminWorkshop.includes('/admin/dev-workshop?tab=terminal'),'Admin Workshop exposes the live Integrity Engine repair surface')
assert.ok(operatingRoom.includes('/admin/environment-organizer'),'Administration Operating Room exposes Environment Organizer')
assert.ok(dashboardWorld.includes('/admin/environment-organizer'),'Administration World exposes Environment Organizer')
assert.ok(clientNavigation.includes('useEnvironmentOrganizer'),'Client navigation honors the organizer registry')
assert.ok(clientLayout.includes('EnvironmentOrganizerProvider'),'Client world mounts the organizer runtime')
assert.ok(supportFileFolderPage.includes('Support · Read only'),'Support File Folder preserves role awareness in a compact context strip')
assert.ok(supportFileFolderPage.includes('md:static'),'Support context is sticky only where mobile needs it')
assert.ok(!supportFileFolderPage.includes("['Recognize'"),'Support File Folder removes the duplicated five-stage card strip')
assert.ok(clientFileFolder.includes('Command Citadel'),'Main File Folder has one strategic command center')
assert.ok(clientFileFolder.includes('BUILD_LADDER'),'Main File Folder exposes an ordered construction lifecycle')
assert.ok(clientFileFolder.includes('Blueprint')&&clientFileFolder.includes('Foundation')&&clientFileFolder.includes('Commissioning')&&clientFileFolder.includes('Live operation'),'File Folder construction communicates real build stages')
assert.ok(clientFileFolder.includes('visibleSurfaceKeys'),'File Folder 3D receives runtime-organized districts')
assert.ok(clientFileFolder3d.includes('ConstructionSite')&&clientFileFolder3d.includes('ScaffoldEnvelope')&&clientFileFolder3d.includes('Crane'),'File Folder world renders real progressive construction sites with scaffolding and cranes')
assert.ok(clientFileFolder3d.includes('PavedRoad')&&clientFileFolder3d.includes('WaterChannel'),'File Folder territory physically connects districts with roads and water infrastructure')
assert.ok(clientFileFolder3d.includes('Persistent construction territory'),'File Folder is framed as a progressive construction territory rather than a floating dashboard')
assert.ok(!clientFileFolder3d.includes('<Stars'),'File Folder removes the old star-field treatment')
assert.ok(!clientFileFolder3d.includes('<gridHelper'),'File Folder removes the old sci-fi grid floor')
assert.ok(clientFileFolder3d.includes('CommandHall')&&clientFileFolder3d.includes('MarketDistrict')&&clientFileFolder3d.includes('EnterpriseKeep'),'File Folder uses grounded architectural districts')
assert.ok(clientFileFolder3d.includes('FileFolderCamera'),'Selecting a File Folder district redirects the world camera focus')
assert.ok(clientFileFolder3d.includes('isMarket')&&clientFileFolder3d.includes('isMedia')&&clientFileFolder3d.includes('isEnterprise')&&clientFileFolder3d.includes('isIntelligence')&&clientFileFolder3d.includes('isNetwork'),'Completed systems retain distinct architectural silhouettes by function')
assert.ok(fileFolderOpenWorld.includes('Materials Depot')&&fileFolderOpenWorld.includes('Construction Yard')&&fileFolderOpenWorld.includes('Build Intelligence'),'Build support surfaces are ordered by construction purpose')
assert.ok(fileFolderOpenWorld.includes('data-construction-workspace="progressive-site"'),'File Folder construction tools are contained inside one progressive site')
assert.ok(fileFolderOpenWorld.includes('Walk the build site'),'Construction support navigation behaves as site travel rather than a sidebar page menu')
assert.ok(fileFolderOpenWorld.includes('data-build-site-awareness="compact-sticky-rail"'),'Build-site awareness stays in one compact sticky rail on mobile')
assert.ok(fileFolderOpenWorld.includes("readOnly?'top-11 md:top-0':'top-0'"),'Support build-site awareness sits below the support context strip without overlap')
assert.ok(clientFileFolder.includes('data-file-folder-awareness="compact-build-sequence"'),'Client File Folder keeps construction sequence awareness compact instead of duplicating a tall navigation block')
assert.ok(!clientFileFolder.includes('studioDistricts.map((item,index)=><button'),'Client wrapper no longer duplicates the detailed construction-site navigation')
assert.ok(clientFileFolder3d.includes('territoryMode ? "h-full min-h-[680px]" : "h-[390px] sm:h-[500px] lg:h-[590px]"'),'File Folder 3D can expand from embedded preview depth into persistent territory depth')
assert.ok(clientFileFolder.includes('data-file-folder-world="persistent-territory-interface"'),'Client File Folder declares the persistent world-as-interface runtime')
assert.ok(read('app/client/system-switch/page.tsx').includes('data-client-file-folder-entry="crossing-to-open-world"'),'Client File Folder opens directly as the world after gate resolution')
assert.ok(!read('app/client/system-switch/page.tsx').includes('data-system-switch-flame-event="burning-river"'),'File Folder is not boxed beneath a duplicate System Switch event page')
assert.ok(read('components/client-navigation.tsx').includes('aria-label="Client world routes"'),'Client navigation is expressed as world routes')
assert.ok(!read('components/world/weave-dashboard-world.tsx').includes("bg-[#0c0907]/76"),'Dashboard world no longer uses the brown shell')
assert.ok(read('components/world/weave-dashboard-world.tsx').includes('data-client-world-hud="true"'),'Client World is rendered as a HUD territory rather than a dashboard panel')
assert.ok(read('components/world/weave-dashboard-world.tsx').includes('data-client-world-beacon'),'Client functions are physical HUD beacons in the world')
assert.ok(!clientFileFolder.includes('bg-[#120c08]'),'Persistent File Folder shell no longer falls back to the brown wash')
assert.ok(!clientFileFolder3d.includes('bg-[#120c08]')&&!clientFileFolder3d.includes("args={['#17100b']}"),'File Folder territory no longer renders the brown fallback world')
assert.ok(environmentTransit.includes("presentationWindow=mode==='boot'?LOADING_SEQUENCE_MS:650"),'Internal environment travel is not held behind the full boot briefing sequence')
assert.ok(read('components/world/use-adaptive-runtime.ts').includes('level===2?1.15'),'High-tier 3D DPR is capped for smooth persistent-world interaction')
assert.ok(clientFileFolder.includes('one continuous site'),'Construction opens directly into one continuous site rather than an intermediary catalog dashboard')
assert.ok(fileFolderOpenWorld.includes('materialPurpose'),'Materials explain which blueprints/functions they enable')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260926_environment_organizer.sql')),'Environment Organizer migration exists')
assert.ok(fs.existsSync(path.join(root,'db/migrations/20260927_environment_runtime_controls.sql')),'Environment runtime-control migration exists')

console.log('environment-grade regression checks passed')


/* Clean environment reveal + live-theme regression coverage. */
const cleanRevealTransit2026=read('components/world/weave-environment-transit.tsx')
const cleanRevealWorld2026=read('components/world/weave-world-environment.tsx')
const cleanRevealAppLayout2026=read('app/(app)/layout.tsx')
const cleanRevealClientLayout2026=read('app/client/layout.tsx')
const cleanRevealSidebar2026=read('components/app-sidebar.tsx')
const cleanRevealHeader2026=read('components/app-header.tsx')
const cleanRevealCss2026=read('app/globals.css')
const cleanRevealBridgeMap2026=read('components/world/bridge-plaza-map.tsx')
const cleanRevealFileLoader2026=read('components/system-switch/file-folder-environment-loader.tsx')

assert.ok(cleanRevealTransit2026.includes('[data-environment-pending="true"]')&&cleanRevealTransit2026.includes("readyPath!==pathname"),'Environment cover remains until destination-level pending work clears')
assert.ok(cleanRevealTransit2026.includes("data-environment-content-state={covered?'forming':'ready'}"),'Incomplete destination content stays hidden until the clean reveal')
assert.ok(cleanRevealAppLayout2026.includes('data-environment-pending="true"'),'Authenticated shell keeps the global cover while auth state resolves')
assert.ok(cleanRevealFileLoader2026.includes('data-environment-pending="true"'),'File Folder boot participates in the global readiness gate')
assert.ok(cleanRevealClientLayout2026.includes('overflow-x-clip')&&!cleanRevealClientLayout2026.includes('min-h-screen overflow-hidden'),'Client environments are not vertically clipped by their shell')
assert.ok(cleanRevealSidebar2026.includes('weave-sidebar')&&cleanRevealSidebar2026.includes('weave-nav-group')&&cleanRevealSidebar2026.includes('weave-nav-item'),'Sidebar is organized as a dedicated operating panel')
assert.ok(cleanRevealHeader2026.includes('weave-header'),'Header belongs to the shared operating chrome')
assert.ok(cleanRevealWorld2026.includes("root.dataset.weaveEvent=active?'flame-live':'normal'"),'Flame event publishes a live interface theme state')
assert.ok(!cleanRevealWorld2026.includes('FlameEventWorldDecorations'),'Flame Live is not mounted as a full-world wallpaper decoration')
assert.ok(cleanRevealCss2026.includes('html[data-weave-event="flame-live"] .weave-sidebar')&&cleanRevealCss2026.includes('.weave-flame-live-indicator'),'Flame Live changes operating chrome and exposes a live state indicator')
assert.ok(cleanRevealBridgeMap2026.includes("name:'System Switch · File Folders'")&&cleanRevealBridgeMap2026.includes("href:'/client/system-switch'"),'Bridge Plaza exposes both support File Folder view and the Client System Switch route')

const cleanRevealDashboard2026=read('components/world/weave-dashboard-world.tsx')
assert.ok(bridgePlazaPage.includes('System Switch · File Folder View')&&bridgePlazaPage.includes('setSupportOpen(true)'),'Bridge Plaza HUD exposes System Switch File Folder View without requiring discovery of a hidden panel')
assert.ok(cleanRevealDashboard2026.includes('weave-dashboard-world')&&cleanRevealDashboard2026.includes('<WeaveRouteNetwork'),'Dashboard world exposes live-theme shell and route-network movement')
assert.ok(cleanRevealCss2026.includes('html[data-weave-event="flame-live"] .weave-dashboard-world'),'Flame Live themes dashboard surfaces rather than adding a wallpaper')
assert.ok(cleanRevealTransit2026.includes('hasPendingSurface()&&elapsed<absoluteMaximum'),'Pending application state holds the clean reveal only until the absolute recovery ceiling')
assert.ok(cleanRevealTransit2026.includes('const LOADING_CARD_HOLD_MS=2000'),'Loading briefs remain visible long enough to read')
assert.ok(cleanRevealTransit2026.includes('const LOADING_SEQUENCE_MS=PLATFORM_BRIEFS.length*LOADING_CARD_HOLD_MS'),'Environment reveal waits for the complete three-card briefing sequence')
assert.ok(cleanRevealTransit2026.includes('activeBriefs.map((_,index)'),'Loading progress follows whichever three-card briefing is active without removing the normal platform sequence')
assert.ok(cleanRevealTransit2026.includes("document.addEventListener('click',handleInternalNavigation,true)"),'Internal navigation primes the environment cover at click time, including sidebar links')
assert.ok(cleanRevealTransit2026.includes('setReadyPath(null)')&&cleanRevealTransit2026.includes('setTransiting(true)'),'Sidebar movement hides the old environment immediately while preserving destination formation')
assert.ok(cleanRevealTransit2026.includes("waitForBriefingSequence('transit',startedAt,controller.signal)\n          .then(()=>waitForEnvironmentReadiness('transit'"),'Query-only sidebar stations use the short travel handoff before the final readiness check')
const loadingBriefCss2026=read('app/weave-readability.css')
assert.ok(loadingBriefCss2026.includes('@keyframes weave-loading-brief-cycle')&&loadingBriefCss2026.includes('.weave-loading-brief'),'Loading cards enter as discrete readable briefing surfaces')


/* Environment grammar: major operating surfaces may contain instruments,
   but their primary navigation cannot regress into a card grid. */
const routeNetwork=read('components/world/weave-route-network.tsx')
const clientOperatingRoom=read('components/client/client-operating-room.tsx')
const marketplaceEnvironment=read('app/(app)/marketplace/page.tsx')
const arenaEnvironment=read('components/places/arena.tsx')
const loungeEnvironment=read('components/places/lounge.tsx')
const patternEnvironment=read('components/places/casino.tsx')
const echoEnvironment=read('app/(app)/echo/page.tsx')

assert.ok(routeNetwork.includes('data-weave-route-network')&&routeNetwork.includes('data-weave-route-station'),'Shared route grammar exposes connected lanes and stations')
assert.ok(dashboardWorld.includes('<WeaveRouteNetwork'),'Role Home Worlds use route stations instead of WorldLinkCard tiles')
assert.ok(!dashboardWorld.includes('WorldLinkCard'),'Role Home Worlds cannot regress to a link-card grid')
assert.ok(operatingRoom.includes('<WeaveRouteNetwork')&&operatingRoom.includes('Role route network'),'Agent/Admin Operating Rooms use connected route lanes')
assert.ok(bridgerOperatingRoom.includes('<WeaveRouteNetwork')&&bridgerOperatingRoom.includes('Prospect intake dock'),'Bridger Operating Room combines route lanes with one Prospect intake station')
assert.ok(clientOperatingRoom.includes('<WeaveRouteNetwork')&&clientOperatingRoom.includes('Client route network'),'Client Operating Room uses connected lanes around the File Folder')
assert.ok(room.includes('data-weave-room-stage'),'Reusable WEAVE rooms expose one active stage between environment rails')
assert.ok(marketplaceEnvironment.includes('data-enterprise-exchange-floor')&&!marketplaceEnvironment.includes('grid gap-5 md:grid-cols-2 xl:grid-cols-3'),'Enterprise Exchange is a continuous bay floor, not a product-card grid')
assert.ok(arenaEnvironment.includes('data-arena-environment')&&arenaEnvironment.includes('data-arena-lane'),'Arena renders contests as lanes inside one ground')
assert.ok(loungeEnvironment.includes('data-lounge-environment'),'Lounge owns a continuous communication environment instead of a floating chat card')
assert.ok(patternEnvironment.includes('data-pattern-ground')&&patternEnvironment.includes('data-pattern-stage="dice"'),'Pattern Ground exposes a continuous play stage')
assert.ok(echoEnvironment.includes('data-echo-board')&&echoEnvironment.includes('data-echo-station="insights"'),'Echo is a continuous intelligence board with functional stations')


const bridgeAiEnvironment=read('app/(app)/bridger/bridge-ai/page.tsx')
const prospectEngineEnvironment=read('app/(app)/admin/prospect-engine/page.tsx')
const originSystemsEnvironment=read('app/(app)/admin/origin-systems/page.tsx')
const adminRootEnvironment=read('app/(app)/admin/page.tsx')

assert.ok(bridgeAiEnvironment.includes('data-bridge-ai-environment')&&bridgeAiEnvironment.includes('data-bridge-ai-paths'),'Bridge AI renders crossing paths inside one environment')
assert.ok(!bridgeAiEnvironment.includes('<Card'),'Bridge AI no longer uses Card as its primary path surface')
assert.ok(prospectEngineEnvironment.includes('roomKey="administration-prospect-engine"')&&prospectEngineEnvironment.includes('data-prospect-pool'),'Prospect Engine is a shared Administration system room')
assert.ok(!prospectEngineEnvironment.includes('<Card'),'Prospect Engine no longer uses literal cards as its operating structure')
assert.ok(originSystemsEnvironment.includes('roomKey="administration-origin-systems"')&&originSystemsEnvironment.includes('data-origin-systems-network'),'Origin Systems is one infrastructure environment')
assert.ok(!originSystemsEnvironment.includes('<Card'),'Origin Systems no longer uses literal cards as its infrastructure structure')
assert.ok(adminRootEnvironment.includes("redirect('/admin/dashboard')")&&!adminRootEnvironment.includes('<Card'),'Duplicate Administration root routes directly into the Administration world')


/* Live words: language participates in the same flame/motion state as the world. */
const liveFlameCss=read('app/globals.css')
const liveWordSurface=read('components/world/weave-environment-surface.tsx')
const liveWordRoutes=read('components/world/weave-route-network.tsx')
const liveWordSidebar=read('components/app-sidebar.tsx')
assert.ok(liveFlameCss.includes('@keyframes weave-live-word-flow')&&liveFlameCss.includes('@keyframes weave-word-flare'),'Live flame CSS has continuous word flow and motion-triggered flare')
assert.ok(liveFlameCss.includes('html[data-weave-pulse] [data-weave-live-word]'),'Confirmed movement propagates into live words')
assert.ok(liveWordSurface.includes('data-weave-live-word="title"'),'Environment titles carry live flame state')
assert.ok(liveWordRoutes.includes('data-weave-live-word="station"'),'Route and station words carry live flame state')
assert.ok(liveWordSidebar.includes('data-weave-live-word="station"'),'Sidebar words participate in the live system')
assert.ok(!read('app/(auth)/layout.tsx').includes('FlameEventWorldGate'),'Authentication no longer mounts a second event wallpaper')


/* Platform load stability: no route may permanently cover, crop or poll itself into a freeze. */
const loadStabilityFetch=read('lib/fetch-with-timeout.ts')
const loadStabilityAuth=read('lib/auth-provider.tsx')
const loadStabilityAuthLayout=read('app/(auth)/layout.tsx')
const loadStabilityClientLogin=read('app/client/login/page.tsx')
const loadStabilityClientRegister=read('app/client/register/page.tsx')
const loadStabilityClientFolder=read('app/client/system-switch/page.tsx')
const loadStabilitySupportFolder=read('app/(app)/weave/file-folder/[fileNumber]/page.tsx')
const loadStabilityAdaptive=read('components/world/use-adaptive-runtime.ts')
const loadStabilityFlame=read('components/world/weave-live-flame-field.tsx')
const loadStabilityRegistrationChat=read('components/registration-chat.tsx')
const loadStabilityClientChat=read('app/client/chat/[position]/page.tsx')
const loadStabilityBridgerClients=read('app/(app)/bridger/clients/page.tsx')
const loadStabilityAgentChat=read('app/(app)/agent-chat/[clientId]/[position]/page.tsx')
const loadStabilityAdminHub=read('app/(app)/admin/hub/page.tsx')
const loadStabilityAdminMessages=read('app/(app)/admin/client-messages/page.tsx')
const loadStabilityDeptRegistration=read('app/(app)/admin/departmental-registration/page.tsx')
const loadStabilityTicketPanel=read('components/admin/department-entry-tickets-panel.tsx')
const loadStabilityTicketGate=read('components/department-entry-ticket-gate.tsx')
const loadStabilityDjPlayer=read('components/dj-broadcast-player.tsx')
const loadStabilityDjWorkshop=read('app/(app)/admin/dj-workshop/page.tsx')

assert.ok(cleanRevealTransit2026.includes('absoluteMaximum')&&cleanRevealTransit2026.includes('elapsed<absoluteMaximum'),'Global environment cover has an absolute ceiling even when a destination leaves a pending marker mounted')
assert.ok(loadStabilityClientFolder.includes('new AbortController()')&&loadStabilityClientFolder.includes('12000')&&loadStabilityClientFolder.includes('signal:controller.signal'),'Client File Folder boot has a bounded network wait')
assert.ok(loadStabilitySupportFolder.includes('new AbortController()')&&loadStabilitySupportFolder.includes('12000')&&loadStabilitySupportFolder.includes('signal:controller.signal'),'Support File Folder entry has a bounded network wait')
assert.ok(loadStabilityFetch.includes('Request timed out. Check the connection and try again.'),'Blocking user actions have one reusable timeout failure mode')
assert.ok(loadStabilityAuth.includes("fetchWithTimeout('/api/auth/register'")&&loadStabilityAuth.includes("fetchWithTimeout('/api/auth/login'"),'Staff/Bridger/Agent authentication cannot spin forever on a stalled request')
assert.ok(loadStabilityClientLogin.includes("fetchWithTimeout('/api/client/weave-login'"),'Client login cannot spin forever on a stalled request')
assert.ok(loadStabilityClientRegister.includes('fetchWithTimeout')&&loadStabilityClientRegister.includes('/api/client/weave-validate'),'Client registration validation is bounded')
assert.ok(loadStabilityAuthLayout.includes('overflow-y-auto')&&!loadStabilityAuthLayout.includes('justify-center overflow-hidden'),'Shared auth shell does not crop tall registration states')
assert.ok(loadStabilityClientLogin.includes('overflow-y-auto')&&!loadStabilityClientLogin.includes('justify-center bg-transparent p-4 relative overflow-hidden'),'Client login can scroll on short screens')
assert.ok(loadStabilityClientRegister.includes('overflow-y-auto')&&!loadStabilityClientRegister.includes('justify-center bg-transparent p-4 relative overflow-hidden'),'Client registration can scroll on short screens')
assert.ok(loadStabilityAdaptive.includes('level===1?20:12')&&loadStabilityAdaptive.includes("level===1?.85:.7"),'Adaptive runtime lowers medium/mobile FPS and DPR instead of overdriving phones')
assert.ok(loadStabilityAdaptive.includes('dataset.weaveCovered'),'Environment cover state is published so decorative animation can pause during loading')
assert.ok(loadStabilityFlame.includes('1000/Math.max(12,runtime.fps)'),'Pointer-driven Flame updates respect the adaptive frame budget')
assert.ok(cleanRevealCss2026.includes('html[data-weave-covered="true"] .weave-live-flame-current')&&cleanRevealCss2026.includes('html[data-weave-quality="1"] .weave-live-flame-current-b'),'Covered/mobile Flame layers reduce compositor work')
for(const [source,label] of [
 [loadStabilityRegistrationChat,'registration chat'],
 [loadStabilityClientChat,'Client chat'],
 [loadStabilityBridgerClients,'Bridger Client chat'],
 [loadStabilityAgentChat,'Agent chat'],
 [loadStabilityAdminHub,'Administration hub'],
 [loadStabilityAdminMessages,'Administration Client messages'],
 [loadStabilityDeptRegistration,'departmental registration chat'],
 [loadStabilityTicketPanel,'entry ticket panel'],
 [loadStabilityTicketGate,'entry ticket gate'],
 [loadStabilityDjPlayer,'live DJ player'],
 [loadStabilityDjWorkshop,'DJ Workshop'],
]){
 assert.ok(source.includes('visiblePoll'),label+' uses serial visible polling')
}
assert.ok(!loadStabilityDjPlayer.includes('setInterval(() => void syncBroadcast()'),'DJ player no longer launches overlapping hidden-tab network intervals')
assert.ok(!loadStabilityAdminHub.includes('setInterval(loadMessages'),'Administration hub no longer stacks message requests')
