'use client'
import { useEffect,useState } from 'react'
import { getAuthHeaders } from '@/lib/auth-client'
import { Phone,ShoppingCart,CheckCircle2 } from 'lucide-react'
import { toast } from 'sonner'

export default function BridgerNumbersPage(){
 const [available,setAvailable]=useState<any[]>([]),[mine,setMine]=useState<any[]>([]),[buying,setBuying]=useState<string|null>(null)
 const load=async()=>{const r=await fetch('/api/bridger/numbers',{headers:getAuthHeaders(),cache:'no-store'});const d=await r.json();if(!r.ok)return toast.error(d.error||'Unable to load Number Market');setAvailable(d.available||[]);setMine(d.mine||[])}
 useEffect(()=>{void load()},[])
 const buy=async(id:string)=>{setBuying(id);try{const r=await fetch('/api/bridger/numbers',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify({numberId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Purchase failed');toast.success('Number assigned to your Bridger position');await load()}catch(e:any){toast.error(e.message)}finally{setBuying(null)}}
 return <main className="mx-auto max-w-6xl p-4 md:p-7">
  <header className="rounded-[2rem] border border-cyan-300/15 bg-[#03101a]/80 p-6 backdrop-blur-xl"><p className="text-[9px] font-black uppercase tracking-[.24em] text-cyan-300">Bridger · Communication Infrastructure</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black text-white"><Phone className="h-7 w-7"/>WhatsApp Number Market</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Purchase a provisioned number assigned by WEAVE Administration. After assignment, complete WhatsApp or WhatsApp Business verification normally with the number provider. WEAVE never asks for your WhatsApp OTP or password.</p></header>
  <section className="mt-5 rounded-[1.6rem] border border-white/10 bg-black/30 p-5"><h2 className="font-black text-white">Available inventory</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{available.length===0?<p className="text-sm text-slate-500">No numbers are currently available.</p>:available.map(n=><article key={n.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-cyan-300">{n.country}</p><p className="mt-2 text-sm font-bold text-white">{n.provider||'Provisioned business number'}</p><p className="mt-3 text-xl font-black text-white">{Number(n.price_flame_coin).toLocaleString()} <span className="text-xs text-slate-500">Flame Coin</span></p><p className="mt-2 text-[10px] text-slate-500">The number itself is revealed after successful assignment.</p><button onClick={()=>void buy(n.id)} disabled={buying===n.id} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-400 px-3 py-2.5 text-xs font-black text-black disabled:opacity-50"><ShoppingCart className="h-4 w-4"/>{buying===n.id?'Assigning…':'Purchase + assign'}</button></article>)}</div></section>
  <section className="mt-5 rounded-[1.6rem] border border-emerald-300/10 bg-black/30 p-5"><h2 className="font-black text-white">My WhatsApp numbers</h2><div className="mt-4 space-y-2">{mine.length===0?<p className="text-sm text-slate-500">No number has been assigned to you yet.</p>:mine.map(n=><article key={n.id} className="rounded-2xl border border-emerald-300/10 bg-emerald-400/[.03] p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 font-mono text-lg font-black text-white"><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{n.phone_e164}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-500">{n.country} · {n.provider||'Provider'} · assigned {n.assigned_at?new Date(n.assigned_at).toLocaleDateString():''}</p></div><p className="text-sm font-black text-emerald-300">{Number(n.price_flame_coin).toLocaleString()} FC</p></div></article>)}</div></section>
 </main>
}