'use client'
import { useEffect,useState } from 'react'
import { getAuthHeaders } from '@/lib/auth-client'
import { Phone,ShoppingCart,CheckCircle2,Clock3 } from 'lucide-react'
import { toast } from 'sonner'
export default function BridgerNumbersPage(){
 const [available,setAvailable]=useState<any[]>([]),[mine,setMine]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[buying,setBuying]=useState<string|null>(null)
 const load=async()=>{const [a,b]=await Promise.all([fetch('/api/bridger/numbers',{headers:getAuthHeaders(),cache:'no-store'}),fetch('/api/bridger/number-verifications',{headers:getAuthHeaders(),cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)return toast.error(x.error||'Unable to load Number Market');if(!b.ok)return toast.error(y.error||'Unable to load code requests');setAvailable(x.available||[]);setMine(x.mine||[]);setRequests(y.requests||[])}
 useEffect(()=>{void load()},[])
 const buy=async(id:string)=>{setBuying(id);try{const r=await fetch('/api/bridger/numbers',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify({numberId:id})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Purchase failed');toast.success('WEAVE WhatsApp number assigned');await load()}catch(e:any){toast.error(e.message)}finally{setBuying(null)}}
 const requestCode=async(numberId:string,method:'sms'|'call')=>{const r=await fetch('/api/bridger/number-verifications',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify({numberId,method})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Could not request code');toast.success(method==='sms'?'SMS code requested':'Call code requested');void load()}
 const verify=async(id:string)=>{const r=await fetch('/api/bridger/number-verifications',{method:'PATCH',headers:getAuthHeaders(),body:JSON.stringify({id})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Could not complete verification');toast.success('Number verification completed');void load()}
 const activeFor=(id:string)=>requests.find(r=>r.number_id===id&&['requested','pending','code_ready'].includes(r.status))
 return <main className="mx-auto max-w-6xl p-4 md:p-7"><header className="rounded-[2rem] border border-cyan-300/15 bg-[#03101a]/80 p-6"><p className="text-[9px] font-black uppercase tracking-[.24em] text-cyan-300">Bridger · Worldwide Number Access</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black text-white"><Phone/>WhatsApp Number Engine</h1><p className="mt-3 text-sm text-slate-400">Purchase a WEAVE Worldwide WhatsApp Number, use it for your registration or login, then request SMS or call verification. WEAVE Administration returns the verification movement here.</p></header>
 <section className="mt-5 rounded-[1.6rem] border border-white/10 bg-black/30 p-5"><h2 className="font-black text-white">Available batteries</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{available.length===0?<p className="text-sm text-slate-500">No worldwide WhatsApp numbers are currently available.</p>:available.map(n=><article key={n.id} className="rounded-2xl border border-white/10 p-4"><p className="text-[10px] font-black uppercase text-cyan-300">{n.country} · WEAVE Worldwide</p><p className="mt-3 text-xl font-black text-white">{Number(n.price_flame_coin).toLocaleString()} <span className="text-xs text-slate-500">FC</span></p><p className="mt-2 text-[10px] text-slate-500">Number revealed after assignment.</p><button onClick={()=>void buy(n.id)} disabled={buying===n.id} className="mt-4 w-full rounded-xl bg-cyan-400 p-2.5 text-xs font-black text-black"><ShoppingCart className="mr-2 inline h-4 w-4"/>{buying===n.id?'Assigning…':'Buy number'}</button></article>)}</div></section>
 <section className="mt-5 rounded-[1.6rem] border border-emerald-300/10 bg-black/30 p-5"><h2 className="font-black text-white">My numbers + verification</h2><div className="mt-4 space-y-3">{mine.length===0?<p className="text-sm text-slate-500">No assigned number.</p>:mine.map(n=>{const r=activeFor(n.id);return <article key={n.id} className="rounded-2xl border border-emerald-300/10 p-4"><p className="flex items-center gap-2 font-mono text-lg font-black text-white"><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{n.phone_e164}</p><p className="text-[10px] uppercase text-slate-500">WEAVE Worldwide · {n.country}</p>{!r?<div className="mt-3 flex gap-2"><button onClick={()=>void requestCode(n.id,'sms')} className="rounded-lg bg-white/10 px-3 py-2 text-[10px] font-black text-white">Request SMS</button><button onClick={()=>void requestCode(n.id,'call')} className="rounded-lg bg-white/10 px-3 py-2 text-[10px] font-black text-white">Request Call</button></div>:<div className="mt-3 rounded-xl border border-amber-300/10 bg-amber-300/[.025] p-3"><p className="flex items-center gap-1 text-[10px] font-black uppercase text-amber-300"><Clock3 className="h-3 w-3"/>{r.status} · {r.method}</p>{r.status==='requested'&&<p className="mt-2 text-xs text-slate-400">WEAVE Administration is processing verification. Window ends {new Date(r.deadline_at).toLocaleTimeString()}.</p>}{r.status==='pending'&&<p className="mt-2 text-xs text-slate-300">{r.admin_message||'Verification is still processing. Your number remains reserved to you. Administration will update this request.'}</p>}{r.status==='code_ready'&&<><p className="mt-2 text-[10px] uppercase text-slate-500">Verification code</p><p className="mt-1 font-mono text-2xl font-black tracking-widest text-white">{r.verification_code}</p><button onClick={()=>void verify(r.id)} className="mt-3 rounded-lg bg-emerald-400 px-3 py-2 text-[10px] font-black text-black">I verified WhatsApp</button></>}</div>}</article>})}</div></section></main>
}