'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { BatteryCharging,CheckCircle2,Clock3,Phone,RefreshCw,ShieldCheck,ShoppingCart } from 'lucide-react'
import { getAuthHeaders } from '@/lib/auth-client'
import { toast } from 'sonner'
import { WeaveSystemRoom } from '@/components/world/weave-system-room'

export default function BridgerNumbersPage(){
 const [available,setAvailable]=useState<any[]>([]),[mine,setMine]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[buying,setBuying]=useState<string|null>(null),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/bridger/numbers',{headers:getAuthHeaders(),cache:'no-store'}),fetch('/api/bridger/number-verifications',{headers:getAuthHeaders(),cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error||'Unable to load Number Bay');if(!b.ok)throw new Error(y.error||'Unable to load verification movement');setAvailable(x.available||[]);setMine(x.mine||[]);setRequests(y.requests||[])}catch(e:any){toast.error(e.message||'Unable to load Number Bay')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const buy=async(id:string)=>{setBuying(id);try{const r=await fetch('/api/bridger/numbers',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify({numberId:id})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Purchase failed');toast.success('WEAVE WhatsApp number assigned');await load()}catch(e:any){toast.error(e.message)}finally{setBuying(null)}}
 const requestCode=async(numberId:string,method:'sms'|'call')=>{const r=await fetch('/api/bridger/number-verifications',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify({numberId,method})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Could not request code');toast.success(method==='sms'?'SMS verification requested':'Call verification requested');void load()}
 const verify=async(id:string)=>{const r=await fetch('/api/bridger/number-verifications',{method:'PATCH',headers:getAuthHeaders(),body:JSON.stringify({id})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Could not complete verification');toast.success('Number verification completed');void load()}
 const activeFor=(id:string)=>requests.find(r=>r.number_id===id&&['requested','pending','code_ready'].includes(r.status))

 const left=<>
  <section className="rounded-3xl border border-cyan-300/15 bg-cyan-400/[.035] p-4"><Phone className="h-5 w-5 text-cyan-300"/><p className="mt-3 text-sm font-black text-white">Worldwide Number Bay</p><p className="mt-2 text-xs leading-5 text-slate-400">WEAVE holds the provider layer. Your Bridger position sees only the WEAVE number product and its Flame Coin value.</p></section>
  <section className="rounded-3xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Bay state</p><div className="mt-3 grid grid-cols-2 gap-2 text-center"><div className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="text-xl font-black text-cyan-200">{available.length}</p><p className="text-[8px] uppercase text-slate-500">Available</p></div><div className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="text-xl font-black text-emerald-200">{mine.length}</p><p className="text-[8px] uppercase text-slate-500">Owned</p></div></div></section>
 </>

 const center=<>
  <div className="flex items-end justify-between gap-3 border-b border-white/10 pb-4"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-300">Available batteries</p><h2 className="mt-1 text-xl font-black text-white">Number inventory</h2><p className="mt-2 text-xs text-slate-400">The number stays hidden until assignment. Flame Coin is the only price exposed to the Bridger position.</p></div><button onClick={()=>void load()} aria-label="Refresh Number Bay" className="rounded-xl border border-white/10 p-2"><RefreshCw className={`h-4 w-4 text-slate-400 ${loading?'animate-spin':''}`}/></button></div>
  <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{available.length===0?<p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No worldwide numbers are available.</p>:available.map(n=><article key={n.id} className="rounded-2xl border border-cyan-300/10 bg-cyan-400/[.025] p-4"><BatteryCharging className="h-5 w-5 text-cyan-300"/><p className="mt-3 text-[9px] font-black uppercase tracking-wider text-cyan-300">{n.country} · WEAVE Worldwide</p><p className="mt-2 text-2xl font-black text-white">{Number(n.price_flame_coin).toLocaleString()} <span className="text-xs text-slate-500">FC</span></p><p className="mt-2 text-[10px] leading-5 text-slate-500">Identity revealed only after successful assignment.</p><button data-presence-output={`Buy WEAVE number for ${Number(n.price_flame_coin).toLocaleString()} Flame Coin`} onClick={()=>void buy(n.id)} disabled={buying===n.id} className="mt-4 w-full rounded-xl bg-cyan-300 p-2.5 text-xs font-black text-slate-950 disabled:opacity-40"><ShoppingCart className="mr-2 inline h-4 w-4"/>{buying===n.id?'Assigning…':'Buy number'}</button></article>)}</div>
  <div className="mt-6 border-t border-white/10 pt-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-300">Assigned stack</p><h2 className="mt-1 text-xl font-black text-white">My numbers + verification</h2></div>
  <div className="mt-4 space-y-3">{mine.length===0?<p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No assigned number yet.</p>:mine.map(n=>{const r=activeFor(n.id);return <article key={n.id} className="rounded-2xl border border-emerald-300/10 bg-emerald-400/[.025] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-mono text-lg font-black text-white"><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{n.phone_e164}</p><p className="mt-1 text-[9px] font-black uppercase text-slate-500">WEAVE Worldwide · {n.country}</p></div><p className="text-sm font-black text-emerald-200">{Number(n.price_flame_coin).toLocaleString()} FC</p></div>{!r?<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void requestCode(n.id,'sms')} className="rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-[10px] font-black text-white">Request SMS</button><button onClick={()=>void requestCode(n.id,'call')} className="rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-[10px] font-black text-white">Request Call</button></div>:<div className="mt-3 rounded-xl border border-amber-300/10 bg-amber-300/[.025] p-3"><p className="flex items-center gap-1 text-[9px] font-black uppercase text-amber-300"><Clock3 className="h-3 w-3"/>{r.status} · {r.method}</p>{r.status==='requested'&&<p className="mt-2 text-xs text-slate-400">Administration is processing verification. Window ends {new Date(r.deadline_at).toLocaleTimeString()}.</p>}{r.status==='pending'&&<p className="mt-2 text-xs text-slate-300">{r.admin_message||'Verification remains pending. The number stays reserved to you.'}</p>}{r.status==='code_ready'&&<><p className="mt-2 text-[9px] uppercase text-slate-500">Verification code</p><p className="mt-1 font-mono text-2xl font-black tracking-widest text-white">{r.verification_code}</p><button onClick={()=>void verify(r.id)} className="mt-3 rounded-xl bg-emerald-300 px-3 py-2 text-[10px] font-black text-slate-950">I verified WhatsApp</button></>}</div>}</article>})}</div>
 </>

 const right=<>
  <section className="rounded-3xl border border-amber-300/15 bg-amber-400/[.035] p-4"><ShieldCheck className="h-5 w-5 text-amber-300"/><p className="mt-3 text-sm font-black text-white">WEAVE wrapper</p><p className="mt-2 text-xs leading-5 text-slate-400">Provider acquisition data remains Administration-only. Bridgers see the Flame Coin product value, assignment state and verification movement.</p></section>
  <Link href="/bridger/functions" className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-xs font-black text-white">Bridger Operating Room <span className="text-cyan-300">→</span></Link>
 </>

 return <WeaveSystemRoom roomKey="bridger-number-bay" eyebrow="Bridge · Worldwide Number Access" title="Number Bay" detail="A live stock-and-verification environment for WEAVE WhatsApp numbers. Purchase, assignment and verification remain one continuous Bridger movement." tone="cyan" left={left} center={center} right={right} pulse={requests.some(r=>['requested','pending'].includes(r.status))?'Verification movement active':'Number Bay ready'}/>
}
