export type WeaveRole='client'|'agent'|'bridger'|'admin'
export type WeaveDistrictKey='presence'|'position'|'bridge'|'enterprise'|'participation'|'administration'

export type WeaveRolePlace={
  label:string
  detail:string
  href:string
  daily?:boolean
}

export type WeaveRoleDistrict={
  key:WeaveDistrictKey
  name:string
  subtitle:string
  purpose:string
  accent:string
  places:WeaveRolePlace[]
}

// One canonical catalog. Districts group genuinely different movement; labels do
// not create duplicate rooms for the same continuity.
const byRole:Record<WeaveRole,WeaveRoleDistrict[]>={
  agent:[
    {
      key:'presence',
      name:'Presence',
      subtitle:'UNDERSTAND YOUR POSITION',
      purpose:'Understand the Agent position before entering its working functions.',
      accent:'#7dd3fc',
      places:[
        {label:'Agent Presence',href:'/agent/presence',detail:'Understand the Agent position, Agility movement and commission return.',daily:true},
        {label:'Settings',href:'/settings',detail:'Manage identity, password and the current signed-in Agent session.'},
      ],
    },
    {
      key:'position',
      name:'Agent Work',
      subtitle:'AGILITY + EARNINGS',
      purpose:'Carry real distribution through Agility and receive the Agent shares generated by qualifying Bridger and Client movement.',
      accent:'#34d399',
      places:[
        {label:'Agility',href:'/agility',detail:'Order, receive, distribute and record Agility movement.',daily:true},
        {label:'Commissions',href:'/agent/commissions',detail:'See Prospect purchase shares and verified Client File Folder shares generated through attached Bridgers.',daily:true},
      ],
    },
    {
      key:'bridge',
      name:'Connection & Event',
      subtitle:'BRIDGER + LOOP ONE',
      purpose:'Speak directly with attached Bridgers and enter the shared Company Loop 1 Flame Event.',
      accent:'#f59e0b',
      places:[
        {label:'Direct Communication',href:'/communications',detail:'Message Bridgers attached to your Agent position directly.',daily:true},
        {label:'Flame Event · Loop 1',href:'/event',detail:'Enter the same Burning River event ground used by every WEAVE role.',daily:true},
      ],
    },
  ],
  bridger:[
    {
      key:'presence',
      name:'Presence',
      subtitle:'UNDERSTAND YOUR POSITION',
      purpose:'Understand the Bridger position and the movement it carries before entering Bridge tools.',
      accent:'#7dd3fc',
      places:[
        {label:'Bridger Presence',href:'/bridger/presence',detail:'Understand Prospect movement, Bridge AI, Number Bay, Email Outreach, Echo and value continuity.',daily:true},
        {label:'Settings',href:'/settings',detail:'Manage identity, password and the current signed-in Bridger session.'},
      ],
    },
    {
      key:'bridge',
      name:'Prospect & Crossing',
      subtitle:'ACQUIRE → OUTREACH → CLIENT',
      purpose:'Acquire Prospects, operate human-first outreach, carry people toward Client crossing and receive the Bridger share when a guided Prospect completes a verified File Folder purchase.',
      accent:'#22d3ee',
      places:[
        {label:'Crossing Notebook',href:'/bridger/crossing-notebook',detail:'Read the Prospect → Bridge → File Folder → Client crossing one manual step at a time before carrying real outreach.',daily:true},
        {label:'Prospect Market',href:'/weave/market/prospects',detail:'Claim the daily Prospect or purchase Prospect movement.',daily:true},
        {label:'Email Outreach',href:'/bridger/email-outreach',detail:'Acquire lower-cost email Prospects, send from your configured reply identity and inspect movement reports.',daily:true},
        {label:'Number Bay',href:'/bridger/numbers',detail:'Purchase authenticated numbers and follow delivery and verification.',daily:true},
        {label:'Bridge AI',href:'/bridger/bridge-ai',detail:'Use and maintain the Bridge AI crossing path.',daily:true},
        {label:'Echo',href:'/echo',detail:'Operate authorized AI-assisted outreach and amplification.'},
      ],
    },
    {
      key:'participation',
      name:'Continuity',
      subtitle:'VALUE + PEOPLE + LOOP ONE',
      purpose:'Keep value, direct communication, visible Presences and the current company event together as one continuity movement instead of separate duplicate districts.',
      accent:'#a78bfa',
      places:[
        {label:'Deposit & Withdrawal',href:'/wallet/deposit-withdraw',detail:'Deposit Flame Coin value or request withdrawal.',daily:true},
        {label:'Direct Communication',href:'/communications',detail:'Message your assigned Agent, Prospect conversations and referred Clients from one authorized place.',daily:true},
        {label:'Presences',href:'/profiles',detail:'See people and active Presences inside WEAVE.'},
        {label:'Flame Event · Loop 1',href:'/event',detail:'Enter the same Burning River event ground used by every WEAVE role.',daily:true},
      ],
    },
  ],
  client:[
    {
      key:'presence',
      name:'Presence',
      subtitle:'UNDERSTAND YOUR WORLD',
      purpose:'Understand the Client position, the File Folder and how work, value and support continue through the Client world.',
      accent:'#7dd3fc',
      places:[
        {label:'Client Presence',href:'/client/presence',detail:'Understand your Client world, File Folder, value movement and support paths.',daily:true},
      ],
    },
    {
      key:'position',
      name:'File Folder',
      subtitle:'BUILD + OPERATE',
      purpose:'Enter System Switch, build systems and operate the Client File Folder.',
      accent:'#34d399',
      places:[
        {label:'File Folder',href:'/client/system-switch',detail:'Build and operate systems, your store and Customer Door.',daily:true},
        {label:'Enterprise Systems',href:'/marketplace',detail:'Explore enterprise-scale systems for your work.'},
        {label:'Settings',href:'/client/settings',detail:'Manage your Client identity and account.'},
      ],
    },
    {
      key:'participation',
      name:'Funds & Records',
      subtitle:'VALUE + EVIDENCE',
      purpose:'Fund work, release available value and preserve financial evidence.',
      accent:'#f59e0b',
      places:[
        {label:'Deposit',href:'/client/deposit',detail:'Fund your Client work.'},
        {label:'Withdraw',href:'/client/withdraw',detail:'Request controlled release of available value.'},
        {label:'Wallet',href:'/wallet',detail:'See balances and value movement.'},
        {label:'Records',href:'/ledger',detail:'See preserved payment and earning history.'},
        {label:'Receipts',href:'/receipts',detail:'See payment, purchase and withdrawal receipts.'},
      ],
    },
    {
      key:'bridge',
      name:'Support & Continuity',
      subtitle:'WEAVE POSITIONS + LOOP ONE',
      purpose:'Reach the WEAVE position needed for the next movement and continue into Company Loops or the current Flame Event without a second duplicate district.',
      accent:'#a78bfa',
      places:[
        {label:'Your Bridger',href:'/client/chat/bridger',detail:'Contact Your Bridger for crossing and continuity support.'},
        {label:'Mandate',href:'/client/chat/mandate',detail:'Contact Mandate for operational support.'},
        {label:'Forensics',href:'/client/chat/forensic',detail:'Contact Forensics for value and verification support.'},
        {label:'Attorney',href:'/client/chat/lawyer',detail:'Contact Attorney for legal support.'},
        {label:'Administration',href:'/client/chat/admin',detail:'Contact Administration for institutional support.'},
        {label:'Loop Field',href:'/client/loops',detail:'See Company Loops, responsibilities, agreements and participation stages.'},
        {label:'Flame Event · Loop 1',href:'/client/event',detail:'Enter the current Client event ground and live Loop 1 movement.',daily:true},
      ],
    },
  ],
  admin:[
    {
      key:'position',
      name:'Control',
      subtitle:'PEOPLE + AUTHORITY',
      purpose:'Govern people, departmental placement, Bridger standing and institutional authorization from one control district.',
      accent:'#60a5fa',
      places:[
        {label:'Administration Control Center',href:'/admin/control-center',detail:'Users, departmental authorization, Bridger operations, verification queues and announcements.',daily:true},
        {label:'Departmental Registration',href:'/admin/departmental-registration',detail:'Issue departmental codes and company placement.'},
        {label:'Subscriptions',href:'/admin/subscriptions',detail:'Review subscription and Continuance standing.'},
        {label:'Settings',href:'/settings',detail:'Manage Administration identity, password and the current signed-in session.'},
      ],
    },
    {
      key:'presence',
      name:'Finance',
      subtitle:'VALUE + RECORDS',
      purpose:'Review, release and preserve institutional value movement without duplicating verification stations.',
      accent:'#f59e0b',
      places:[
        {label:'Client Deposits',href:'/admin/client-deposits',detail:'Review Client funding requests.',daily:true},
        {label:'Client Vaults',href:'/admin/client-vault',detail:'Administer Client vault movement.'},
        {label:'Payments',href:'/admin/payments',detail:'Institutional payment administration.'},
        {label:'Wallet',href:'/wallet',detail:'Administration balances and value position.'},
        {label:'Reserve',href:'/fund-wall',detail:'Institutional reserve and fund position.'},
        {label:'Records',href:'/ledger',detail:'Administration value history.'},
        {label:'Receipts',href:'/receipts',detail:'Receipts issued for Administration value movement.'},
      ],
    },
    {
      key:'bridge',
      name:'Operations',
      subtitle:'LIVE COMPANY SYSTEMS',
      purpose:'Operate the engines that move Clients, Prospects, Bridgers, Agility, email outreach and enterprise formation.',
      accent:'#22d3ee',
      places:[
        {label:'File Number Engine',href:'/admin/file-number-engine',detail:'Issue and administer Client File Numbers.',daily:true},
        {label:'Prospect Engine',href:'/admin/prospect-engine',detail:'Create and organize Prospect movement.',daily:true},
        {label:'Email Outreach',href:'/admin/email-outreach',detail:'Load email Prospects, configure Administration outreach, run the daily engine and inspect Admin/Bridger reports.',daily:true},
        {label:'Number Bay Engine',href:'/admin/bridger-numbers',detail:'Number Bay stock, delivery and verification authority.',daily:true},
        {label:'Bridge AI',href:'/admin/bridge-ai',detail:'Review Bridge AI crossing and Client continuity.'},
        {label:'Bridge Templates',href:'/admin/bridge-templates',detail:'Control Bridge AI crossing templates.'},
        {label:'Fulfillment Agent',href:'/admin/outreach',detail:'Authorized phone/WhatsApp Prospect outreach and delivery movement.'},
        {label:'Agility Fulfillment',href:'/admin/agility',detail:'Administer Agility orders and fulfillment.'},
        {label:'Enterprise Dream',href:'/admin/enterprise-dream',detail:'Lord/Lady elevation and enterprise plans.'},
        {label:'Client Build Catalog',href:'/admin/client-build-catalog',detail:'Control Client build systems and pricing.'},
        {label:'Enterprise Systems',href:'/admin/enterprise-systems',detail:'Build and administer enterprise-scale systems.'},
      ],
    },
    {
      key:'administration',
      name:'Workshops',
      subtitle:'BUILD + GOVERN',
      purpose:'Develop, govern and tune WEAVE itself through distinct Administration workshops.',
      accent:'#c084fc',
      places:[
        {label:'Authority Workshop',href:'/authority/workshops',detail:'Institutional structures and authority.'},
        {label:'Development Foundry',href:'/admin/development-agents',detail:'EIGHT and persistent coding agents developing WEAVE against the real source.'},
        {label:'WEAVE Integrity Engine',href:'/admin/dev-workshop',detail:'Inspect and safely repair live WEAVE system state.'},
        {label:'Origin Systems',href:'/admin/origin-systems',detail:'Inspect origin runtime and system foundations.'},
        {label:'Infrastructure',href:'/admin/infrastructure',detail:'Cloud Run, runtime and maintenance control.'},
        {label:'Visual Systems · Interaction in Motion',href:'/admin/visual-systems',detail:'Govern live Flame, River, route current and visual runtime.'},
        {label:'Environment Organizer',href:'/admin/environment-organizer',detail:'Withdraw, restore and reorder active WEAVE environments.'},
        {label:'Loop Workshop',href:'/admin/loop-workshop',detail:'Create and publish Company Loops.'},
        {label:'DJ Workshop',href:'/admin/dj-workshop',detail:'System sound and live atmosphere.'},
        {label:'Ad Workshop',href:'/admin/ad-workshop',detail:'Role-targeted communication without deployment.'},
      ],
    },
    {
      key:'enterprise',
      name:'Company Movement',
      subtitle:'MESSAGE + LOOP + EVENT',
      purpose:'Operate direct communication, Company Loops and the current event lifecycle as one company-movement district.',
      accent:'#fb7185',
      places:[
        {label:'Direct Communication',href:'/communications',detail:'Message Agents, Bridgers, Clients and Prospect conversations from one authorized environment.',daily:true},
        {label:'Company Loops',href:'/company/loops',detail:'Shared company movement visible across WEAVE.'},
        {label:'Company Guidance',href:'/company-chat',detail:'Use the shared company clarification channel.'},
        {label:'Campaign Flame',href:'/admin/campaign-flame',detail:'Campaign construction and coordinated movement.'},
        {label:'Flame Event · Loop 1',href:'/event',detail:'Enter the same Burning River event ground used by every WEAVE role.',daily:true},
        {label:'Flame Event Control',href:'/admin/flame-event',detail:'Administration-only event schedule, announcement and lifecycle control.'},
      ],
    },
  ],
}

export function normalizeWeaveRole(role?:string|null):WeaveRole{
  if(role==='admin'||role==='agent'||role==='bridger'||role==='client')return role
  return 'client'
}

export function getRoleDistricts(role?:string|null){
  return byRole[normalizeWeaveRole(role)]
}

export function getRoleDistrict(role:string|undefined|null,key:string){
  return getRoleDistricts(role).find(district=>district.key===key)||null
}

export function getRolePlaces(role?:string|null){
  return getRoleDistricts(role).flatMap(district=>district.places.map(place=>({...place,district:district.name})))
}
