export const WEAVE_WRITING_STYLE = {
  cadence: ['Place', 'Movement', 'State', 'Action', 'Continuation'],
  canonicalTerms: [
    'WEAVE',
    'The Weave of Presence',
    'System Switch',
    'Bridge Radiance',
    'Interaction in Motion',
    'Prospect',
    'Client',
    'Agent',
    'Bridger',
    'Administration',
    'Attorney',
    'Mandate',
    'Forensics',
    'File Folder',
    'File Number',
    'Operating Room',
    'movement',
    'position',
    'function',
    'environment',
    'record',
    'value',
    'continuation',
  ],
  rules: [
    'Name the place before explaining it.',
    'Describe what is moving, not what the interface resembles.',
    'State the current condition before the available action.',
    'Use direct verbs for actions.',
    'Keep institutional terms stable across roles and routes.',
    'Reserve technical words such as terminal and protocol for actual technical functions.',
  ],
} as const

export const WEAVE_WRITING = {
  identity: {
    institution: 'The Weave of Presence',
    subject: 'System Switch — Bridge Radiance',
    movement: 'Interaction in Motion',
  },

  bridgeRadiance: {
    eyebrow: 'Bridge Radiance',
    title: 'Connection becoming Client movement.',
    detail:
      'Bridge Radiance keeps the Prospect movement visible while company functions bring clarity, execution, confirmation and recognition into one crossing.',
    position: 'Prospect position',
    movement: 'Prospect movement',
    topic: 'Current topic',
    fileNumber: 'File Number',
    fileNumberPending: 'Not yet issued',
    arrival: 'Movement received',
    movementCount: 'Bridge movement',
    action: 'Continue to File Folder',
    event: 'Flame Event · Burning River',
    eventName: 'The River that Burns',
  },

  fileFolderCrossing: {
    eyebrow: 'File Folder Crossing',
    title: 'Establish the Client world.',
    detail:
      'The File Folder is the Client’s persistent operating environment. Record the TRX movement here. Administration verifies it, issues the File Number and opens the Client crossing into System Switch.',
    stages: [
      'Prospect',
      'File Folder Value',
      'TRX Movement',
      'Administration',
      'Client Position',
    ],
    state: 'Crossing state',
    recognition: 'Prospect recognition',
    value: 'File Folder value',
    trx: 'TRX movement',
    administration: 'Administration verification',
    paymentAction: 'Record payment movement',
    pendingTitle: 'Administration verification in progress.',
    pendingDetail:
      'The payment movement is recorded. When Administration verifies it, the File Number appears here. No second purchase is required.',
    confirmedTitle: 'File Number issued.',
    confirmedDetail:
      'The File Number now carries this movement into the Client position. Establish the Client identity to open System Switch.',
    rejectedTitle: 'Verification not completed.',
    rejectedDetail:
      'Administration did not verify this TRX movement. Confirm the transaction details before recording another File Folder movement.',
    clientAction: 'Establish Client Position',
  },

  clientAccess: {
    registerEyebrow: 'Client Crossing',
    registerTitle: 'Establish Client Identity',
    recognizeTitle: 'Recognize File Number',
    recognizeDetail: 'Enter the File Number issued by Administration.',
    detailsTitle: 'Complete Client Position',
    detailsDetail: 'Set the access details attached to this Client File Folder.',
    fileNumber: 'File Number',
    recognized: 'File Number recognized',
    recognizeAction: 'Recognize File Number',
    completeAction: 'Establish Client Position',
    existing: 'Already established?',
    enter: 'Enter Client World',

    loginEyebrow: 'Client Position',
    loginTitle: 'Client Access',
    loginDetail: 'Enter the File Number and password attached to your Client position.',
    password: 'Password',
    loginAction: 'Enter Client World',
    registerAction: 'Establish Client Identity',
  },

  positionAccess: {
    access: 'WEAVE · Position Access',
    administrationAccess: 'WEAVE · Administration Access',
    divider: 'Interaction in Motion',
    clientAccess: 'Client Access',
    chooseTitle: 'Choose Your Position',
    chooseDetail: 'Choose the position you are entering.',
    existing: 'Already have a position?',
    signIn: 'Sign In',
    termsTitle: 'Terms of Participation',
    termsDetail: 'Review the company terms that govern this position.',
    acceptTerms: 'Accept Terms and Continue',
    guidanceTitle: 'Position Guidance',
    guidanceDetail: 'See how this position moves inside WEAVE.',
    identityTitle: 'Establish Position',
  },
} as const
