export type WeaveEnvironmentCopy = {
  key: string
  title: string
  district: string
  purpose: string
  movement: string
  layer: 'world' | 'district' | 'system' | 'interaction'
  world?: 'open-weave' | 'file-folder'
}

export function weaveWorldForPath(pathname:string):'open-weave'|'file-folder'{
  return pathname.startsWith('/client/system-switch')?'file-folder':'open-weave'
}

const exact: Record<string, WeaveEnvironmentCopy> = {
  '/login': {
    key: 'position-entry',
    title: 'WEAVE Position Gate',
    district: 'Presence',
    purpose: 'Enter the WEAVE world through your issued position. Authentication opens continuity; it does not start a disconnected page session.',
    movement: 'Identify position → authenticate → enter role world',
    layer: 'interaction',
  },
  '/register': {
    key: 'position-registration',
    title: 'WEAVE Position Registration',
    district: 'Presence',
    purpose: 'Establish a participant position before entering the shared WEAVE environment.',
    movement: 'Register → establish position → enter world',
    layer: 'interaction',
  },
  '/forgot-password': {
    key: 'access-recovery',
    title: 'Access Recovery Gate',
    district: 'Presence',
    purpose: 'Recover authorized access without breaking continuity with the position already established in WEAVE.',
    movement: 'Identify → recover → return to position',
    layer: 'interaction',
  },
  '/reset-password': {
    key: 'access-reset',
    title: 'Access Reset Gate',
    district: 'Presence',
    purpose: 'Complete secure access recovery, then return directly to the WEAVE environment.',
    movement: 'Verify → reset → re-enter',
    layer: 'interaction',
  },
  '/client': {
    key: 'client-access-point',
    title: 'Client Access Point',
    district: 'Client World',
    purpose: 'The authorized entrance to Client Services and the Client-owned File Folder environment.',
    movement: 'Enter with File Number → authenticate → resume Client world',
    layer: 'world',
  },
  '/client/login': {
    key: 'client-access-gate',
    title: 'Client Access Gate',
    district: 'Client World',
    purpose: 'Authenticate with the issued File Number and secure passkey to reopen the same Client operating environment.',
    movement: 'File Number → passkey → resume world',
    layer: 'interaction',
  },
  '/client/register': {
    key: 'client-registration-gate',
    title: 'Client Registration Gate',
    district: 'Client World',
    purpose: 'Activate authorized Client access against an issued File Number before entering the persistent File Folder world.',
    movement: 'File Number → establish access → enter world',
    layer: 'interaction',
  },
  '/client/presence': {
    key: 'client-presence',
    title: 'Client Presence',
    district: 'Presence',
    purpose: 'The Client orientation environment for understanding the File Folder, value movement, support and ownership of the Client world.',
    movement: 'Recognize position → enter File Folder → build → activate → operate',
    layer: 'district',
  },
  '/client/dashboard': {
    key: 'client-home-world',
    title: 'Client World',
    district: 'Client World',
    purpose: 'The Client arrival ground: one world connecting the File Folder, support, value, loops, enterprise and live systems.',
    movement: 'Arrive → choose district → move → return with changed state',
    layer: 'world',
  },
  '/client/settings': {
    key: 'client-position-settings',
    title: 'Client Position Settings',
    district: 'Client World',
    purpose: 'The Client control environment for secure identity and operating preferences attached to the same Client position.',
    movement: 'Inspect → adjust → confirm → continue',
    layer: 'system',
  },
  '/': {
    key: 'public-world',
    title: 'WEAVE World Entrance',
    district: 'Presence',
    purpose: 'Enter the living WEAVE environment where human presence becomes interaction, work, value, participation and livelihood.',
    movement: 'Arrive → recognize your position → enter the world',
    layer: 'world',
  },
  '/weave': {
    key: 'role-world-return',
    title: 'Role World',
    district: 'Presence',
    purpose: 'Return an authenticated participant to the world belonging to their established WEAVE position.',
    movement: 'Recognize position → return to role world',
    layer: 'world',
  },
  '/presence': {
    key: 'presence-district',
    title: 'Presence District',
    district: 'Presence',
    purpose: 'The district where standing, human presence, record and value remain organized as one continuous layer of the WEAVE world.',
    movement: 'Recognize position → enter place → continue movement',
    layer: 'district',
  },
  '/marketplace': {
    key: 'enterprise-exchange',
    title: 'Enterprise Systems Exchange',
    district: 'Enterprise',
    purpose: 'A live technology market for serious systems, infrastructure and operating capabilities formed through WEAVE.',
    movement: 'Inspect → choose → structure → activate',
    layer: 'district',
  },
  '/wallet': {
    key: 'value-vault',
    title: 'Value Vault',
    district: 'Presence',
    purpose: 'The operating environment for balances, deposits, withdrawals and value movement connected to participation.',
    movement: 'Hold → move → confirm → record',
    layer: 'system',
  },
  '/ledger': {
    key: 'movement-record',
    title: 'Movement Record',
    district: 'Presence',
    purpose: 'The preserved record of value and participation already moving through the WEAVE environment.',
    movement: 'Movement → confirmation → record → continuity',
    layer: 'system',
  },
  '/echo': {
    key: 'echo-board',
    title: 'Echo Board',
    district: 'Enterprise',
    purpose: 'The operating environment for authorized AI amplification, outreach and truthful extension of human movement.',
    movement: 'Authorize → extend → speak → return insight',
    layer: 'system',
  },
  '/arena': {
    key: 'arena-ground',
    title: 'Arena Ground',
    district: 'WEAVE',
    purpose: 'A shared contest environment where participants meet each other through defined rules and recorded outcomes.',
    movement: 'Enter → participate → resolve → record',
    layer: 'district',
  },
  '/casino': {
    key: 'pattern-ground',
    title: 'Pattern Ground',
    district: 'WEAVE',
    purpose: 'A user-versus-system environment for defined patterns, stakes, outcomes and recorded movement.',
    movement: 'Enter → interact → resolve → record',
    layer: 'district',
  },
  '/event': {
    key: 'flame-event-loop-one',
    title: 'Flame Event · Loop 1',
    district: 'Presence',
    purpose: 'The shared Burning River event ground for Agent, Bridger and Administration positions inside Company Loop 1.',
    movement: 'Arrive → recognize position → participate → continue',
    layer: 'district',
  },
  '/company/loops': {
    key: 'company-loops',
    title: 'Company Loops',
    district: 'Presence',
    purpose: 'The operating environment for recurring company movement, stages and participation across positions.',
    movement: 'See the loop → enter position → move → preserve',
    layer: 'district',
  },
  '/profiles': {
    key: 'presence-field',
    title: 'Presence Field',
    district: 'Presence',
    purpose: 'A living field of people and positions already participating inside WEAVE.',
    movement: 'Discover → recognize → connect',
    layer: 'district',
  },
  '/search': {
    key: 'cadence-field',
    title: 'Human Cadence Field',
    district: 'Presence',
    purpose: 'Search the WEAVE field by the movement, presence and participation people make visible.',
    movement: 'Notice → recognize → connect',
    layer: 'district',
  },
  '/communications': {
    key: 'direct-communication',
    title: 'Direct Communication',
    district: 'Presence',
    purpose: 'Authorized direct communication between connected WEAVE positions, Prospects and Clients.',
    movement: 'Select relationship → speak directly → preserve continuity',
    layer: 'interaction',
  },
  '/settings': {
    key: 'role-settings',
    title: 'Settings',
    district: 'Presence',
    purpose: 'Manage identity, password and the current signed-in role session.',
    movement: 'Review identity → update → sign out or continue',
    layer: 'system',
  },
  '/weave/standing': {
    key: 'standing-field',
    title: 'Standing Field',
    district: 'Presence',
    purpose: 'A shared view of current position, participation and visible movement across the environment.',
    movement: 'Position → participation → standing',
    layer: 'district',
  },
  '/admin/visual-systems': {
    key: 'administration-visual-systems',
    title: 'Visual Systems Workshop',
    district: 'Institution',
    purpose: 'The Administration runtime-design environment for registered WEAVE artifacts, live publication, placement control and rollback.',
    movement: 'Draft → preview → publish → observe → roll back when needed',
    layer: 'system',
  },
  '/admin/environment-organizer': {
    key: 'administration-environment-organizer',
    title: 'Environment Organizer',
    district: 'Institution',
    purpose: 'Administration control for withdrawing, restoring and ordering registered pages and cards while preserving source and records.',
    movement: 'Inspect → withdraw or restore → reorder → observe',
    layer: 'system',
  },
}

const prefix: Array<[string, WeaveEnvironmentCopy]> = [
  ['/district', {
    key: 'role-district',
    title: 'Role District',
    district: 'Role World',
    purpose: 'A role-aware district that organizes only the places belonging to the authenticated position.',
    movement: 'Enter district → choose place → operate → return to role world',
    layer: 'district',
  }],

  ['/agent/bridge-radiance', {
    key: 'agent-radiance-station',
    title: 'Bridge Radiance · Stability Station',
    district: 'Bridge Radiance',
    purpose: 'The support station where an assigned Agent may participate with Prospects belonging to that Agent’s Bridgers.',
    movement: 'Observe assigned movement → support → clarify → return continuity',
    layer: 'interaction',
  }],
  ['/admin/bridge-radiance', {
    key: 'administration-radiance-station',
    title: 'Bridge Radiance · Administration Station',
    district: 'Bridge Radiance',
    purpose: 'The institutional interaction station for authorized Administration participation in active Prospect movement.',
    movement: 'Observe → interact when required → preserve record → continue',
    layer: 'interaction',
  }],

  ['/stream', {
    key: 'public-stream-network',
    title: 'WEAVE Stream Network',
    district: 'Enterprise',
    purpose: 'The public broadcast world where completed Client Streaming Open Gates become channels anyone can visit.',
    movement: 'Enter network → choose channel → watch live or replay → continue into connected Client worlds',
    layer: 'world',
  }],
  ['/enterprise', {
    key: 'public-enterprise-territory',
    title: 'WEAVE Enterprise Territory',
    district: 'Enterprise',
    purpose: 'The public territory for Administration-approved Lord/Lady enterprises that have completed Enterprise Door construction.',
    movement: 'Enter territory → inspect enterprise → enter systems, market or stream → participate',
    layer: 'world',
  }],
  ['/market', {
    key: 'public-client-market',
    title: 'WEAVE Client Market',
    district: 'Enterprise',
    purpose: 'The public district where constructed Client Customer Doors, storefronts and Market Halls can be visited without a WEAVE account.',
    movement: 'Enter market → visit store → inspect offer → purchase or request',
    layer: 'world',
  }],
  ['/client/system-switch', {
    key: 'client-file-folder',
    title: 'Main File Folder · 4D Operating World',
    district: 'System Switch',
    purpose: 'The Client-owned persistent environment where workshops, materials, boosts, builds, live systems, customers and enterprise movement stay together.',
    movement: 'Recognize → build → activate → operate → continue',
    layer: 'world',
  }],
  ['/client/district', {
    key: 'client-role-district',
    title: 'Client District',
    district: 'Client World',
    purpose: 'An organized Client district containing the places that perform one class of Client movement.',
    movement: 'Presence → district → place → changed state',
    layer: 'district',
  }],

  ['/client/loops', {
    key: 'client-loops',
    title: 'Loop Field',
    district: 'Client World',
    purpose: 'The Client view of company loops, participation stages and active movement connected to the File Folder.',
    movement: 'See → enter → participate → preserve',
    layer: 'district',
  }],
  ['/client/event', {
    key: 'client-event-ground',
    title: 'Flame Event · Loop 1',
    district: 'Client World',
    purpose: 'A live event environment where the Client participates inside current WEAVE movement.',
    movement: 'Arrive → participate → carry movement forward',
    layer: 'district',
  }],
  ['/client/deposit', {
    key: 'client-value-entry',
    title: 'Client Value Entry',
    district: 'Client World',
    purpose: 'The Client environment for moving value into the operating world and confirming its arrival.',
    movement: 'Prepare → deposit → verify → use',
    layer: 'system',
  }],
  ['/client/withdraw', {
    key: 'client-value-release',
    title: 'Client Value Release',
    district: 'Client World',
    purpose: 'The Client environment for requesting controlled release of available value from the operating world.',
    movement: 'Request → verify → release → record',
    layer: 'system',
  }],
  ['/client/chat', {
    key: 'client-support-room',
    title: 'Client Support Room',
    district: 'Bridge',
    purpose: 'A direct interaction environment between the Client and authorized WEAVE support positions.',
    movement: 'Speak → clarify → act → preserve continuity',
    layer: 'interaction',
  }],
  ['/bridger/presence', {
    key: 'bridger-presence',
    title: 'Bridger Presence',
    district: 'Presence',
    purpose: 'The Bridger orientation environment for understanding Prospect movement, crossing tools, value continuity and authorized outreach.',
    movement: 'Recognize position → acquire Prospect → connect → cross',
    layer: 'district',
  }],

  ['/bridger/bridge-ai', {
    key: 'bridge-ai-crossing',
    title: 'Bridge AI Crossing',
    district: 'Bridge',
    purpose: 'The intelligent crossing environment that helps move a prospect toward Client entry and then supports Client continuity.',
    movement: 'Interact → reveal → recognize → cross',
    layer: 'interaction',
  }],

  ['/bridger/numbers', {
    key: 'bridger-number-bay',
    title: 'Worldwide Number Bay',
    district: 'Bridge',
    purpose: 'The authenticated WhatsApp-number environment where Bridgers purchase available numbers and receive verification movement through WEAVE.',
    movement: 'Select → purchase → receive code or pending state → verify',
    layer: 'system',
  }],
  ['/bridger/subscription', {
    key: 'bridger-continuance',
    title: 'Bridger Continuance',
    district: 'Bridge',
    purpose: 'The environment that keeps Bridger participation active and connected to company movement.',
    movement: 'Check standing → renew when due → continue',
    layer: 'system',
  }],
  ['/agent/presence', {
    key: 'agent-presence',
    title: 'Agent Presence',
    district: 'Presence',
    purpose: 'The orientation environment for understanding the Agent position before entering Agility or Commission movement.',
    movement: 'Recognize position → understand functions → move Agility or review commission',
    layer: 'district',
  }],
  ['/agent/channels', {
    key: 'agent-channel-field',
    title: 'Agent Channel Field',
    district: 'Support',
    purpose: 'The company-position environment where Agents enter authorized channels and working functions.',
    movement: 'Request → enter → work → preserve',
    layer: 'district',
  }],
  ['/agent/commissions', {
    key: 'agent-continuance',
    title: 'Agent Commissions',
    district: 'Agent Movement',
    purpose: 'The Agent value environment for Prospect purchase shares, verified Client File Folder shares and the resulting commission record.',
    movement: 'Prospect purchase → Agent share · File Folder crossing → Agent share → record',
    layer: 'system',
  }],
  ['/district', {
    key: 'role-district',
    title: 'Role District',
    district: 'Open WEAVE World',
    purpose: 'A role-specific district that contains related places without scattering every function across the open world.',
    movement: 'World → district → place → return with changed state',
    layer: 'district',
  }],
  ['/admin/dashboard', {
    key: 'administration-world',
    title: 'Administration World',
    district: 'Institution',
    purpose: 'The institutional environment from which WEAVE authority, verification, infrastructure and company movement are coordinated.',
    movement: 'Observe → authorize → verify → keep the world moving',
    layer: 'world',
  }],

  ['/admin/', {
    key: 'administration-system',
    title: 'Administration System',
    district: 'Institution',
    purpose: 'A live institutional system inside the Administration world. Changes here affect real WEAVE operations and participant movement.',
    movement: 'Inspect → act → verify → preserve continuity',
    layer: 'system',
  }],
  ['/agility', {
    key: 'agility-market',
    title: 'Agility Distribution Ground',
    district: 'Enterprise',
    purpose: 'The operating environment for Agility food distribution, Agent participation and real-world delivery.',
    movement: 'Order → distribute → sell → record return',
    layer: 'district',
  }],
  ['/company-chat', {
    key: 'company-guidance',
    title: 'Company Guidance Room',
    district: 'Bridge',
    purpose: 'The company interaction environment for position-specific guidance and operational clarification.',
    movement: 'Ask → clarify → act → continue',
    layer: 'interaction',
  }],
]

export function resolveWeaveEnvironment(pathname: string): WeaveEnvironmentCopy {
  if (exact[pathname]) return exact[pathname]

  const matched = prefix.find(([route]) =>
    route.endsWith('/') ? pathname.startsWith(route) : pathname === route || pathname.startsWith(route + '/')
  )
  if (matched) return matched[1]

  return {
    key: 'weave-world',
    title: 'WEAVE Operating Environment',
    district: 'Presence',
    purpose: 'A live part of the WEAVE world where interaction changes state and movement continues across connected systems.',
    movement: 'Notice → recognize → act → move',
    layer: 'system',
  }
}
