export type WeaveRole='client'|'agent'|'bridger'|'admin'
export type WeaveDistrictKey='presence'|'position'|'bridge'|'enterprise'|'participation'|'administration'

export type WeaveRolePlace={
  label:string
  detail:string
  href:string
  daily?:boolean
}

export type WeaveRoleDistrict={
  key:WeaveDistrictKey
  name:string
  subtitle:string
  purpose:string
  accent:string
  places:WeaveRolePlace[]
}

// Single role catalog used by Bridge Plaza and all operating rooms.
const byRole:Record<WeaveRole,WeaveRoleDistrict[]>={
  "agent": [
    {
      "key": "presence",
      "name": "Presence",
      "subtitle": "UNDERSTAND YOUR POSITION",
      "purpose": "Understand the Agent position before entering its working functions.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Agent Presence",
          "href": "/agent/presence",
          "detail": "Understand the Agent position, Agility movement and commission return.",
          "daily": true
        }
      ]
    },
    {
      "key": "position",
      "name": "Agent Movement",
      "subtitle": "AGILITY + COMMISSIONS",
      "purpose": "Carry real distribution through Agility and receive commissions from qualifying Bridger Prospect purchases.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Agility",
          "href": "/agility",
          "detail": "Order, receive, distribute and record Agility movement.",
          "daily": true
        },
        {
          "label": "Commissions",
          "href": "/agent/commissions",
          "detail": "See commissions generated by qualifying Bridger Prospect purchases.",
          "daily": true
        }
      ]
    }
  ],
  "bridger": [
    {
      "key": "presence",
      "name": "Presence",
      "subtitle": "UNDERSTAND YOUR POSITION",
      "purpose": "Understand the Bridger position and the movement it carries before entering Bridge tools.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Bridger Presence",
          "href": "/bridger/presence",
          "detail": "Understand prospect movement, Bridge AI, Number Bay, Echo, Presences and value continuity.",
          "daily": true
        }
      ]
    },
    {
      "key": "bridge",
      "name": "Bridge Movement",
      "subtitle": "PROSPECT → CROSSING",
      "purpose": "Acquire Prospects, operate authorized outreach and carry people toward Client crossing.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Bridge AI",
          "href": "/bridger/bridge-ai",
          "detail": "Use and maintain the Bridge AI crossing path.",
          "daily": true
        },
        {
          "label": "Prospect Market",
          "href": "/weave/market/prospects",
          "detail": "Claim the daily Prospect or purchase Prospect movement.",
          "daily": true
        },
        {
          "label": "Number Bay",
          "href": "/bridger/numbers",
          "detail": "Purchase authenticated numbers and follow delivery and verification.",
          "daily": true
        },
        {
          "label": "Echo",
          "href": "/echo",
          "detail": "Operate authorized AI-assisted outreach and amplification."
        },
        {
          "label": "Presences",
          "href": "/profiles",
          "detail": "See people and active Presences inside WEAVE."
        }
      ]
    },
    {
      "key": "participation",
      "name": "Value",
      "subtitle": "DEPOSIT + WITHDRAWAL",
      "purpose": "Keep Bridger value movement available without turning value controls into the identity of the role.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Deposit & Withdrawal",
          "href": "/wallet/deposit-withdraw",
          "detail": "Deposit Flame Coin value or request withdrawal.",
          "daily": true
        }
      ]
    }
  ],
  "client": [
    {
      "key": "presence",
      "name": "Presence",
      "subtitle": "UNDERSTAND YOUR WORLD",
      "purpose": "Understand the Client position, the File Folder and how work, value and support continue through the Client world.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Client Presence",
          "href": "/client/presence",
          "detail": "Understand your Client world, File Folder, value movement and support paths.",
          "daily": true
        }
      ]
    },
    {
      "key": "position",
      "name": "File Folder",
      "subtitle": "BUILD + OPERATE",
      "purpose": "Enter System Switch, build systems and operate the Client File Folder.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "System Switch · File Folder",
          "href": "/client/system-switch",
          "detail": "Build and operate systems, your store and Customer Door.",
          "daily": true
        },
        {
          "label": "Enterprise Systems",
          "href": "/marketplace",
          "detail": "Explore enterprise-scale systems for your work."
        },
        {
          "label": "Settings",
          "href": "/client/settings",
          "detail": "Manage your Client identity and account."
        }
      ]
    },
    {
      "key": "participation",
      "name": "Funds & Records",
      "subtitle": "VALUE + EVIDENCE",
      "purpose": "Fund work, release available value and preserve financial evidence.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Deposit",
          "href": "/client/deposit",
          "detail": "Fund your Client work."
        },
        {
          "label": "Withdraw",
          "href": "/client/withdraw",
          "detail": "Request controlled release of available value."
        },
        {
          "label": "Wallet",
          "href": "/wallet",
          "detail": "See balances and value movement."
        },
        {
          "label": "Records",
          "href": "/ledger",
          "detail": "See preserved payment and earning history."
        },
        {
          "label": "Receipts",
          "href": "/receipts",
          "detail": "See payment, purchase and withdrawal receipts."
        }
      ]
    },
    {
      "key": "bridge",
      "name": "Support",
      "subtitle": "HUMAN CONTINUITY",
      "purpose": "Reach the authorized WEAVE position needed for the next Client movement.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Your Bridger",
          "href": "/client/chat/bridger",
          "detail": "Contact Your Bridger for crossing and continuity support."
        },
        {
          "label": "Mandate",
          "href": "/client/chat/mandate",
          "detail": "Contact Mandate for operational support."
        },
        {
          "label": "Forensics",
          "href": "/client/chat/forensic",
          "detail": "Contact Forensics for value and verification support."
        },
        {
          "label": "Attorney",
          "href": "/client/chat/lawyer",
          "detail": "Contact Attorney for legal support."
        },
        {
          "label": "Administration",
          "href": "/client/chat/admin",
          "detail": "Contact Administration for institutional support."
        }
      ]
    }
  ],
  "admin": [
    {
      "key": "position",
      "name": "People",
      "subtitle": "PEOPLE",
      "purpose": "Manage Agents, Bridgers and Clients.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "User Management",
          "detail": "Manage users, departments, roles and Bridger-to-Agent assignment.",
          "href": "/admin/control-center#users"
        },
        {
          "label": "Department Authorization",
          "detail": "Open the embedded departmental authorization component.",
          "href": "/admin/control-center#departmental"
        },
        {
          "label": "Bridger Operations",
          "detail": "Open Bridger operations, standing and exemption controls.",
          "href": "/admin/control-center#bridgers"
        },
        {
          "label": "Departmental Registration",
          "detail": "Departmental codes and company placement.",
          "href": "/admin/departmental-registration"
        },
        {
          "label": "Agent Channel Requests",
          "detail": "Approve Agent service channels.",
          "href": "/admin/agent-channels"
        },
        {
          "label": "Subscriptions",
          "detail": "Subscription and continuance administration.",
          "href": "/admin/subscriptions"
        }
      ]
    },
    {
      "key": "presence",
      "name": "Finance",
      "subtitle": "FINANCE",
      "purpose": "Finance.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Receipts",
          "detail": "Receipts issued for Administration value movement.",
          "href": "/receipts"
        },
        {
          "label": "Administration Wallet",
          "detail": "Platform balances, deposit, withdrawal and participation controls.",
          "href": "/admin/control-center#wallet"
        },
        {
          "label": "OPay Deposit Review",
          "detail": "Review and decide pending OPay deposits.",
          "href": "/admin/control-center#deposits"
        },
        {
          "label": "Withdrawal Review",
          "detail": "Review and decide pending withdrawal requests.",
          "href": "/admin/control-center#withdrawals"
        },
        {
          "label": "Client Deposits",
          "detail": "Review Client funding requests.",
          "href": "/admin/client-deposits"
        },
        {
          "label": "Client Vaults",
          "detail": "Administer Client vault movement.",
          "href": "/admin/client-vault"
        },
        {
          "label": "Payments",
          "detail": "Institutional payment administration.",
          "href": "/admin/payments"
        },
        {
          "label": "Reserve",
          "href": "/fund-wall",
          "detail": "Institutional reserve and fund position."
        },
        {
          "label": "Wallet",
          "href": "/wallet",
          "detail": "Administration balances."
        },
        {
          "label": "Records",
          "href": "/ledger",
          "detail": "Administration value history."
        }
      ]
    },
    {
      "key": "bridge",
      "name": "Operations",
      "subtitle": "OPERATIONS",
      "purpose": "Operations.",
      "accent": "#7dd3fc",
      "places": [
        {"label":"Enterprise Systems Exchange","href":"/marketplace","detail":"Explore the live enterprise systems market."},
        {
          "label": "Human Cadences",
          "detail": "Find people through their recorded participation and movement.",
          "href": "/search"
        },
        {
          "label": "Presences",
          "detail": "See people and their place in the WEAVE.",
          "href": "/profiles"
        },
        {
          "label": "Bridge Plaza",
          "detail": "Enter the shared WEAVE world and Client support entrance.",
          "href": "/weave"
        },
        {
          "label": "Standing",
          "detail": "See shared WEAVE standing and position.",
          "href": "/weave/standing"
        },
        {
          "label": "Administration Control Center",
          "detail": "Open the preserved dense Administration center and its live embedded components.",
          "href": "/admin/control-center"
        },
        {
          "label": "File Number Registry",
          "detail": "Open the existing File Number Engine component and registry history.",
          "href": "/admin/control-center#fne"
        },
        {
          "label": "Client Communications",
          "detail": "Open the existing Client communications panel.",
          "href": "/admin/control-center#clients"
        },
        {
          "label": "TRON Deposit Review",
          "detail": "Review and decide pending TRON deposits.",
          "href": "/admin/control-center#tron"
        },
        {
          "label": "Bridge Deposit Review",
          "detail": "Review Bridge AI and File Folder deposit movement.",
          "href": "/admin/control-center#bridge"
        },
        {
          "label": "Announcements",
          "detail": "Send role-targeted WEAVE announcements and update notices.",
          "href": "/admin/control-center#announcements"
        },
        {
          "label": "File Number Engine",
          "detail": "Issue and administer Client File Numbers.",
          "href": "/admin/file-number-engine"
        },
        {
          "label": "Enterprise Dream",
          "detail": "Lord/Lady elevation and enterprise plans.",
          "href": "/admin/enterprise-dream"
        },
        {
          "label": "Prospect Engine",
          "detail": "Create and organize Prospect movement.",
          "href": "/admin/prospect-engine"
        },
        {
          "label": "Bridge Templates",
          "detail": "Control Bridge AI crossing templates.",
          "href": "/admin/bridge-templates"
        },
        {
          "label": "Bridge AI Continuity",
          "detail": "Review Client Bridge AI support insight.",
          "href": "/admin/bridge-ai"
        },
        {
          "label": "Fulfillment Agent",
          "detail": "Authorized outreach and delivery movement.",
          "href": "/admin/outreach"
        },
        {
          "label": "Agility Fulfillment",
          "detail": "Administer Agility orders and fulfillment.",
          "href": "/admin/agility"
        },
        {
          "label": "Administration World",
          "detail": "Institutional arrival world and daily authority state.",
          "href": "/admin/dashboard"
        },
        {
          "label": "Administration Operating Room",
          "detail": "Enter administrative systems and controls.",
          "href": "/admin/functions"
        },
        {
          "label": "WhatsApp Number Engine",
          "detail": "Number Bay stock, delivery and verification authority.",
          "href": "/admin/bridger-numbers"
        }
      ]
    },
    {
      "key": "administration",
      "name": "Workshops",
      "subtitle": "WORKSHOPS",
      "purpose": "Workshops.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Administration Workshops",
          "detail": "Developer, Authority, AI Registry, EIGHT Dev Core and event workshop access.",
          "href": "/admin/control-center#workshops"
        },
        {
          "label": "EIGHT AI",
          "detail": "Direct Administration interaction with EIGHT and its Scroll.",
          "href": "/admin/control-center#eight"
        },
        {
          "label": "Client Build Catalog",
          "detail": "Control Client build systems and pricing.",
          "href": "/admin/client-build-catalog"
        },
        {
          "label": "Authority Workshop",
          "detail": "Institutional structures and authority.",
          "href": "/authority/workshops"
        },
        {
          "label": "Development Foundry",
          "detail": "Eight and persistent coding agents developing WEAVE against the real source.",
          "href": "/admin/development-agents"
        },
        {
          "label": "Developer Workshop",
          "detail": "Develop and refine WEAVE systems.",
          "href": "/admin/dev-workshop"
        },
        {
          "label": "Origin Systems",
          "detail": "Inspect origin runtime and system foundations.",
          "href": "/admin/origin-systems"
        },
        {
          "label": "Enterprise Systems Workshop",
          "detail": "Million-scale software, hardware and infrastructure systems.",
          "href": "/admin/enterprise-systems"
        },
        {
          "label": "Infrastructure",
          "detail": "Cloud Run, runtime and maintenance control.",
          "href": "/admin/infrastructure"
        },
        {
          "label": "Visual Systems \u00b7 Interaction in Motion",
          "detail": "Govern live Flame, River, route current, emergence and visual runtime with history and rollback.",
          "href": "/admin/visual-systems"
        },
        {
          "label": "Environment Organizer",
          "detail": "Withdraw, restore and reorder registered cards and pages without deleting source.",
          "href": "/admin/environment-organizer"
        },
        {
          "label": "Loop Workshop",
          "detail": "Create and publish company loops.",
          "href": "/admin/loop-workshop"
        },
        {
          "label": "DJ Workshop",
          "detail": "System sound and live atmosphere.",
          "href": "/admin/dj-workshop"
        },
        {
          "label": "Ad Workshop",
          "detail": "Role-targeted communication without deployment.",
          "href": "/admin/ad-workshop"
        }
      ]
    },
    {
      "key": "participation",
      "name": "Communication & Events",
      "subtitle": "COMMUNICATION & EVENTS",
      "purpose": "Communication & Events.",
      "accent": "#7dd3fc",
      "places": [
        {
          "label": "Company Loops",
          "detail": "Shared company movement visible across WEAVE.",
          "href": "/company/loops"
        },
        {
          "label": "Company Guidance",
          "detail": "Use the shared company clarification channel.",
          "href": "/company-chat"
        },
        {
          "label": "Private Lounge",
          "detail": "Enter private WEAVE communication.",
          "href": "/lounge?view=private"
        },
        {
          "label": "Lounge",
          "detail": "Enter the shared WEAVE communication space.",
          "href": "/lounge"
        },
        {
          "label": "Echo",
          "detail": "Use the WEAVE Echo surface.",
          "href": "/echo"
        },
        {
          "label": "Contest",
          "detail": "Enter shared participant contest movement.",
          "href": "/arena"
        },
        {
          "label": "Pattern",
          "detail": "Enter shared system pattern play.",
          "href": "/casino"
        },
        {
          "label": "Stream",
          "detail": "Enter the shared WEAVE media stream.",
          "href": "/video-feed"
        },
        {
          "label": "Loop 1 Ground",
          "detail": "Enter the current shared WEAVE event ground.",
          "href": "/event"
        },
        {
          "label": "Message Hub",
          "detail": "People, Client and staff communication.",
          "href": "/admin/hub"
        },
        {
          "label": "Client Messages",
          "detail": "Direct Client communication records.",
          "href": "/admin/client-messages"
        },
        {
          "label": "Campaign Flame",
          "detail": "Campaign construction and coordinated movement.",
          "href": "/admin/campaign-flame"
        },
        {
          "label": "Flame Event \u00b7 Loop 1",
          "detail": "Event-world control and opening movement.",
          "href": "/admin/flame-event"
        }
      ]
    }
  ]
}

export function normalizeWeaveRole(role?:string|null):WeaveRole{
  if(role==='admin'||role==='agent'||role==='bridger'||role==='client')return role
  return 'client'
}

export function getRoleDistricts(role?:string|null){
  return byRole[normalizeWeaveRole(role)]
}

export function getRoleDistrict(role:string|undefined|null,key:string){
  return getRoleDistricts(role).find(district=>district.key===key)||null
}

export function getRolePlaces(role?:string|null){
  return getRoleDistricts(role).flatMap(district=>district.places.map(place=>({...place,district:district.name})))
}
