'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { BatteryCharging,Clock3,Plus,RefreshCw,ShieldCheck } from 'lucide-react'
import { getAuthHeaders } from '@/lib/auth-client'
import { toast } from 'sonner'
import { WeaveSystemRoom } from '@/components/world/weave-system-room'

export default function AdminBridgerNumbersPage(){
 const [numbers,setNumbers]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true)
 const [form,setForm]=useState({phone:'',country:'Nigeria',providerReference:'',acquisitionCost:'',priceFlameCoin:'',notes:''})
 const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/admin/bridger-numbers',{headers:getAuthHeaders(),cache:'no-store'}),fetch('/api/bridger/number-verifications',{headers:getAuthHeaders(),cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error);if(!b.ok)throw new Error(y.error);setNumbers(x.numbers||[]);setRequests(y.requests||[])}catch(e:any){toast.error(e.message||'Unable to load Number Engine')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const add=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin/bridger-numbers',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return toast.error(d.error||'Unable to load number');toast.success('Number loaded into WEAVE stock');setForm({...form,phone:'',providerReference:'',acquisitionCost:'',notes:''});void load()}
 const respond=async(id:string,status:string)=>{const message=status==='pending'?window.prompt('Why is the verification pending?')||'':'';const code=status==='code_ready'?window.prompt('Enter the received verification code')||'':'';if(status==='pending'&&!message)return;if(status==='code_ready'&&!code)return;const r=await fetch('/api/bridger/number-verifications',{method:'PATCH',headers:getAuthHeaders(),body:JSON.stringify({id,status,message,code})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Update failed');toast.success(status==='code_ready'?'Code delivered to Bridger':'Request remains pending');void load()}
 const fields=[{key:'phone',label:'Number',placeholder:'+2348012345678',type:'text'},{key:'country',label:'Country',placeholder:'Nigeria',type:'text'},{key:'providerReference',label:'Provider reference',placeholder:'',type:'text'},{key:'acquisitionCost',label:'Administration acquisition cost',placeholder:'0',type:'number'},{key:'priceFlameCoin',label:'Bridger price · Flame Coin',placeholder:'0',type:'number'},{key:'notes',label:'Administration notes',placeholder:'',type:'text'}] as const
 const pending=requests.filter(r=>['requested','pending'].includes(r.status))
 const available=numbers.filter(n=>n.status==='available'&&!n.assigned_to).length
 const assigned=numbers.filter(n=>n.assigned_to).length

 const left=<>
  <section className="rounded-3xl border border-emerald-300/15 bg-emerald-400/[.035] p-4"><BatteryCharging className="h-5 w-5 text-emerald-300"/><p className="mt-3 text-sm font-black text-white">Inventory authority</p><p className="mt-2 text-xs leading-5 text-slate-400">Administration loads provider stock, sets the internal acquisition cost and publishes only the Flame Coin sale value to Bridgers.</p></section>
  <section className="rounded-3xl border border-white/10 bg-black/20 p-4"><p className="text-[9px] font-black uppercase text-slate-500">Engine state</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border border-white/10 p-2"><p className="text-lg font-black text-emerald-200">{available}</p><p className="text-[7px] uppercase text-slate-500">Ready</p></div><div className="rounded-xl border border-white/10 p-2"><p className="text-lg font-black text-sky-200">{assigned}</p><p className="text-[7px] uppercase text-slate-500">Assigned</p></div><div className="rounded-xl border border-white/10 p-2"><p className="text-lg font-black text-amber-200">{pending.length}</p><p className="text-[7px] uppercase text-slate-500">Codes</p></div></div></section>
 </>

 const center=<>
  <div className="flex items-end justify-between gap-3 border-b border-white/10 pb-4"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-emerald-300">Stock loading station</p><h2 className="mt-1 text-xl font-black text-white">Load a number battery</h2><p className="mt-2 text-xs text-slate-400">Internal acquisition cost stays here. Bridger-facing value is Flame Coin only.</p></div><button onClick={()=>void load()} aria-label="Refresh Administration Number Engine" className="rounded-xl border border-white/10 p-2"><RefreshCw className={`h-4 w-4 text-slate-400 ${loading?'animate-spin':''}`}/></button></div>
  <form onSubmit={add} className="mt-4 grid gap-3 sm:grid-cols-2">{fields.map(f=><label key={f.key} className={f.key==='notes'?'sm:col-span-2':'block'}><span className="text-[9px] font-black uppercase text-slate-500">{f.label}</span><input type={f.type} step={f.type==='number'?'any':undefined} min={f.type==='number'?'0':undefined} value={(form as any)[f.key]} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))} placeholder={f.placeholder} className="mt-1 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-white"/></label>)}<button data-presence-output="Load number battery into WEAVE inventory" className="sm:col-span-2 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-300 p-3 text-xs font-black uppercase tracking-wider text-slate-950"><Plus className="h-4 w-4"/>Load battery</button></form>
  <div className="mt-6 border-t border-white/10 pt-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Administration inventory</p><h2 className="mt-1 text-xl font-black text-white">Battery stock</h2></div>
  <div className="mt-4 space-y-2">{loading?<p className="text-sm text-slate-500">Synchronizing stock…</p>:numbers.length===0?<p className="rounded-xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No numbers loaded.</p>:numbers.map(n=><article key={n.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-mono font-black text-white">{n.phone_e164}</p><p className="mt-1 text-[9px] font-black uppercase text-slate-500">Aphone · {n.country} · {n.status}{n.assigned_name?' · '+n.assigned_name:''}</p>{n.provider_reference&&<p className="mt-1 text-[9px] text-slate-600">Provider ref · {n.provider_reference}</p>}</div><div className="grid min-w-[240px] grid-cols-2 gap-2 text-right"><div className="rounded-xl border border-sky-300/10 bg-sky-400/[.025] p-3"><p className="text-[8px] font-black uppercase text-sky-300">Bridger value</p><p className="mt-1 text-sm font-black text-white">{Number(n.price_flame_coin).toLocaleString()} FC</p></div><div className="rounded-xl border border-amber-300/10 bg-amber-400/[.025] p-3"><p className="text-[8px] font-black uppercase text-amber-300">Acquisition cost</p><p className="mt-1 text-sm font-black text-amber-100">{n.acquisition_cost==null?'Not set':Number(n.acquisition_cost).toLocaleString()}</p></div></div></div></article>)}</div>
 </>

 const right=<>
  <section className="max-h-[520px] overflow-y-auto rounded-3xl border border-amber-300/15 bg-amber-400/[.025] p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-amber-300">Verification dock</p><p className="mt-1 text-sm font-black text-white">{pending.length} waiting</p></div><Clock3 className="h-4 w-4 text-amber-300"/></div><div className="mt-3 space-y-2">{pending.length===0?<p className="text-xs text-slate-500">No verification movement waiting.</p>:pending.map(r=><article key={r.id} className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="font-mono text-xs font-black text-white">{r.phone_e164}</p><p className="mt-1 text-[9px] text-slate-500">{r.bridger_name} · {r.method.toUpperCase()} · {r.status}</p><p className="mt-1 text-[9px] text-amber-300">Deadline {new Date(r.deadline_at).toLocaleTimeString()}</p>{r.admin_message&&<p className="mt-2 text-[9px] text-slate-400">{r.admin_message}</p>}<div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>void respond(r.id,'pending')} className="rounded-lg border border-amber-300/20 px-2 py-1.5 text-[8px] font-black text-amber-300">Pending</button><button onClick={()=>void respond(r.id,'code_ready')} className="rounded-lg bg-emerald-300 px-2 py-1.5 text-[8px] font-black text-slate-950">Send code</button></div></article>)}</div></section>
  <Link href="/admin/functions" className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-xs font-black text-white"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300"/>Administration Operating Room</span></Link>
 </>

 return <WeaveSystemRoom roomKey="administration-number-engine" eyebrow="Administration · Number Authority" title="Number Engine Control Bay" detail="Provider stock, acquisition cost, Bridger Flame Coin pricing and verification fulfillment operate here as one Administration system. Internal acquisition data never crosses into the Bridger view." tone="emerald" left={left} center={center} right={right} pulse={pending.length?'Verification requests waiting':'Number Engine synchronized'}/>
}
