'use client'
import { useEffect,useState } from 'react'
import { getAuthHeaders } from '@/lib/auth-client'
import { Plus,RefreshCw,BatteryCharging,Clock3 } from 'lucide-react'
import { toast } from 'sonner'
export default function AdminBridgerNumbersPage(){
 const [numbers,setNumbers]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true)
 const [form,setForm]=useState({phone:'',country:'Nigeria',providerReference:'',acquisitionCost:'',priceFlameCoin:'',notes:''})
 const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/admin/bridger-numbers',{headers:getAuthHeaders(),cache:'no-store'}),fetch('/api/bridger/number-verifications',{headers:getAuthHeaders(),cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error);if(!b.ok)throw new Error(y.error);setNumbers(x.numbers||[]);setRequests(y.requests||[])}catch(e:any){toast.error(e.message||'Unable to load Number Engine')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const add=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin/bridger-numbers',{method:'POST',headers:getAuthHeaders(),body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return toast.error(d.error||'Unable to load Aphone number');toast.success('Aphone number loaded into stock');setForm({...form,phone:'',providerReference:'',acquisitionCost:'',notes:''});void load()}
 const respond=async(id:string,status:string)=>{const message=status==='pending'?window.prompt('Why is the Aphone code pending?')||'':'';const code=status==='code_ready'?window.prompt('Enter the code received from Aphone')||'':'';if(status==='pending'&&!message)return;if(status==='code_ready'&&!code)return;const r=await fetch('/api/bridger/number-verifications',{method:'PATCH',headers:getAuthHeaders(),body:JSON.stringify({id,status,message,code})}),d=await r.json();if(!r.ok)return toast.error(d.error||'Update failed');toast.success(status==='code_ready'?'Code delivered to Bridger':'Request marked pending');void load()}
 const fields=[
  {key:'phone',label:'Number',placeholder:'+2348012345678',type:'text'},
  {key:'country',label:'Country',placeholder:'Nigeria',type:'text'},
  {key:'providerReference',label:'Provider reference',placeholder:'',type:'text'},
  {key:'acquisitionCost',label:'Administration acquisition cost',placeholder:'0',type:'number'},
  {key:'priceFlameCoin',label:'Bridger price · Flame Coin',placeholder:'0',type:'number'},
  {key:'notes',label:'Administration notes',placeholder:'',type:'text'},
 ] as const
 return <main className="mx-auto max-w-7xl p-4 md:p-7"><header className="rounded-[2rem] border border-emerald-300/15 bg-[#03120f]/80 p-6"><p className="text-[9px] font-black uppercase tracking-[.24em] text-emerald-300">Administration · Aphone Stock</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black text-white"><BatteryCharging/>Bridger Number Engine</h1><p className="mt-3 text-sm text-slate-400">Load Aphone numbers like stock. Acquisition cost remains Administration-only. Bridgers see only the Flame Coin sale value.</p></header>
 <div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><form onSubmit={add} className="space-y-3 rounded-[1.6rem] border border-white/10 bg-black/30 p-5"><h2 className="font-black text-white">Load Aphone number</h2>{fields.map(f=><label key={f.key} className="block"><span className="text-[9px] font-black uppercase text-slate-500">{f.label}</span><input type={f.type} step={f.type==='number'?'any':undefined} min={f.type==='number'?'0':undefined} value={(form as any)[f.key]} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))} placeholder={f.placeholder} className="mt-1 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-white"/></label>)}<button className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 p-3 text-sm font-black text-black"><Plus className="h-4 w-4"/>Load battery</button></form>
 <section className="rounded-[1.6rem] border border-amber-300/10 bg-black/30 p-5"><div className="flex justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-amber-300">Live fulfillment</p><h2 className="font-black text-white">Code Requests</h2></div><button onClick={()=>void load()}><RefreshCw className="h-4 w-4 text-slate-400"/></button></div><div className="mt-4 space-y-2">{requests.filter(r=>['requested','pending'].includes(r.status)).length===0?<p className="text-sm text-slate-500">No code requests waiting.</p>:requests.filter(r=>['requested','pending'].includes(r.status)).map(r=><article key={r.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono font-black text-white">{r.phone_e164}</p><p className="text-xs text-slate-500">{r.bridger_name} · {r.method.toUpperCase()} · {r.status}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-amber-300"><Clock3 className="h-3 w-3"/>Deadline {new Date(r.deadline_at).toLocaleTimeString()}</p>{r.admin_message&&<p className="mt-2 text-xs text-slate-400">{r.admin_message}</p>}</div><div className="flex gap-2"><button onClick={()=>void respond(r.id,'pending')} className="rounded-lg border border-amber-300/20 px-3 py-2 text-[10px] font-black text-amber-300">Pending + reason</button><button onClick={()=>void respond(r.id,'code_ready')} className="rounded-lg bg-emerald-400 px-3 py-2 text-[10px] font-black text-black">Send code</button></div></div></article>)}</div></section></div>
 <section className="mt-5 rounded-[1.6rem] border border-white/10 bg-black/30 p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-emerald-300">Administration inventory</p><h2 className="font-black text-white">Aphone battery stock</h2></div><button onClick={()=>void load()} className="rounded-lg border border-white/10 p-2" aria-label="Refresh number inventory"><RefreshCw className="h-4 w-4 text-slate-400"/></button></div><div className="mt-3 space-y-2">{loading?<p className="text-slate-500">Loading…</p>:numbers.length===0?<p className="text-sm text-slate-500">No numbers loaded.</p>:numbers.map(n=><article key={n.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-mono font-bold text-white">{n.phone_e164}</p><p className="text-[10px] uppercase text-slate-500">Aphone · {n.country} · {n.status}{n.assigned_name?' · '+n.assigned_name:''}</p>{n.provider_reference&&<p className="mt-1 text-[10px] text-slate-600">Provider ref · {n.provider_reference}</p>}</div><div className="min-w-[190px] rounded-xl border border-white/10 bg-white/[.025] p-3 text-right"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Bridger price</p><p className="text-lg font-black text-white">{Number(n.price_flame_coin).toLocaleString()} FC</p><div className="mt-2 border-t border-white/10 pt-2"><p className="text-[9px] font-black uppercase tracking-wider text-amber-300">Admin acquisition cost</p><p className="text-sm font-black text-amber-100">{n.acquisition_cost==null?'Not set':Number(n.acquisition_cost).toLocaleString()}</p></div></div></div></article>)}</div></section></main>
}
